walmartlabs/concord

- plugins/tasks/http/src/main/java/com/walmartlabs/concord/plugins/http/HttpTaskUtils.java
fix the garbled code problem of json string body: set charset "UTF-8" when construct StringEntity.
> fix the garbled code problem of json string body: set charset "UTF-8" when construct StringEntity.

- server/dist/pom.xml
It was erroneously added in ce3899aec648b89062315e9797ad9ea4c00018d1
cc @brig
> concord-server: remove kafka-event-sink from dist

- server/impl/src/main/java/com/walmartlabs/concord/server/Listeners.java
- server/impl/src/test/java/com/walmartlabs/concord/server/ListenersTest.java
Use `ForkJoinPool` to run process event/audit/log listeners, wait for completion before returning.
The previous mechanism made no guarantees when exactly those listeners are called.
Now it also sets a (currently hard coded) time limit for notifications, 3 seconds for now - can make it configurable later.
cc @brig
> concord-server: use ForkJoinPool to run listeners, wait for completion

- agent/src/main/java/com/walmartlabs/concord/agent/Worker.java
- agent/src/main/java/com/walmartlabs/concord/agent/WorkerFactory.java
- agent/src/main/java/com/walmartlabs/concord/agent/executors/JobExecutorFactory.java
- agent/src/main/java/com/walmartlabs/concord/agent/executors/runner/RunnerJobExecutor.java
- agent/src/main/java/com/walmartlabs/concord/agent/guice/AgentDependencyManager.java
- agent/src/main/java/com/walmartlabs/concord/agent/guice/AgentDependencyManagerProvider.java
- agent/src/main/java/com/walmartlabs/concord/agent/guice/AgentImportManager.java
- agent/src/main/java/com/walmartlabs/concord/agent/guice/AgentImportManagerProvider.java
- agent/src/main/java/com/walmartlabs/concord/agent/guice/WorkerModule.java
- it/compat/README.md
- it/compat/pom.xml
- it/compat/src/test/java/com/walmartlabs/concord/it/compat/ITConstants.java
- it/compat/src/test/java/com/walmartlabs/concord/it/compat/LocalModeIT.java
- it/compat/src/test/java/com/walmartlabs/concord/it/compat/OldAgentIT.java
1.60.0 broke the `LOCAL` mode in testcontainers-concord:
```
1) A binding to com.walmartlabs.concord.imports.ImportManager was already configured at org.eclipse.sisu.wire.LocatorWiring.
at com.walmartlabs.concord.agent.guice.WorkerModule.configure(WorkerModule.java:92)
2) A binding to com.walmartlabs.concord.dependencymanager.DependencyManager was already configured at org.eclipse.sisu.wire.LocatorWiring.
at com.walmartlabs.concord.agent.guice.WorkerModule.configure(WorkerModule.java:93)
```
When running in the same VM both the Agent and the Server were trying to bind the same interfaces.
This PR:
- creates wrapper types for the Agent's `ImportManager` and `DependencyManager`. This way both the Server's and the Agent's instances can co-exist in the same Injector;
- adds a test for the …
> concord-agent, it: change bindings to allow testcontainers-concord LOCAL mode

- README.md
- agent/src/assembly/start.sh
- common/pom.xml
- docker-images/base/oss/Dockerfile
- docker-images/pom.xml
- docker-images/server/oss/Dockerfile
- pom.xml
- runtime/v1/impl/src/main/java/com/walmartlabs/concord/runner/Main.java
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/InjectorFactory.java
- server/dist/src/assembly/start.sh
- targetplatform/pom.xml
- add `jdk11` Maven profile;
- fix `Module` imports;
- update JOOQ and Guice versions to get rid of `Illegal reflective access by...` warnings;
- print out path to Java and the current Java version in the Agent's and the Server's start.sh scripts. Useful for debugging.
All tests seems to be happy when I run them locally
```
$ ./mvnw clean install -Pit -Pdocker -Pjdk11
```
cc @brig
> project: more JDK11 compatibility updates

- agent/src/assembly/start.sh
Similar to the Server's start.sh. Useful for Java 11's `-XX:+UseContainerSupport`.
cc @brig
> concord-agent: add CONCORD_JAVA_OPTS to the start script

- plugins/tasks/ansible/src/main/java/com/walmartlabs/concord/plugins/ansible/AnsibleAuthFactory.java
- plugins/tasks/ansible/src/main/java/com/walmartlabs/concord/plugins/ansible/PrivateKeyAuth.java
Do not remove private key files when using `auth.privateKey.path`.
Otherwise it is impossible to run Ansible multiple times in row using the same private key file.
> ansible: do not remove private key files

- server/impl/src/main/java/com/walmartlabs/concord/server/audit/AuditLogEntry.java
- server/impl/src/main/java/com/walmartlabs/concord/server/package-info.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/event/NewProcessEvent.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/event/ProcessEventEntry.java
Use a package-level `@Value.Style(jdkOnly = true)` annotation instead of individually marking each interface/class.
> concord-server: apply jdkOnly to all Immutables in the module

- server/impl/src/main/java/com/walmartlabs/concord/server/org/CreateOrganizationResponse.java
- server/impl/src/main/java/com/walmartlabs/concord/server/org/OrganizationDao.java
- server/impl/src/main/java/com/walmartlabs/concord/server/org/OrganizationManager.java
- server/impl/src/main/java/com/walmartlabs/concord/server/org/OrganizationOperationResult.java
- server/impl/src/main/java/com/walmartlabs/concord/server/org/OrganizationResource.java
Replace `OrganizationManager#create` and `#update` with a single method - `createOrUpdate`.
Use DB advisory locking to avoid data races when, for example, two requests are handled by two
different Server instances connected to the same DB.
> concord-server: replace OrganizationManager's create and update methods with a single one

- server/db/pom.xml
- server/db/src/main/resources/com/walmartlabs/concord/server/db/v0.44.0.xml
- server/db/src/main/resources/com/walmartlabs/concord/server/db/v1.34.3.xml
- server/db/src/main/resources/com/walmartlabs/concord/server/db/v1.58.0.xml
- server/dist/src/main/resources/concord-server.conf
- server/plugins/ansible/db/pom.xml
- server/plugins/ansible/db/src/main/resources/com/walmartlabs/concord/server/plugins/ansible/db/liquibase.xml
- server/plugins/noderoster/db/pom.xml
- server/plugins/noderoster/db/src/main/java/com/walmartlabs/concord/server/plugins/noderoster/db/DatabaseModule.java
- server/plugins/noderoster/db/src/main/resources/com/walmartlabs/concord/server/plugins/noderoster/db/liquibase.xml
Allows deployment of the schema without the SUPERUSER role.
Adds an optional mode when `SUPERUSER` is not required:
```
concord-server {
db {
changeLogParameters {
superuserAvailable = "false"
}
}
}
```
Useful for certain managed environments where SUPERUSER is typically not available.
Docs: https://github.com/walmartlabs/concord-website/pull/27
> concord-server: non-superuser version of 1.58.0 migrations

- client/src/main/java/com/walmartlabs/concord/client/ClientUtils.java
- client/src/main/java/com/walmartlabs/concord/client/SecretClient.java
Header names in `ClientUtils#getHeaders` were case-sensitive which is incorrect.
> concord-client: fix potential NPE in ClientUtils

- server/db/pom.xml
- server/db/src/main/resources/com/walmartlabs/concord/server/db/v0.44.0.xml
- server/db/src/main/resources/com/walmartlabs/concord/server/db/v1.34.3.xml
- server/dist/src/main/resources/concord-server.conf
- server/plugins/ansible/db/pom.xml
- server/plugins/noderoster/db/pom.xml
- server/plugins/noderoster/db/src/main/resources/com/walmartlabs/concord/server/plugins/noderoster/db/liquibase.xml
Gate all "CREATE EXTENSION" changesets with a new option - `createExtensionAvailable`
(default is `true`).
Allows DB schema deployment in enviroments where `SUPERUSER` is not available but
`CREATE EXTENSION` is.
> concord-server: new schema option "createExtensionAvailable"

- plugins/tasks/ansible/src/main/resources/com/walmartlabs/concord/plugins/ansible/callback/concord_events.py
- server/plugins/ansible/impl/src/main/java/com/walmartlabs/concord/server/plugins/ansible/AnsibleEvent.java
example ansible step:
```
uri:
url: 'http://host/'
method: POST
body_format: json
body: "{{ undefined_variable }}"
ignore_errors: '{{ ignore | default("true") }}'   # saved as is in event
```
> ansible: fix invalid type of `ignore_error` param in ansible event

- runtime/v2/model/src/main/java/com/walmartlabs/concord/runtime/v2/parser/LogGrammar.java
- runtime/v2/model/src/main/java/com/walmartlabs/concord/runtime/v2/parser/TaskGrammar.java
- runtime/v2/model/src/main/java/com/walmartlabs/concord/runtime/v2/parser/ThrowGrammar.java
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/vm/ExpressionCommand.java
Update the v2 grammar to support the `name` attribute for `log`, `throw` and `expr` steps.
E.g.
```yaml
- name: "two plus two"
expr: ${2 + 2}
- name: "Throw an error"
throw: "boom!"
- name: "Log stuff"
log: "stuff"
```
> runtime-v2: allow "log", "throw" and "expr" steps to have names

- server/impl/src/main/java/com/walmartlabs/concord/server/security/ldap/UserLdapGroupSynchronizer.java
Remove a disabled user's LDAP groups when synchronizing. Currently, disabled users show up in Teams configured with the LDAP group.
> server: Remove user's LDAP groups when disabling

- server/sdk/pom.xml
- server/sdk/src/main/java/com/walmartlabs/concord/server/sdk/audit/AuditEvent.java
It should've been `@Nullable` in the first place.
> concord-server-sdk: userId in AuditEvent is optional

- it/server/src/test/java/com/walmartlabs/concord/it/server/ExternalImportsIT.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/ProcessEntry.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/ProcessResource.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/queue/ProcessQueueDao.java
The only place where we read `Imports` is when a process fork is created.
Removing it from `ProcessEntry` saves a bit of time by not deserializing the data.
Also helps us to avoid issues when an unknown import type is present in the `process_queue` data.
Before this change it would lead to a deserialization error when trying to get a list of processes.
> concord-server: remove imports from ProcessEntry

- docker-images/ansible/oss/Dockerfile
- docker-images/base/oss/Dockerfile
Starting from 1.13, Docker ships its own mini-init.
We don't need dumb-init anymore.
As a bonus, the change allows us to build Concord Docker images on aarch64 :-)
> docker-images: remove dumb-init from the base image

- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/el/DefaultExpressionEvaluator.java
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/el/ExpressionEvaluator.java
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/el/LazyExpressionEvaluator.java
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/vm/SetVariablesCommand.java
- runtime/v2/runner/src/test/java/com/walmartlabs/concord/runtime/v2/runner/MainTest.java
- runtime/v2/runner/src/test/resources/com/walmartlabs/concord/runtime/v2/runner/nestedSet/concord.yml
Enhance the `set` step implementation to support nested values, e.g.
```yaml
- set:
x.y: 123
x.z: "${myTask.getAValue()}"
```
Doesn't support partial eval results. I.e. this isn't working:
```
- set:
x.y: 123
x.z: "${myTask.getDerivedValue(x.y)}"
```
> runtime-v2: support for nested "set"

- server/impl/src/main/java/com/walmartlabs/concord/server/org/jsonstore/JsonStoreDataResource.java
Allow both PUT and POST methods to add/update data in JSON stores.
Fixes compatibility with the Terraform plugin's `concord` backend
in the v2 version of the task (TF wants to POST state updates).
> concord-server: allow POSTing JSON store data

- plugins/tasks/ansible/src/main/java/com/walmartlabs/concord/plugins/ansible/v2/AnsibleTaskV2.java
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/vm/RetryWrapper.java
- runtime/v2/runner/src/test/java/com/walmartlabs/concord/runtime/v2/runner/MainTest.java
- runtime/v2/runner/src/test/resources/com/walmartlabs/concord/runtime/v2/runner/retry/concord.yml
- runtime/v2/sdk/src/main/java/com/walmartlabs/concord/runtime/v2/sdk/Constants.java
- runtime/v2/sdk/src/main/java/com/walmartlabs/concord/runtime/v2/sdk/ContextUtils.java
RetryWrapper was incorrectly adding NextRetry command to the stack
instead of using it as the frame's exception handler.
> runtime-v2: fix "retry" triggering successful commands twice

- agent/src/main/java/com/walmartlabs/concord/agent/cfg/ImportConfiguration.java
- agent/src/main/java/com/walmartlabs/concord/agent/guice/AgentImportManagerProvider.java
- agent/src/main/resources/concord-agent.conf
- cli/src/main/java/com/walmartlabs/concord/cli/Run.java
- cli/src/main/java/com/walmartlabs/concord/cli/runner/CliImportsNormalizer.java
- imports/src/main/java/com/walmartlabs/concord/imports/DefaultImportManager.java
- imports/src/main/java/com/walmartlabs/concord/imports/DirectoryProcessor.java
- imports/src/main/java/com/walmartlabs/concord/imports/Import.java
- imports/src/main/java/com/walmartlabs/concord/imports/ImportManagerFactory.java
- imports/src/main/java/com/walmartlabs/concord/imports/MvnProcessor.java
- imports/src/main/java/com/walmartlabs/concord/imports/RepositoryProcessor.java
- imports/src/main/java/com/walmartlabs/concord/imports/package-info.java
- it/runtime-v2/src/test/java/com/walmartlabs/concord/it/runtime/v2/ConcordConfiguration.java
- it/runtime-v2/src/test/java/com/walmartlabs/concord/it/runtime/v2/ImportsIT.java
- it/runtime-v2/src/test/java/com/walmartlabs/concord/it/runtime/v2/SmtpIT.java
- it/runtime-v2/src/test/java/com/walmartlabs/concord/it/runtime/v2/TemplateIT.java
- it/runtime-v2/src/test/resources/com/walmartlabs/concord/it/runtime/v2/dirImport/other.concord.yml
- repository/src/main/java/com/walmartlabs/concord/repository/Snapshot.java
- runtime/v2/model/src/main/java/com/walmartlabs/concord/runtime/v2/parser/ImportsGrammar.java
- runtime/v2/model/src/main/java/com/walmartlabs/concord/runtime/v2/parser/YamlValueType.java
- runtime/v2/model/src/test/java/com/walmartlabs/concord/project/runtime/v2/parser/YamlOkParserTest.java
- runtime/v2/model/src/test/resources/007.yml
- server/dist/src/main/resources/concord-server.conf
- server/impl/src/main/java/com/walmartlabs/concord/server/ImportManagerProvider.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/ImportsNormalizerFactory.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/pipelines/processors/StateImportingProcessor.java
- server/impl/src/main/java/com/walmartlabs/concord/server/repository/ClasspathRepositoryProvider.java
- targetplatform/pom.xml
Allows importing of local (external to ${workDir}) directories.
Add Server/Agent configuration parameter to disable the `dir` importer by default.
Example:
```yaml
imports:
- dir:
src: "/home/user/concord_stuff"
```
I'll add an IT once testcontainers-concord supports custom Server/Agent configurations in the `DOCKER` mode (https://github.com/concord-workflow/testcontainers-concord/issues/19)
> concord-imports: add support for "dir" imports

- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/compiler/CheckpointCompiler.java
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/vm/CheckpointCommand.java
- runtime/v2/runner/src/test/java/com/walmartlabs/concord/runtime/v2/runner/MainTest.java
- runtime/v2/runner/src/test/resources/com/walmartlabs/concord/runtime/v2/runner/checkpointExpr/concord.yml
Eval expressions in checkpoint names, just like we do it in v1.
> runtime-v2: expression support in the checkpoint step

- runtime/v2/model/src/main/java/com/walmartlabs/concord/runtime/v2/model/Retry.java
- runtime/v2/model/src/main/java/com/walmartlabs/concord/runtime/v2/parser/FlowCallGrammar.java
- runtime/v2/model/src/main/java/com/walmartlabs/concord/runtime/v2/parser/RetryGrammar.java
- runtime/v2/model/src/main/java/com/walmartlabs/concord/runtime/v2/parser/ScriptGrammar.java
- runtime/v2/model/src/main/java/com/walmartlabs/concord/runtime/v2/parser/TaskGrammar.java
- runtime/v2/model/src/test/java/com/walmartlabs/concord/project/runtime/v2/parser/YamlOkParserTest.java
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/vm/RetryWrapper.java
- runtime/v2/runner/src/test/java/com/walmartlabs/concord/runtime/v2/runner/MainTest.java
In v1 the `delay` parameter is in seconds. Make the v2 version assume the same.
Use `Duration` instead of a long value.
Rename `CommonGrammar` to `RetryGrammar` as it is the only thing there.
There's no good built-in way to format `Durations`, so I left the original log message intact.
> runtime-v2: assume "retry.delay" is in seconds

- console2/src/components/organisms/ProcessLogActivityV2/index.tsx
Increase the log segment limit to 100 (instead of 30) to accommodate larger v2 flows.
Ultimately, we'd need a proper paging mechanism for log segments.
> concord-console: increase the default log segment limit to 100

- client/pom.xml
- client/src/main/java/com/walmartlabs/concord/client/ClientUtils.java
- client/src/main/java/com/walmartlabs/concord/client/SecretClient.java
- plugins/tasks/crypto/src/main/java/com/walmartlabs/concord/plugins/crypto/CryptoTaskV2.java
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/DefaultSecretService.java
- runtime/v2/sdk/src/main/java/com/walmartlabs/concord/runtime/v2/sdk/SecretService.java
Rename `SecretParams#name()` to `secretName()` for consistency.
Throw ApiException instead of RuntimeException to allow access to the status code/response headers.
> runtime-v2, concord-client: rename SecretParams#name to secretName, throw ApiException

- runtime/v2/model/src/main/java/com/walmartlabs/concord/runtime/v2/parser/ConfigurationGrammar.java
- runtime/v2/model/src/test/java/com/walmartlabs/concord/project/runtime/v2/parser/YamlErrorParserTest.java
- runtime/v2/model/src/test/resources/errors/configuration/018.yml
Add truncateMaxStringLength, truncateMaxArrayLength and truncateMaxDepth to the grammar.
> runtime-v2: add missing EventConfiguration fields to the grammar

- runtime/v2/sdk/src/main/java/com/walmartlabs/concord/runtime/v2/sdk/TaskResult.java
Fix the error message when a TaskResult value is not a serializable value.
> runtime-v2: fix the TaskResult values assertion message

- agent/src/main/java/com/walmartlabs/concord/agent/Agent.java
- agent/src/main/java/com/walmartlabs/concord/agent/cfg/AbstractRunnerConfiguration.java
- agent/src/main/java/com/walmartlabs/concord/agent/cfg/AgentConfiguration.java
- agent/src/main/java/com/walmartlabs/concord/agent/cfg/RepositoryCacheConfiguration.java
- agent/src/main/java/com/walmartlabs/concord/agent/cfg/Utils.java
- agent/src/main/java/com/walmartlabs/concord/agent/executors/JobExecutorFactory.java
- agent/src/main/java/com/walmartlabs/concord/agent/executors/runner/RunnerJobExecutor.java
- agent/src/main/resources/concord-agent.conf
- server/impl/src/main/java/com/walmartlabs/concord/server/org/secret/SecretManager.java
A new configuration option:
```
concord-agent {
runner {
persistentWorkDir = "/path/to/dir"
}
}
```
If specified, Agent will copy all files from the process' working directory
into a subdirectory of `persistentWorkDir` after the process ends (regardless
of the status).
This feature is planned to be used in testcontainers-concord to allow test authors
to inspect the process ${workDir}.
All copied files will be readable by all users (i.e. it sets `0644`
permissions for files and `755` for directories). Should *not* be used in production.
> concord-agent: option to keep workDir after the process ends

- it/runtime-v2/src/test/java/com/walmartlabs/concord/it/runtime/v2/ProcessIT.java
- it/runtime-v2/src/test/resources/com/walmartlabs/concord/it/runtime/v2/checkpoints/concord.yml
- it/runtime-v2/src/test/resources/com/walmartlabs/concord/it/runtime/v2/checkpointsParallel/concord.yml
- runtime/common/src/main/java/com/walmartlabs/concord/runtime/common/StateManager.java
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/Main.java
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/Runner.java
- runtime/v2/runner/src/test/java/com/walmartlabs/concord/runtime/v2/runner/MainTest.java
- runtime/v2/runner/src/test/java/com/walmartlabs/concord/runtime/v2/runner/TestCheckpointService.java
- runtime/v2/runner/src/test/resources/com/walmartlabs/concord/runtime/v2/runner/checkpointRestore/concord.yml
- targetplatform/pom.xml
Update the runner v2 to actually support checkpoints.
The previous implementation expected a checkpoint to have an eventRef associated with it.
Which was the case in v1, but not in v2. In v2 we can directly feed a ProcessSnapshot instance to the runtime.
Update the runner v2 and add some tests.
> runtime-v2: actually working checkpoints

- agent/src/main/java/com/walmartlabs/concord/agent/cfg/AbstractRunnerConfiguration.java
- agent/src/main/resources/concord-agent.conf
- it/server/src/test/java/com/walmartlabs/concord/it/server/SecretIT.java
- server/impl/src/main/java/com/walmartlabs/concord/server/org/secret/SecretManager.java
Use the current java (`${java.home}/bin/java`) if no `runner*.javaCmd` values provided.
Simplifies Agent configuration a little bit.
> concord-agent: use current java by default

- it/server/src/test/java/com/walmartlabs/concord/it/server/GitHubTriggersV2IT.java
- it/server/src/test/resources/com/walmartlabs/concord/it/server/githubTests/repos/v2/files/concord.yml
- server/impl/src/main/java/com/walmartlabs/concord/server/events/github/Constants.java
- server/impl/src/main/java/com/walmartlabs/concord/server/events/github/GithubTriggerV2Processor.java
- server/impl/src/main/java/com/walmartlabs/concord/server/events/github/Payload.java
trigger definition:
```
- github:
entryPoint: "onPush"
version: 2
conditions:
type: "push"
...
files:
modified:
- "concord.yml"
added:
- "new.*"
removed:
- ....
```
> concord-server: support for added/removed/modified files in github push trigger conditions

- console2/src/api/process/event/index.ts
- console2/src/components/organisms/TaskCallDetails/index.tsx
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/remote/TaskCallEventRecordingListener.java
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/tasks/TaskCallEvent.java
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/tasks/TaskCallInterceptor.java
- runtime-v2: update the TaskCallInterceptor and TaskCallEventRecordingListener to record TaskResults
- concord-console: bring back the "Output" table in the task call details popup (only for v2 processes)
> runtime-v2, concord-console: record and display task outputs

- console2/src/api/org/project/index.ts
- console2/src/components/organisms/ProjectActivity/ProjectSettings.tsx
- console2/src/components/organisms/ProjectOutVariablesModeActivity/index.tsx
- console2/src/components/organisms/index.ts
- it/server/src/test/java/com/walmartlabs/concord/it/server/OutVariablesProjectIT.java
- server/db/src/main/resources/com/walmartlabs/concord/server/db/liquibase.xml
- server/db/src/main/resources/com/walmartlabs/concord/server/db/v1.66.0.xml
- server/impl/src/main/java/com/walmartlabs/concord/server/org/project/ProjectDao.java
- server/impl/src/main/java/com/walmartlabs/concord/server/org/project/ProjectEntry.java
- server/impl/src/main/java/com/walmartlabs/concord/server/org/project/ProjectManager.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/pipelines/NewProcessPipeline.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/pipelines/processors/AssertOutVariablesProcessor.java
- server/impl/src/test/java/com/walmartlabs/concord/server/process/pipelines/processors/ConfigurationProcessorTest.java
- server/impl/src/test/java/com/walmartlabs/concord/server/security/secret/SecretDaoTest.java
- server/impl/src/test/java/com/walmartlabs/concord/server/template/ProjectDaoTest.java
out variables restrictions:
- DISABLED (default): 'Sending custom out variable names is disabled. Only out variables defined in concord.yml can be used.';
- OWNERS: "Only the project's owner and team members with OWNER privileges can specify custom out variable names.";
- TEAM_MEMBERS: "Only the members of the teams assigned to the project's can specify custom out variable names.";
- ORG_MEMBERS: "Only the project's organization members can specify custom out variable names.";
- EVERYONE: 'Everyone can can specify custom out variable names. This is the least secure option.';
> server: configurable out variables mode for project

- server/impl/src/main/java/com/walmartlabs/concord/server/org/jsonstore/JsonStoreManager.java
- server/impl/src/main/java/com/walmartlabs/concord/server/org/project/ProjectAccessManager.java
- server/impl/src/main/java/com/walmartlabs/concord/server/org/secret/SecretManager.java
record example:
```
{
"access":{
"teams":[
{
"id":"00000000-0000-0000-0000-000000000000",
"level":"OWNER"
}
],
"replace":true
},
"storeId":"d6fb4e42-f759-11ea-aec8-0242ac110002",
"requestId":"ad4a79cc-9db2-4132-a39f-9cc7c9890b22",
"actionSource":{
"type":"UI"
}
}
```
> server: audit log changes in entity access

- it/console/src/test/java/com/walmartlabs/concord/it/console/FormsIT.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/form/FormUtils.java
Before this change, the Server converted `dateTime` form fields to its default time zone.
Now we explicitly convert those values to UTC.
This fixes the issue with local testing - tests can check for a fixed value instead of trying to use the local time zone.
Shouldn't affect the production as the servers typically use UTC anyway.
> concord-server: convert dateTime fields to UTC

- it/common/pom.xml
- it/common/src/main/java/com/walmartlabs/concord/it/common/OffsetDateTimeDeserializer.java
- it/common/src/main/java/com/walmartlabs/concord/it/common/ServerCompatModule.java
- it/server/src/test/java/com/walmartlabs/concord/it/server/ProcessMetadataIT.java
Add a Jackson module to support the Server API's timestamp format (`yyyy-MM-dd'T'HH:mm:ss.SSSX`).
Normally, the client handles the deserialization, but if someone wants to use the client's model
classes they need to use Concord Server's own timestamp format.
> it: support Server timestamp format

- server/impl/src/main/java/com/walmartlabs/concord/server/boot/filters/ConcordAuthenticatingFilter.java
to prevent browser show auth popup
> concord-server: don't send the auth header for ui requests

- server/impl/src/main/java/com/walmartlabs/concord/server/metrics/MetricInterceptor.java
Avoid potential races in embedded situation (e.g. testcontainers-concord's LOCAL mode).
> concord-server: use CHM in MetricInterceptor

- agent/src/main/java/com/walmartlabs/concord/agent/Worker.java
- agent/src/main/java/com/walmartlabs/concord/agent/executors/runner/RunnerJobExecutor.java
looks like DependencyManager threw Throwable exception.
agent logs:
```
14:21:48.232 [DefaultMetadataResolver-507-1] [ERROR] c.w.c.d.DependencyManager - transferFailed -> GET FAILED https://repo.maven.apache.org/maven2/org/webjars/npm/lodash._createset/maven-metadata.xml <> /home/concord/.m2/repository/org/webjars/npm/lodash._createset/maven-metadata-central.xml
14:21:49.369 [pool-1-thread-1822] [INFO ] com.walmartlabs.concord.agent.Worker - exec ['d6ace27d-e6d9-4738-948c-3621095b7ebc'] -> removing the payload directory: /tmp/concord/payload/workDir893755744059954205
```
process logs:
```
17:10:00 [INFO ] Resolving process dependencies...
17:24:58 [WARN ] Process failed to start for more than '15 minutes'
```
> agent: better exception handling in worker

- plugins/tasks/resource/pom.xml
- plugins/tasks/resource/src/main/java/com/walmartlabs/concord/plugins/resource/ResourceTask.java
- plugins/tasks/resource/src/main/java/com/walmartlabs/concord/plugins/resource/ResourceTaskCommon.java
- plugins/tasks/resource/src/main/java/com/walmartlabs/concord/plugins/resource/v2/ResourceTaskV2.java
- plugins/tasks/resource/src/test/java/com/walmartlabs/concord/plugins/resource/ResourceTaskCommonTest.java
Useful for injecting values into other YAML files (e.g. Helm values.yaml).
Example:
```yaml
flows:
default:
- set:
data:
x: 1
y:
a: 10
b: 20
z:
- "a"
- "b"
- set:
result: |
data: ${resource.prettyPrintYaml(data, 2)}
- log: |
-------------------------------------------
${result}
```
```
> concord run
Starting...
16:22:05.564 [main] -------------------------------------------
data:
x: 1
y:
a: 10
b: 20
z:
- "a"
- "b"
...done!
```
> resource-tasks: implement prettyPrintYaml method

- server/impl/src/main/java/com/walmartlabs/concord/server/org/secret/SecretDao.java
- server/impl/src/main/java/com/walmartlabs/concord/server/org/secret/SecretManager.java
- server/impl/src/main/java/com/walmartlabs/concord/server/org/secret/store/SecretStore.java
- server/impl/src/main/java/com/walmartlabs/concord/server/org/secret/store/concord/ConcordSecretStore.java
Allow explicit transactions in `SecretManager#createBinaryData`
SecretStores can now participate in transactions as well.
> concord-server: tx aware createBinaryData

- plugins/tasks/slack/src/main/java/com/walmartlabs/concord/plugins/slack/SlackTask.java
@InjectVariables into class field not working with expressions/scripts :(
> slack-tasks: read default variables from context instead of @InjectVariables

- server/db/src/main/java/com/walmartlabs/concord/db/DataSourceUtils.java
+ remove unused `#migrateDb(DataSource, DatabaseChangeLogProvider)` method.
> concord-server: minor logging improvements when running Liquibase migrations

- server/db/src/main/resources/com/walmartlabs/concord/server/db/liquibase.xml
- server/db/src/main/resources/com/walmartlabs/concord/server/db/v1.69.0.xml
- server/impl/src/main/java/com/walmartlabs/concord/server/task/TaskScheduler.java
- simplify task poll conditions;
- save task error stack trace into DB;
- better task heartbeat/stalled updates.
> server: task scheduler up

- runtime/v2/runner/src/main/resources/logback.xml
no more messages:
```
Replaced standard System.out and System.err PrintStreams with SLF4JPrintStreams
Redirected System.out and System.err to SLF4J for this context
```
> runtime-v2: disable SLF4JPrintStreams info messages

- cli/src/main/java/com/walmartlabs/concord/cli/Run.java
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/vm/TaskCallCommand.java
Fix NPE when a task returns `null` instead of a `TaskResult`.
Also, print out the error's stacktrace in `verbose` mode in the CLI.
> runtime-v2: fix potential NPE in TaskCallCommand

- runtime/v2/model/src/main/java/com/walmartlabs/concord/runtime/v2/model/FlowCallOptions.java
- runtime/v2/model/src/main/java/com/walmartlabs/concord/runtime/v2/parser/FlowCallGrammar.java
- runtime/v2/model/src/main/java/com/walmartlabs/concord/runtime/v2/parser/GrammarV2.java
- runtime/v2/model/src/main/java/com/walmartlabs/concord/runtime/v2/parser/YamlValueType.java
- runtime/v2/model/src/main/java/com/walmartlabs/concord/runtime/v2/serializer/FlowCallStepSerializer.java
- runtime/v2/model/src/test/java/com/walmartlabs/concord/project/runtime/v2/ProjectSerializerV2Test.java
- runtime/v2/model/src/test/java/com/walmartlabs/concord/project/runtime/v2/parser/YamlErrorParserTest.java
- runtime/v2/model/src/test/resources/errors/flowCall/004.yml
- runtime/v2/model/src/test/resources/serializer/flowCallStepOutExpr.yml
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/vm/FlowCallCommand.java
- runtime/v2/runner/src/test/java/com/walmartlabs/concord/runtime/v2/runner/MainTest.java
- runtime/v2/runner/src/test/resources/com/walmartlabs/concord/runtime/v2/runner/flowOutExpr/concord.yml
```
flows:
default:
- call: test
out:
v: ${x.y}
- log: "v: ${v}" # 123
test:
- set:
x:
y: 123
```
> runtime-v2: support for expressions in `out` block of flow call step

- runtime/v2/model/src/main/java/com/walmartlabs/concord/runtime/v2/model/Expression.java
- runtime/v2/model/src/main/java/com/walmartlabs/concord/runtime/v2/model/ExpressionOptions.java
- runtime/v2/model/src/main/java/com/walmartlabs/concord/runtime/v2/parser/ExpressionGrammar.java
- runtime/v2/model/src/main/java/com/walmartlabs/concord/runtime/v2/parser/YamlValueType.java
- runtime/v2/model/src/main/java/com/walmartlabs/concord/runtime/v2/serializer/ExpressionStepSerializer.java
- runtime/v2/model/src/test/java/com/walmartlabs/concord/project/runtime/v2/ProjectSerializerV2Test.java
- runtime/v2/model/src/test/java/com/walmartlabs/concord/project/runtime/v2/parser/YamlErrorParserTest.java
- runtime/v2/model/src/test/java/com/walmartlabs/concord/project/runtime/v2/parser/YamlOkParserTest.java
- runtime/v2/model/src/test/resources/errors/expression/004.yml
- runtime/v2/model/src/test/resources/serializer/expressionStepOutExpr.yml
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/vm/ExpressionCommand.java
- runtime/v2/runner/src/test/java/com/walmartlabs/concord/runtime/v2/runner/MainTest.java
- runtime/v2/runner/src/test/resources/com/walmartlabs/concord/runtime/v2/runner/exprOutExpr/concord.yml
```
flows:
default:
- expr: "${ {'k': 'v'} }"
out:
theThingIActuallyWanted: "${result.k}"
- log: "result: ${theThingIActuallyWanted}"
```
> runtime-v2: support for expressions in `out` block of expr call step

- agent/src/main/java/com/walmartlabs/concord/agent/guice/AgentImportManagerProvider.java
- cli/src/main/java/com/walmartlabs/concord/cli/Run.java
- imports/src/main/java/com/walmartlabs/concord/imports/DefaultImportManager.java
- imports/src/main/java/com/walmartlabs/concord/imports/ImportProcessingException.java
- repository/src/main/java/com/walmartlabs/concord/repository/GitCliRepositoryProvider.java
- repository/src/main/java/com/walmartlabs/concord/repository/RepositoryCache.java
- server/impl/src/main/java/com/walmartlabs/concord/server/ImportManagerProvider.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/pipelines/processors/FailProcessor.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/pipelines/processors/ProcessDefinitionProcessor.java
now:
```
12:50:41 [INFO ] Storing policy '[concord-base]' data
12:51:14 [ERROR] Process failed: Error while processing import {
"type" : "git",
"url" : "https://github.com/walmartlabs/concord.git",
"version" : "xxx",
"path" : "examples/hello_world",
"dest" : "concord"
}. Error: Couldn't find any revision to build. Verify the repository and branch configuration.
```
before:
```
19:08:51 [ERROR] Process failed: Error while loading the project, check the syntax. com.walmartlabs.concord.repository.RepositoryException: git fetch failed
com.walmartlabs.concord.server.process.ProcessException: Error while loading the project, check the syntax. com.walmartlabs.concord.repository.RepositoryException: git fetch failed
at com.walmartlabs.concord.server.process.pipelines.processors.ProcessDefinitionPr …
```
> server: better error messages while processing imports

- plugins/tasks/concord/pom.xml
- plugins/tasks/concord/src/main/java/com/walmartlabs/concord/client/ConcordTask.java
- plugins/tasks/concord/src/main/java/com/walmartlabs/concord/client/ConcordTaskParams.java
- plugins/tasks/concord/src/test/java/com/walmartlabs/concord/client/ConcordTaskParamsTest.java
In v1 version of the task, `forks` entries inherit "global" values (such as `tags`). This PR makes the v2 version of the task behave in the same way.
Test case:
```yaml
configuration:
runtime: "concord-v2"
flows:
default:
- task: concord
in:
action: fork
tags:
- "xyz"
forks:
- entryPoint: sayHello # doesn't inherit "tags"
sync: true
```
> concord-tasks: fix "global" parameters not being inherited by "forks"

- plugins/tasks/concord/src/main/java/com/walmartlabs/concord/client/ConcordTask.java
- plugins/tasks/concord/src/main/java/com/walmartlabs/concord/client/ConcordTaskCommon.java
- plugins/tasks/concord/src/main/java/com/walmartlabs/concord/client/ConcordTaskParams.java
E.g.
```
- task: concord
in:
action: kill
instanceId: [] # empty list, produced by (for example) ${concord.listSubprocesses(...)}
```
> concord-tasks: 'kill' shouldn't error on empty instanceId lists

- server/db/src/main/java/com/walmartlabs/concord/db/PgUtils.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/queue/FilterUtils.java
Add condition to consider the process when flavours are given as list in requirements i,e more than one flavour
for ex: `{"agent": {"flavor": ["k8s-s-w3", "k8s-kitt", "k8s-s-w2"]}}`
> Process-requirement-api: filter to consider list of agent flavors

- console2/src/api/process/event/index.ts
- console2/src/components/molecules/ProcessElementList/index.tsx
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/el/resolvers/TaskMethodResolver.java
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/remote/TaskCallEventRecordingListener.java
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/tasks/TaskCallEvent.java
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/tasks/TaskCallInterceptor.java
> runtime-v2, concord-console: record post events for failed tasks, mark failed tasks on the events tab

- client/src/main/java/com/walmartlabs/concord/client/ClientUtils.java
before:
```
00:18:40 [WARN ] call error: 'Server response: '
00:18:40 [ERROR] (concord.yml): Error @ line: 16, col: 11. Secret not found: Default/Something
```
after:
```
00:25:04 [ERROR] (concord.yml): Error @ line: 16, col: 11. Secret not found: Default/Something
```
> client: logs up

- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/el/resolvers/TaskMethodResolver.java
before:
```
00:36:10 [ERROR] (concord.yml): Error @ line: 14, col: 9. javax.el.ELException: com.walmartlabs.concord.runtime.v2.sdk.UserDefinedException: BOO2
```
after:
```
00:39:21 [ERROR] (concord.yml): Error @ line: 14, col: 9. BOO2
```
> runtime-v2: less useless exceptions

- server/db/src/main/resources/com/walmartlabs/concord/server/db/liquibase.xml
- server/db/src/main/resources/com/walmartlabs/concord/server/db/v1.75.0.xml
- server/impl/src/main/java/com/walmartlabs/concord/server/events/GithubEventResource.java
- server/impl/src/main/java/com/walmartlabs/concord/server/events/github/Constants.java
- server/impl/src/main/java/com/walmartlabs/concord/server/events/github/GithubTriggerV2Processor.java
- server/impl/src/main/resources/com/walmartlabs/concord/server/org/triggers/concord.yml
```
- github:
version: 2
entryPoint: "onChange"
conditions:
type: "push"
...
repositoryInfo:
- repository: ".*"
enabled: true
```
> server: new github trigger condition repositoryInfo.enabled

- common/src/main/java/com/walmartlabs/concord/common/LogUtils.java
- repository/src/main/java/com/walmartlabs/concord/repository/GitClient.java
after:
```
16:36:13.488 [pool-2-thread-2] [INFO ] [a7bdce60-b995-433f-8bfe-2c3d39676bac] c.w.concord.repository.GitClient - > git rev-parse HEAD
16:36:13.496 [pool-1-thread-6] [INFO ] [a7bdce60-b995-433f-8bfe-2c3d39676bac] c.w.concord.repository.GitClient - GIT (stdout): 7b1d5d6e26b725692c7fd60ac4b04b23db7dde71
```
before:
```
16:36:13.488 [pool-2-thread-2] [INFO ] [a7bdce60-b995-433f-8bfe-2c3d39676bac] c.w.concord.repository.GitClient - > git rev-parse HEAD
16:36:13.496 [pool-1-thread-6] [INFO ] [] c.w.concord.repository.GitClient - GIT (stdout): 7b1d5d6e26b725692c7fd60ac4b04b23db7dde71
```
> git-client: preserve MDC in threads

- CHANGELOG.md
- runtime/v1/impl/src/main/java/com/walmartlabs/concord/runner/engine/DockerServiceImpl.java
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/DefaultDockerService.java
Recent docker-client versions use different wording for `docker pull`
errors in case if the registry is unavailable.
```
> docker --version
Docker version 19.03.14, build 5eb3275d40
> docker pull localhost:12345/non-existing
Using default tag: latest
Error response from daemon: Get http://localhost:12345/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```
> runtime-v1, runtime-v2: more retryable docker pull errors

- agent/src/main/java/com/walmartlabs/concord/agent/executors/runner/RunnerJobExecutor.java
- policy-engine/pom.xml
- policy-engine/src/main/java/com/walmartlabs/concord/policyengine/DependencyRewritePolicy.java
- policy-engine/src/main/java/com/walmartlabs/concord/policyengine/DependencyRewriteRule.java
- policy-engine/src/main/java/com/walmartlabs/concord/policyengine/PolicyEngine.java
- policy-engine/src/main/java/com/walmartlabs/concord/policyengine/PolicyEngineRules.java
- policy-engine/src/test/java/com/walmartlabs/concord/policyengine/PolicyEngineRulesTest.java
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/PolicyEngineProvider.java
- server/impl/src/test/java/com/walmartlabs/concord/server/process/pipelines/processors/ConfigurationProcessorTest.java
example:
```
{
"dependencyRewrite":[
{
"msg":"\n*******************************\n\nansible-tasks < 1.71.0 is deprecated.\nPlease update your dependencies to the latest recommended versions.\n\n*******************************\n",
"groupId":"com.walmartlabs.concord.plugins.basic",
"fromVersion":"1.62.0",
"toVersion":"1.70.3",
"artifactId":"ansible-tasks",
"value":"mvn://com.walmartlabs.concord.plugins.basic:ansible-tasks:1.71.0"
}
]
}
```
will replace all ansible deps with versions [1.62.0, 1.70.3] to 1.71.0
process logs:
```
13:53:43 [INFO ] Updating dependency from 'mvn://com.walmartlabs.concord.plugins.basic:ansible-tasks:1.70.0' to 'mvn://com.walmartlabs.concord.plugins.basic:ansible-tasks:1.71.0'
13:53:43 [WARN ] 
*******************************
ansible-tasks < 1.71.0 is deprecated. …
```
> policy-engine: policy to rewrite dependency versions

- console2/src/api/org/index.ts
- console2/src/components/molecules/ProcessList/index.tsx
project configuration:
```
"meta": {
"ui": {
...
{
"source": "meta.myLinkValue",
"caption": "My Link",
"searchType": "substring",
"searchValueType": "string",
"render": "link"
}
]
}
```
concord.yml:
```
flows:
default:
- log: "Hello, ${name}!"
configuration:
arguments:
name: "Concord"
meta:
myLinkValue:
title: "PGPTOOLS-50937"
link: "https://ext/api/PGPTOOLS-50937"
```
result:
> console2: allow link columns in process list

- CHANGELOG.md
- common/src/main/java/com/walmartlabs/concord/common/ObjectInputStreamWithClassLoader.java
- it/runtime-v2/src/test/java/com/walmartlabs/concord/it/runtime/v2/ProcessIT.java
- it/runtime-v2/src/test/resources/com/walmartlabs/concord/it/runtime/v2/checkpointClasses/concord.yml
- it/tasks/serialization-test/pom.xml
- it/tasks/serialization-test/src/main/java/com/walmartlabs/concord/it/tasks/serializationtest/CustomBean.java
- it/tasks/serialization-test/src/main/java/com/walmartlabs/concord/it/tasks/serializationtest/CustomBeanTask.java
- runtime/common/src/main/java/com/walmartlabs/concord/runtime/common/StateManager.java
- runtime/v1/impl/src/main/java/com/walmartlabs/concord/runner/engine/FilePersistenceManager.java
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/Main.java
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/checkpoints/DefaultCheckpointService.java
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/guice/ProcessDependenciesModule.java
- runtime/v2/runner/src/test/java/com/walmartlabs/concord/runtime/v2/runner/MainTest.java
- targetplatform/pom.xml
Explicitly specify the classloader when deserializing checkpoints.
Before the change, checkpoints used the default classloader of the
runner which doesn't contain classes from `dependencies`.
While it is still not recommended to use 3rd party classes as flow
variables, it might be okay for situations when both the server
and the runtime have the same 3rd party JARs on the classpath.
> runtime-v2: use the dependencies classloader for checkpoints

- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/vm/WithItemsWrapper.java
`AbstractMap.SimpleImmutableEntry` is Serializable
> runtime-v2: use standard `AbstractMap.SimpleImmutableEntry` for WithItems

- CHANGELOG.md
- dependency-manager/pom.xml
- dependency-manager/src/main/java/com/walmartlabs/concord/dependencymanager/DependencyManager.java
- docker-images/base/oss/Dockerfile
- targetplatform/pom.xml
Example mvn.json:
```json
{
"repositories": [
{
"id": "host",
"url": "https://my-bucket.s3.us-west-2.amazonaws.com/maven",
"auth": {
"username": "user",
"password": "pwd",
"preemptiveAuth": "true"
}
}
]
}
```
> dependency-mananager: add support for preemptive basic auth

- client/src/main/template/libraries/okhttp-gson/ApiClient.mustache
Add `basePath` to the exception message. Useful for debugging.
E.g.
```
com.walmartlabs.concord.ApiException: (http://localhost:8001) Server response: Process instance not found
```
> concord-client: add basePath to exceptions

- server/db/src/main/java/com/walmartlabs/concord/db/PgUtils.java
- server/dist/src/main/resources/concord-server.conf
- server/impl/src/main/java/com/walmartlabs/concord/server/audit/AuditLogCleaner.java
- server/impl/src/main/java/com/walmartlabs/concord/server/cfg/LdapGroupSyncConfiguration.java
- server/impl/src/main/java/com/walmartlabs/concord/server/cfg/ProcessConfiguration.java
- server/impl/src/main/java/com/walmartlabs/concord/server/cfg/ProcessWatchdogConfiguration.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/ProcessCleaner.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/queue/ProcessQueueWatchdog.java
- server/impl/src/main/java/com/walmartlabs/concord/server/security/ldap/LdapGroupManager.java
- server/impl/src/main/java/com/walmartlabs/concord/server/security/ldap/UserLdapGroupSynchronizer.java
- server/impl/src/test/java/com/walmartlabs/concord/server/process/state/ProcessStateManagerTest.java
Before this change, the Server configuration used a mix of PostgreSQL
interval types and java.time.Duration. Additionally, the existing
Duration properties were converted into milliseconds which causes issues
with large values (e.g. can't set `audit.maxLogAge` interval to more
than `2147483647 ms` or ~24 days.
This PR changes all interval properties to Duration. When the value is
passed to PG it is rounded down to seconds (instead of milliseconds)
which allows values up to ~24000 days.
> concord-server: use java.time.Duration for all intervals in the config

- docker-images/ansible/oss/Dockerfile
`ansible` package installation thru pip3 has a dependency on cryptography package.
But the dependency version is not pinned to a specific version.
So every time ansible package is installed, it fetches the latest version of cryptography package (latest being 3.4.1).
Latest versions of cryptography packages have a dependency on Rust, so the installation fails with ModuleNotFoundError: No module named 'setuptools_rust' error.
Even if we install this package separately, the installation of cryptography package fails with error: Can not find Rust compiler error, since our images dont have Rust compiler installed.
This is to fix our failing Docker image builds, till we decide if we should install Rust on our base images, or continue pinning cryptography to <=3.3.1 (which was the last working …
> docker-images: Restrict cryptography dependency to 3.3.1

- pom.xml
- runtime/v2/sdk/pom.xml
- runtime/v2/sdk/src/main/java/com/walmartlabs/concord/runtime/v2/sdk/Context.java
- runtime/v2/sdk/src/main/java/com/walmartlabs/concord/runtime/v2/sdk/ContextUtils.java
- runtime/v2/sdk/src/main/java/com/walmartlabs/concord/runtime/v2/sdk/DependencyManager.java
- runtime/v2/sdk/src/main/java/com/walmartlabs/concord/runtime/v2/sdk/DockerContainerSpec.java
- runtime/v2/sdk/src/main/java/com/walmartlabs/concord/runtime/v2/sdk/DockerService.java
- runtime/v2/sdk/src/main/java/com/walmartlabs/concord/runtime/v2/sdk/Execution.java
- runtime/v2/sdk/src/main/java/com/walmartlabs/concord/runtime/v2/sdk/SensitiveData.java
- runtime/v2/sdk/src/main/java/com/walmartlabs/concord/runtime/v2/sdk/Task.java
- runtime/v2/sdk/src/main/java/com/walmartlabs/concord/runtime/v2/sdk/TaskProvider.java
- runtime/v2/sdk/src/main/java/com/walmartlabs/concord/runtime/v2/sdk/TaskResult.java
- runtime/v2/sdk/src/main/java/com/walmartlabs/concord/runtime/v2/sdk/WorkingDirectory.java
Document more methods in the runtime v2 SDK.
Make `javax.inject` an explicit dependency of the SDK.
Publish the javadoc artifact.
> runtime-v2: more SDK javadoc, publish javadoc artifact

- dependency-manager/src/main/java/com/walmartlabs/concord/dependencymanager/DependencyManager.java
So that clickable URLs in the UI don't end with `...`
> dependency-manager: remove dots from the resolveFile log

- server/dist/src/assembly/default.conf
Provide a way to override default configuration values without creating a server config file.
> concord-server: allow overriding of default cfg values

- common/src/main/java/com/walmartlabs/concord/common/IOUtils.java
> concord-common: skip outside paths when unzipping

- plugins/tasks/ansible/src/main/java/com/walmartlabs/concord/plugins/ansible/AnsibleEnv.java
- plugins/tasks/ansible/src/main/java/com/walmartlabs/concord/plugins/ansible/AnsibleLibs.java
for example for ansible with docker:
```
- task: ansible
in:
extraEnv:
PYTHONPATH: "/home/concord/shared"
...
```
> ansible: allow users to append custom libs into PYTHONPATH

- it/common/src/main/java/com/walmartlabs/concord/it/common/GitUtils.java
- it/server/src/test/java/com/walmartlabs/concord/it/server/AbstractGitHubTriggersIT.java
- it/server/src/test/java/com/walmartlabs/concord/it/server/GitHubTriggersV2IT.java
- runtime/v2/runner/src/test/java/com/walmartlabs/concord/runtime/v2/runner/el/HasVariableFunctionTest.java
- server/impl/src/main/java/com/walmartlabs/concord/server/events/github/GithubTriggerV2Processor.java
- server/impl/src/main/java/com/walmartlabs/concord/server/org/project/RepositoryDao.java
Currently, multiple repositories share a similar name with different endings in their URL, e.g.
```
[1] https://github.com/myorg/my-repo.git
[2] https://github.com/myorg/my-repo-tools.git
[3] https://github.com/myorg/my-repo-old.git
```
...when a `push` event is received for the repo with the shorter URL, all of the repositories are refreshed.
This fix implements a regular expression filter for finding the matching repository.
> concord-server: Fix repository refresh filtering on GitHub event

- repository/src/main/java/com/walmartlabs/concord/repository/GitClient.java
Cached repos are never pushed back to their origin. Disable auto-maintenance since it will just keep auto-maintenance-ing.
`git maintenance` was introduced in `2.29.0` and auto-maintenance is enabled by default. It can be controlled by `git config maintenance.auto` and the `fetch` parameter `--[no-]auto-maintenance`.
> git-client: Disable git auto-maintenance

- client/src/main/template/libraries/okhttp-gson/ApiClient.mustache
Show the status message instead.
> concord-client: skip empty bodies in error responses

- agent/src/main/java/com/walmartlabs/concord/agent/guice/WorkerModule.java
- agent/src/main/java/com/walmartlabs/concord/agent/logging/CombinedLogAppender.java
- agent/src/main/java/com/walmartlabs/concord/agent/logging/StdOutLogAppender.java
with `REDIRECT_RUNNER_TO_STDOUT=true` agent env variable runner logs prints to agent stdout:
```
...
14:25:15.040 [queue-client] [INFO ] c.w.c.server.queueclient.QueueClient - send ['ProcessRequest{correlationId='3', capabilities='{}'}'] -> done
RUNNER: 2021-03-15T11:25:15.102+0000 [INFO ] Resolving process dependencies...
RUNNER: 2021-03-15T11:25:15.675+0000 [INFO ] Checking the dependency policy...
RUNNER: 2021-03-15T11:25:15.691+0000 [INFO ] Dependencies: 
....
```
> agent: allow redirect runner logs to stdout

- agent/src/main/java/com/walmartlabs/concord/agent/cfg/AgentConfiguration.java
- agent/src/main/java/com/walmartlabs/concord/agent/cfg/PreForkConfiguration.java
- agent/src/main/java/com/walmartlabs/concord/agent/cfg/Utils.java
- agent/src/main/java/com/walmartlabs/concord/agent/executors/JobExecutorFactory.java
- agent/src/main/java/com/walmartlabs/concord/agent/executors/runner/ProcessPool.java
- agent/src/main/java/com/walmartlabs/concord/agent/executors/runner/RunnerCommandBuilder.java
- agent/src/main/java/com/walmartlabs/concord/agent/executors/runner/RunnerJobExecutor.java
- agent/src/main/java/com/walmartlabs/concord/agent/remote/AttachmentsUploader.java
- agent/src/main/resources/concord-agent.conf
- it/runtime-v1/src/test/java/com/walmartlabs/concord/it/runtime/v1/ConcordConfiguration.java
- it/runtime-v2/pom.xml
- it/runtime-v2/src/test/java/com/walmartlabs/concord/it/runtime/v2/ConcordConfiguration.java
- it/runtime-v2/src/test/java/com/walmartlabs/concord/it/runtime/v2/ProcessIT.java
- it/runtime-v2/src/test/resources/com/walmartlabs/concord/it/runtime/v2/checkpoints/concord.yml
- it/server/src/test/resources/agent.conf
- sdk/src/main/java/com/walmartlabs/concord/sdk/Constants.java
See the description of [the new concord-agent.conf parameters](https://github.com/walmartlabs/concord/compare/stable-workdir#diff-659ff82d720ea53124e3e275edd8ad0067c6fc36e9514cad060bb8c21da3f359R37).
I'll do some manual testing, but the startup time impact should be negligible for v2 processes.
Since we started using sisu-maven-plugin, the classpath scanning time is pretty much no longer an issue.
Setting `preforks.enabled = true` returns the old behavior which might be desired for v1-heavy environments.
> concord-agent: disable preforks by default, use stable workDir

- server/dist/src/main/resources/concord-server.conf
- server/impl/src/main/java/com/walmartlabs/concord/server/boot/HttpServer.java
- server/impl/src/main/java/com/walmartlabs/concord/server/cfg/ServerConfiguration.java
Use the `SameSite=Lax` policy for the session cookie to avoid cross-origin requests.
> concord-server: set SameSite=Lax for the session cookie

- server/impl/src/main/java/com/walmartlabs/concord/server/events/Events.java
- server/impl/src/main/java/com/walmartlabs/concord/server/events/github/GithubTriggerV2Processor.java
- server/impl/src/main/java/com/walmartlabs/concord/server/org/project/ProjectRepositoryManager.java
- server/impl/src/main/resources/com/walmartlabs/concord/server/org/triggers/concord.yml
Fixes the repo search pattern. Was not including ssh urls.
In the repository refresh workflow, we previously filtered the trigger on enabled repos. But if there's a mix of enabled and disabled repos all of them would get processed.
> concord-server: Only pass enabled repos to refresh task

- runtime/v2/model/src/main/java/com/walmartlabs/concord/runtime/v2/parser/ScriptGrammar.java
Support name attribute for log segment metadata.
```yaml
- name: "Custom script segment name"
script: groovy
body: |
log.info("Hello from customized script call")
```
> runtime-v2: Support 'name' attribute for script calls

- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/Main.java
before:
```
22:15:18 [ERROR] com.walmartlabs.concord.runtime.v2.sdk.UserDefinedException: boo
22:15:18 [ERROR] 	at com.walmartlabs.concord.plugins.throwex.ThrowExceptionTaskV2.execute(ThrowExceptionTaskV2.java:41)
22:15:18 [ERROR] 	at com.walmartlabs.concord.runtime.v2.runner.vm.TaskCallCommand.lambda$0(TaskCallCommand.java:84)
....
```
after:
```
17:06:43 [ERROR] 
com.walmartlabs.concord.runtime.v2.sdk.UserDefinedException: boo
at com.walmartlabs.concord.plugins.throwex.ThrowExceptionTaskV2.execute(ThrowExceptionTaskV2.java:41)
at com.walmartlabs.concord.runtime.v2.runner.vm.TaskCallCommand.lambda$0(TaskCallCommand.java:84)
```
> runtime-v2: log exception as a single error line

- agent/src/main/java/com/walmartlabs/concord/agent/cfg/ServerConfiguration.java
- agent/src/main/resources/concord-agent.conf
- docker-images/compose/concord.conf
- docker-images/run_dev.sh
- docker-images/server.conf
- it/console/pom.xml
- it/console/src/test/resources/agent.conf
- it/console/src/test/resources/server.conf
- it/runtime-v2/src/test/java/com/walmartlabs/concord/it/runtime/v2/FormIT.java
- it/server/src/test/resources/agent.conf
- it/server/src/test/resources/server.conf
- server/db/src/main/resources/com/walmartlabs/concord/server/db/liquibase.xml
- server/db/src/main/resources/com/walmartlabs/concord/server/db/v0.69.0.xml
- server/db/src/main/resources/com/walmartlabs/concord/server/db/v0.70.0.xml
- server/db/src/main/resources/com/walmartlabs/concord/server/db/v1.45.0.xml
- server/db/src/main/resources/com/walmartlabs/concord/server/db/v1.86.0.xml
- server/dist/src/main/resources/concord-server.conf
- server/liquibase-ext/src/main/java/com/walmartlabs/concord/server/liquibase/ext/ApiTokenCreator.java
- targetplatform/pom.xml
- vagrant/agent.conf
- vagrant/server.conf
- Initialize DB without a hard-coded default agent API token:  New DBs will now initialize with a random or config-provided default API token. Existing DBs that update to the next version will not be cleaned up--so if anyone is actually still using the old hard-coded tokens they need to manually rotate the agent API token in their agent config.
- Modify dev scripts (docker-compose, vagrant) to handle agent API token
- Remove `concordRunner` user and tokens: It's not used
> db: initialize with dynamic default agent token

- server/db/src/main/resources/com/walmartlabs/concord/server/db/v1.86.0.xml
Breaking change for systems that have never rotated the default Agent API token (😖).
> db: delete hard-coded API token

- cli/src/main/java/com/walmartlabs/concord/cli/Run.java
- cli/src/main/java/com/walmartlabs/concord/cli/runner/CliServicesModule.java
Make the CLI use a single configured instance of `DependencyManager`.
Before this change, the runtime was getting it's own instance with the default settings -- i.e. the cacheDir was not configured in the expected way.
> concord-cli: re-use the DependencyManager instance

- plugins/tasks/smtp/src/main/java/com/walmartlabs/concord/plugins/smtp/SmtpTaskV2.java
- plugins/tasks/smtp/src/test/java/com/walmartlabs/concord/plugins/smtp/SmtpTaskV2Test.java
Example policy config:
```json
{
"defaultProcessCfg": {
"processTimeout": "PT6H",
"defaultTaskVariables": {
"smtp": {
"smtpParams": {
"host": "my-smtp.example.com",
"port": 25
}
}
}
}
}
```
> smtp-tasks: Read default params in runtime-v2

- plugins/tasks/concord/src/main/java/com/walmartlabs/concord/client/ConcordTaskCommon.java
start/starExternal result:
```
{ok=true, threadId=0, id=05c9b1ed-fc9b-4ab5-ad66-3725bf2ea951}
```
single fork result:
```
{ok=true, threadId=0, id=0933608a-8299-4bd5-93e8-b72aa433f347}
```
multi fork:
```
{ok=true, threadId=0, ids=[0101a794-6f95-4d04-adaf-37279daf4f71, 4a40fdb6-dd9d-43e4-87ee-332d3a4af4f4, edcf7f8f-11ac-4130-ac81-b8ab479cee18]}
```
> concord-task: return process id/ids for start/startExternal/fork actions

- console2/src/components/molecules/LoadingEditor/index.tsx
after version up of monaco-editor
> console2: fix json store query editor

- server/impl/src/main/java/com/walmartlabs/concord/server/process/queue/ExternalProcessListenerHandler.java
Looks like after #390 we're no longer sending `PROCESS_STATUS` events to listeners.
This PR "fixes" the issue by re-using the existing `ProcessStatusListener` mechanism.
> concord-server: send PROCESS_STATUS events to listeners

- it/runtime-v1/pom.xml
- it/runtime-v1/src/test/java/com/walmartlabs/concord/it/runtime/v1/ProcessIT.java
- it/runtime-v1/src/test/resources/com/walmartlabs/concord/it/runtime/v1/yamlRootFile/concord.yaml
- it/runtime-v1/src/test/resources/com/walmartlabs/concord/it/runtime/v1/yamlRootFile/concord/extra.yaml
- it/runtime-v2/src/test/java/com/walmartlabs/concord/it/runtime/v2/ProcessIT.java
- it/runtime-v2/src/test/resources/com/walmartlabs/concord/it/runtime/v2/yamlRootFile/concord.yaml
- it/runtime-v2/src/test/resources/com/walmartlabs/concord/it/runtime/v2/yamlRootFile/concord/extra.concord.yaml
- runtime/loader/src/main/java/com/walmartlabs/concord/process/loader/ProjectLoader.java
- runtime/v2/model/src/main/java/com/walmartlabs/concord/runtime/v2/model/Resources.java
- runtime/v2/model/src/test/java/com/walmartlabs/concord/project/runtime/v2/ProjectLoaderV2Test.java
- runtime/v2/model/src/test/resources/multiProjectFile/concord.yml
- runtime/v2/model/src/test/resources/serializer/processDefinition.yml
- sdk/src/main/java/com/walmartlabs/concord/sdk/Constants.java
Allows `*.yaml` extension for the root project file.
For the runtime v2, load `concord/*.yaml` as well.
> runtime-v1, runtime-v2: add support for *.yaml files

- targetplatform/pom.xml
With regard to [GHSA-288c-cq4h-88gq](https://github.com/advisories/GHSA-288c-cq4h-88gq).
> targetplatform: update jackson-databind version to address CVE

- it/server/src/test/java/com/walmartlabs/concord/it/server/AnsibleRetryIT.java
- plugins/tasks/ansible/src/main/java/com/walmartlabs/concord/plugins/ansible/AnsibleTask.java
- plugins/tasks/ansible/src/main/java/com/walmartlabs/concord/plugins/ansible/TaskParams.java
- Fix bug where ansible plugin copied the playbook instead of the `.retry` file to `_attachments/`.
- Use the actual retry file name rather than hard-coded retry file name. Useful if multiple playbooks are run and need to be retried.
> ansible: fix retry file persistance

- runtime/v2/model/src/main/java/com/walmartlabs/concord/runtime/v2/parser/ExpressionGrammar.java
- runtime/v2/model/src/main/java/com/walmartlabs/concord/runtime/v2/parser/FlowCallGrammar.java
- runtime/v2/model/src/main/java/com/walmartlabs/concord/runtime/v2/parser/GrammarMisc.java
- runtime/v2/model/src/main/java/com/walmartlabs/concord/runtime/v2/parser/GrammarOptions.java
- runtime/v2/model/src/main/java/com/walmartlabs/concord/runtime/v2/parser/GroupOfStepsGrammar.java
- runtime/v2/model/src/main/java/com/walmartlabs/concord/runtime/v2/parser/LogGrammar.java
- runtime/v2/model/src/main/java/com/walmartlabs/concord/runtime/v2/parser/ScriptGrammar.java
- runtime/v2/model/src/main/java/com/walmartlabs/concord/runtime/v2/parser/TaskGrammar.java
- runtime/v2/model/src/main/java/com/walmartlabs/concord/runtime/v2/parser/ThrowGrammar.java
- runtime/v2/model/src/test/java/com/walmartlabs/concord/project/runtime/v2/parser/YamlErrorParserTest.java
- runtime/v2/model/src/test/java/com/walmartlabs/concord/project/runtime/v2/parser/YamlOkParserTest.java
- runtime/v2/model/src/test/resources/000.2.yml
- runtime/v2/model/src/test/resources/000.yml
```
flows:
default:
- log: "me"
name: Test
```
> runtime-v2: allow the `name` attribute anywhere in the step definition

- runtime/v2/model/src/main/java/com/walmartlabs/concord/runtime/v2/parser/GrammarV2.java
- runtime/v2/model/src/main/java/com/walmartlabs/concord/runtime/v2/parser/YamlObject.java
- runtime/v2/model/src/test/java/com/walmartlabs/concord/project/runtime/v2/parser/YamlErrorParserTest.java
- runtime/v2/model/src/test/resources/errors/configuration/005_1.yml
concord.yml:
```
configuration:
runtime: concord-v2
arguments:
k:
....
```
old message:
```
Error while loading a project file '005_1.yml', arguments value
```
new message:
```
(005_1.yml): Error @ line: 7, col: 7. Invalid value type, expected: NON_NULL, got: NULL. Remove attribute or complete the definition
while processing steps:
'arguments' @ line: 6, col: 3
'configuration' @ line: 1, col: 1
```
> runtime-v2: better parser error message

- it/server/src/test/java/com/walmartlabs/concord/it/server/JsonStoreIT.java
- it/server/src/test/java/com/walmartlabs/concord/it/server/ProjectIT.java
- it/server/src/test/java/com/walmartlabs/concord/it/server/SecretIT.java
- server/impl/src/main/java/com/walmartlabs/concord/server/org/jsonstore/JsonStoreResource.java
- server/impl/src/main/java/com/walmartlabs/concord/server/org/project/ProjectResource.java
- server/impl/src/main/java/com/walmartlabs/concord/server/org/secret/SecretResource.java
Empty list is okay for effectively removing all teams from resource access. No list (null) currently results in a 500 error from failed DB query. It'd be better to throw a bad request error before getting to the DB.
> server: throw error on null teams list in bulk access update

- runtime/v2/model/src/main/java/com/walmartlabs/concord/runtime/v2/model/TaskCallOptions.java
- runtime/v2/model/src/main/java/com/walmartlabs/concord/runtime/v2/parser/TaskGrammar.java
- runtime/v2/model/src/main/java/com/walmartlabs/concord/runtime/v2/serializer/TaskCallStepSerializer.java
- runtime/v2/model/src/test/java/com/walmartlabs/concord/project/runtime/v2/parser/YamlErrorParserTest.java
- runtime/v2/model/src/test/resources/serializer/taskCallStep.yml
- runtime/v2/model/src/test/resources/serializer/taskCallStepOutExpr.yml
- runtime/v2/model/src/test/resources/serializer/taskCallStepParallel.yml
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/tasks/TaskCallInterceptor.java
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/tasks/TaskException.java
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/vm/TaskCallCommand.java
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/vm/TaskCallUtils.java
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/vm/TaskResumeCommand.java
- runtime/v2/runner/src/test/java/com/walmartlabs/concord/runtime/v2/runner/MainTest.java
- runtime/v2/runner/src/test/resources/com/walmartlabs/concord/runtime/v2/runner/faultyTask2/concord.yml
- runtime/v2/runner/src/test/resources/com/walmartlabs/concord/runtime/v2/runner/faultyTaskOut/concord.yml
- runtime/v2/runner/src/test/resources/com/walmartlabs/concord/runtime/v2/runner/taskIgnoreErrors/concord.yml
- runtime/v2/runner/src/test/resources/com/walmartlabs/concord/runtime/v2/runner/taskIgnoreErrors2/concord.yml
- runtime/v2/sdk/src/main/java/com/walmartlabs/concord/runtime/v2/sdk/TaskResult.java
+ allows task to return variables even if the task failed
> runtime-v2: support for task `ignoreErrors` mode

- plugins/tasks/concord/src/main/java/com/walmartlabs/concord/client/ConcordTask.java
- plugins/tasks/concord/src/main/java/com/walmartlabs/concord/client/ConcordTaskCommon.java
- plugins/tasks/concord/src/main/java/com/walmartlabs/concord/client/v2/ConcordTaskV2.java
fixed:
- suspendForCompletion;
- returning Strings instead of UUIDs (I think these are small breaking change:);
- put fork id into `ids` variable;
> concord-task: broken runtime-v2 methods/actions #486

- it/runtime-v2/src/test/java/com/walmartlabs/concord/it/runtime/v2/ProcessIT.java
- it/runtime-v2/src/test/resources/com/walmartlabs/concord/it/runtime/v2/exitWithMeta/concord.yml
- runtime/v2/runner/src/test/resources/com/walmartlabs/concord/runtime/v2/runner/exitWithMeta/concord.yml
- runtime/v2/vm/src/main/java/com/walmartlabs/concord/svm/InMemoryState.java
```
flows:
default:
- log: "Hello"
- exit
configuration:
runtime: "concord-v2"
meta:
test: "INIT"
```
logs:
```
12:03:18 [ERROR] 
java.lang.IllegalStateException: Call frame doesn't exist: ThreadId{id=0}
at com.walmartlabs.concord.svm.InMemoryState.getFrames(InMemoryState.java:103)
at com.walmartlabs.concord.runtime.v2.runner.vm.VMUtils.getCombinedLocals(VMUtils.java:154)
at com.walmartlabs.concord.runtime.v2.runner.MetadataProcessor.afterCommand(MetadataProcessor.java:93)
at com.walmartlabs.concord.svm.ExecutionListenerHolder.fireAfterCommand(ExecutionListenerHolder.java:56)
at com.walmartlabs.concord.svm.VM.eval(VM.java:140)
at com.walmartlabs.concord.svm.VM.execute(VM.java:170)
at com.walmartlabs.concord.svm.VM.start(VM.java:54)
at …
```
> runtime-v2: fix MetadataProcessor exception when called after `exit` step

- server/impl/src/main/java/com/walmartlabs/concord/server/process/queue/ProcessQueueDao.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/queue/ProcessQueueManager.java
fixes this test:
```
ExclusiveProcessIT.testExclusiveCancelOld:77 expected:<CANCELLED> but was:<FINISHED>
```
```
p1 history: [class ProcessStatusHistoryEntry {
01:59:06 [INFO ]     id: fbacf84c-48c2-11ec-a9c0-0242c0a86003
01:59:06 [INFO ]     status: NEW
01:59:06 [INFO ]     changeDate: 2021-11-18T22:58:02.490Z
01:59:06 [INFO ] }, class ProcessStatusHistoryEntry {
01:59:06 [INFO ]     id: fc4d75ba-48c2-11ec-a9c0-0242c0a86003
01:59:06 [INFO ]     status: ENQUEUED
01:59:06 [INFO ]     changeDate: 2021-11-18T22:58:03.540Z
01:59:06 [INFO ] }, class ProcessStatusHistoryEntry {
01:59:06 [INFO ]     id: fc4d81d6-48c2-11ec-b176-0242c0a86003
01:59:06 [INFO ]     status: CANCELLED
01:59:06 [INFO ]     changeDate: 2021-11-18T22:58:03.543Z
01:59:06 [INFO ] }, class ProcessStatusHistoryEntry { …
```
> server: fix concurrent process status update

- plugins/tasks/smtp/src/main/java/com/walmartlabs/concord/plugins/smtp/SmtpTaskV2.java
- plugins/tasks/smtp/src/test/java/com/walmartlabs/concord/plugins/smtp/SmtpTaskV2Test.java
now we can define default variables as:
```
smtp:
host:  ..
port: ...
```
instead of: 
```
smtp:
smtpParams:
host: ...
port: ...
```
> smtp: cfg from default variables fix

- README.md
- docker-images/compose/docker-compose.yml
- docker-images/pom.xml
- docker-images/run_dev.sh
- it/server/pom.xml
- pom.xml
front end maven plugin up - [details](https://github.com/eirslett/frontend-maven-plugin/blob/master/CHANGELOG.md#1110)
docker maven plugin up - [details](https://github.com/fabric8io/docker-maven-plugin/issues/1257)
Node version up - [details](https://github.com/nvm-sh/nvm#install--update-script)
mvn build using [docker desktop for macos](https://www.docker.com/products/docker-desktop) needs following workaround
```
brew install socat
socat TCP-LISTEN:2375,reuseaddr,fork UNIX-CONNECT:/var/run/docker.sock &
export DOCKER_HOST=tcp://127.0.0.1:2375
```
> concord-parent: support for apple M1 silicon 

- it/server/src/test/java/com/walmartlabs/concord/it/server/CronIT.java
- it/server/src/test/resources/com/walmartlabs/concord/it/server/cronProfiles/concord.yml
Unlucky timing can make this test wind up with 1 or 3+ processes which really confuses things when inspecting a combined list of processes. We aren't really looking for 2 processes--we want 1 processes from each trigger/profile (3 will work as long as at least 1 is from either profile).
This change locates the processes based on tags set in their profiles. It also bumps the test timeout to 4 minutes. Sometimes the default 2 minutes isn't enough to 1) let the ConcordSystem process fire and detect/refresh the repo trigger and 2) wait till next cron fire and 3) execute two processes to `FINISHED`
> it: fix flaky CronIT

- agent/src/main/java/com/walmartlabs/concord/agent/logging/LocalProcessLog.java
- agent/src/main/java/com/walmartlabs/concord/agent/logging/SegmentHeaderParser.java
- agent/src/main/java/com/walmartlabs/concord/agent/logging/SegmentedLogsConsumer.java
- agent/src/test/java/com/walmartlabs/concord/agent/executors/runner/SegmentHeaderParserTest.java
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/logging/ConcordLogEncoder.java
- runtime/v2/runner/src/test/java/com/walmartlabs/concord/runtime/v2/runner/MainTest.java
fixed an issue where a segment was marked as `running` but had already been `finished`.
> runtime-v2: fix segment status parse

- runtime/v2/model/src/main/java/com/walmartlabs/concord/runtime/v2/schema/ProcessDefinitionConfigurationMixIn.java
this is not a concord.yml option
> runtime-v2: remove configuration.activeProfiles from json schema

- agent/src/main/java/com/walmartlabs/concord/agent/cfg/AgentConfiguration.java
- agent/src/main/java/com/walmartlabs/concord/agent/guice/AgentDependencyManagerConfigurationProvider.java
- agent/src/main/resources/concord-agent.conf
- dependency-manager/src/main/java/com/walmartlabs/concord/dependencymanager/DependencyManager.java
- dependency-manager/src/main/java/com/walmartlabs/concord/dependencymanager/DependencyManagerConfiguration.java
new agent configuration parameter:
```
dependencyStrictRepositories = true|false
```
> agent: allow ignore artifact descriptor repositories

- it/runtime-v2/src/test/java/com/walmartlabs/concord/it/runtime/v2/ProcessIT.java
- it/runtime-v2/src/test/resources/com/walmartlabs/concord/it/runtime/v2/formWithTimeout/concord.yml
- runtime/v2/model/src/main/java/com/walmartlabs/concord/runtime/v2/model/ProcessDefinitionConfiguration.java
- runtime/v2/model/src/main/java/com/walmartlabs/concord/runtime/v2/parser/ConfigurationGrammar.java
- runtime/v2/model/src/test/java/com/walmartlabs/concord/project/runtime/v2/ProjectLoaderV2Test.java
- runtime/v2/model/src/test/java/com/walmartlabs/concord/project/runtime/v2/parser/YamlErrorParserTest.java
- runtime/v2/model/src/test/resources/errors/configuration/023.yml
- runtime/v2/model/src/test/resources/multiProjectFile/concord.yml
- runtime/v2/model/src/test/resources/multiProjectFile/concord/1.concord.yml
We _do_ support `suspendTimeout` if it's provided in a process start payload, project configuration, or policy, but not directly in `concord.yml` . This fixes that.
> runtime-v2: project document support for suspendTimeout

- it/server/src/test/java/com/walmartlabs/concord/it/server/ConcordTaskIT.java
- it/server/src/test/resources/com/walmartlabs/concord/it/server/concordSubWithNullArg/concord.yml
- it/server/src/test/resources/com/walmartlabs/concord/it/server/concordSubWithNullArg/myPayload/concord.yml
- runtime/v2/model/src/main/java/com/walmartlabs/concord/runtime/v2/model/ProcessDefinitionConfiguration.java
- runtime/v2/sdk/src/main/java/com/walmartlabs/concord/runtime/v2/sdk/AllowNulls.java
- runtime/v2/sdk/src/main/java/com/walmartlabs/concord/runtime/v2/sdk/ProcessConfiguration.java
fix for "Process failed: Error while processing effective concord.yml: arguments value"
> runtime-v2: allow `null` values in configuration.arguments

- it/server/src/test/java/com/walmartlabs/concord/it/server/AbstractServerIT.java
- it/server/src/test/java/com/walmartlabs/concord/it/server/AnsibleIT.java
- it/server/src/test/java/com/walmartlabs/concord/it/server/AttachmentRbacIT.java
- plugins/tasks/ansible/src/main/java/com/walmartlabs/concord/plugins/ansible/AnsibleTask.java
- plugins/tasks/ansible/src/main/resources/com/walmartlabs/concord/plugins/ansible/callback/concord_trace.py
new file `ansible_stats_v2.json`:
```
[ {
"stats" : {
"ok" : [ "127.0.0.1" ],
"failures" : [ ],
"unreachable" : [ ],
"changed" : [ ],
"skipped" : [ ]
},
"exitCode" : 0,
"playbook" : "playbook/hello.yml",
"eventCorrelationId" : "9bb13aad-70cf-414a-a8f4-a8387e0a6e35"
}, {
"stats" : {
"ok" : [ "127.0.0.1" ],
"failures" : [ ],
"unreachable" : [ ],
"changed" : [ ],
"skipped" : [ ]
},
"exitCode" : 0,
"playbook" : "playbook/hello2.yml",
"eventCorrelationId" : "0fdd2f9b-c7a4-4225-8a7f-47a17bbed174"
} ]
```
> ansible: stats file for flow with multiple playbooks

- server/db/src/main/resources/com/walmartlabs/concord/server/db/liquibase.xml
- server/db/src/main/resources/com/walmartlabs/concord/server/db/v1.96.0.xml
- server/impl/src/main/java/com/walmartlabs/concord/server/role/RoleDao.java
- server/impl/src/main/java/com/walmartlabs/concord/server/role/RoleResource.java
- server/impl/src/main/java/com/walmartlabs/concord/server/user/UserDao.java
Support of ldap group for roles
API endpoints
* Add LDAP group for a role
```
PUT  - /api/v1/role/<roleName>/ldapGroups
body: ["group1", "group2"...]
```
* List LDAP groups for a role
```
GET - /api/v1/role/<roleName>/ldapGroups
```
With this access for `concordAdmin` can be managed by LDAP groups
> server: adding support of ldap groups for Roles

- plugins/tasks/http/src/main/java/com/walmartlabs/concord/plugins/http/SimpleHttpClient.java
Fixes
```
[WARNING] skip failed file : Could not extract header on file /home/ibodrov/prj/walmartlabs/concord/plugins/tasks/http/src/main/java/com/walmartlabs/concord/plugins/http/SimpleHttpClient.java for reason Can only have one file header start tag : *****
org.codehaus.mojo.license.header.InvalideFileHeaderException: Could not extract header on file /home/ibodrov/prj/walmartlabs/concord/plugins/tasks/http/src/main/java/com/walmartlabs/concord/plugins/http/SimpleHttpClient.java for reason Can only have one fi
le header start tag : *****
```
> http-tasks: update log message to avoid issues with license-maven-plugin

- it/server/src/test/java/com/walmartlabs/concord/it/server/OutVariablesIT.java
- it/server/src/test/java/com/walmartlabs/concord/it/server/OutVariablesProjectIT.java
- it/server/src/test/resources/com/walmartlabs/concord/it/server/example/_main.json
- server/impl/src/main/java/com/walmartlabs/concord/server/process/PayloadBuilder.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/pipelines/EnqueueProcessPipeline.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/pipelines/processors/AssertOutVariablesProcessor.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/pipelines/processors/ConfigurationProcessor.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/pipelines/processors/OutVariablesSettingProcessor.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/pipelines/processors/cfg/ProcessConfigurationUtils.java
Alternative to https://github.com/walmartlabs/concord/pull/608
Pros and cons...This approach doesn't double-parse the project. Instead it double-checks out variables.
1. Checks for out variables given in direct request parameters (e.g. `curl https://.../api/v1/process?out=myVarA,myVarB`) in the `NewProcessPipeline`
2. _After_ the project is parsed in `EnqueueProcessPipeline`, all the `out` variables are consolidated and the check is made again for out variables being added in a project that doesn't allow it.
The main difference is that the process entry gets created here and fails immediately if it fails on the second check. In https://github.com/walmartlabs/concord/pull/608, the process entry never gets created at all.
> server: fix out vars processing and restrictions (alternative)

- it/console/src/test/java/com/walmartlabs/concord/it/console/CustomFormsIT.java
- it/console/src/test/resources/com/walmartlabs/concord/it/console/customForm/concord.yml
- it/console/src/test/resources/com/walmartlabs/concord/it/console/customForm/forms/testForm/index.html
- server/impl/src/main/java/com/walmartlabs/concord/server/console/CustomFormServiceV2.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/form/FormServiceV2.java
File upload in runtime-v2 custom forms is broken. The submitted data is being converted twice. the first conversion writes the uploaded file to a temp directory for upload to process_state (that's good). But the second run ends up overwriting the file with the filename as the contents.
Solution is to only convert once, which is what non-custom form service and runtime-v1 do.
> server: runtime-v2 custom forms file field fix

- .github/workflows/ci.yml
I always forget that docker system prune doesn't remove old volumes.
> project: prune Docker volumes before build

- server/impl/src/main/resources/com/walmartlabs/concord/server/org/triggers/concord.yml
Remove redundant info that adds up to a whole lot of logging data in a busy concord instance. Same info is still available in the UI on the process status tab.
> concord-server: remove log call for github event in repository refresh flow

- console2/src/api/org/secret/index.ts
- console2/src/components/organisms/SecretActivity/index.tsx
- console2/src/components/organisms/SecretRenameActivity/index.tsx
- console2/src/components/organisms/SecretVisibilityActivity/index.tsx
- console2/src/state/data/secrets/index.ts
- console2/src/state/data/secrets/types.ts
> concord-console: fix for change visibility and renaming of secrets from UI

- cli/src/main/java/com/walmartlabs/concord/cli/Lint.java
- cli/src/test/java/com/walmartlabs/concord/cli/AbstractTest.java
- cli/src/test/java/com/walmartlabs/concord/cli/LintTest.java
- cli/src/test/resources/com/walmartlabs/concord/cli/lintV1/concord.yml
- cli/src/test/resources/com/walmartlabs/concord/cli/lintV1/concord/extra.concord.yml
- cli/src/test/resources/com/walmartlabs/concord/cli/lintV2/concord.yml
- cli/src/test/resources/com/walmartlabs/concord/cli/lintV2/concord/extra.concord.yml
Concord's project loader normalizes the resource glob with an absolute path.
https://github.com/walmartlabs/concord/blob/66fc4e40af7daf4ce61fd004906eba183d7c42d1/runtime/v2/model/src/main/java/com/walmartlabs/concord/runtime/v2/ProjectLoaderV2.java#L209
However, the CLI linter currently treats the command-line supplied `targetDir` as-is which breaks the resource filtering inside the project loader.
> concord-cli: ensure absolute target dir

- server/impl/src/main/java/com/walmartlabs/concord/server/process/waits/ProcessWaitWatchdog.java
In a busy environment, it's possible for wait conditions to come in faster than they can be dispatched in a loop. This keeps the loop going with a small (maybe just one) element in each loop. Then that keeps processes (checked in an earlier iteration) that have been ready to resume for a while to be ignored until the `processWaits()` method gets lucky and returns nothing.
> concord-server: termintate process wait watchdog loop on batches less than fetch limit

- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/vm/UpdateLocalsCommand.java
- runtime/v2/runner/src/test/java/com/walmartlabs/concord/runtime/v2/runner/MainTest.java
- runtime/v2/runner/src/test/resources/com/walmartlabs/concord/runtime/v2/runner/argsFromArgs/concord.yml
```
configuration:
arguments:
args:
k1: v1
k2: ${context.variables().get('args.k1')}   # in runtime-v1: k2 = v1, in runtime-v2: k2 = null
```
> runtime-v2: allow access to the current argument when that argument is evaluated

- console2/src/api/noderoster/index.ts
- console2/src/api/process/index.ts
- console2/src/components/molecules/ProcessStatusTable/index.tsx
- it/runtime-v1/src/test/java/com/walmartlabs/concord/it/runtime/v1/ProcessIT.java
- it/server/src/test/java/com/walmartlabs/concord/it/server/ConcordTaskForkFromGitRepoIT.java
- it/server/src/test/resources/com/walmartlabs/concord/it/server/concordTaskFork/concord.yml
- server/db/src/main/resources/com/walmartlabs/concord/server/db/v0.79.0.xml
- server/impl/src/main/java/com/walmartlabs/concord/server/process/ProcessEntry.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/pipelines/processors/ForkRepositoryInfoProcessor.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/pipelines/processors/RepositoryInfoUpdateProcessor.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/queue/ProcessQueueDao.java
it's useless in UI and wastes db space :)
commit message is still available as process variable `projectInfo.repoCommitMessage`
> server: process_queue.commit_msg removed

- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/Main.java
same as runtime v1.
```
01:02:42 [ERROR] The variable 'boom' must be set. Exiting.
01:02:43 [ERROR] Process exit code: 1
01:02:43 [INFO ] Process status: FAILED
```
> runtime-v2: "throw" with a string value shouldn't produce a stacktrace

- it/server/pom.xml
- it/server/src/test/java/com/walmartlabs/concord/it/server/ProcessIT.java
- it/server/src/test/resources/com/walmartlabs/concord/it/server/effectiveYaml/concord.yml
- runtime/loader/src/main/java/com/walmartlabs/concord/process/loader/model/Options.java
- runtime/loader/src/main/java/com/walmartlabs/concord/process/loader/v2/EffectiveProcessDefinitionProviderV2.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/pipelines/processors/EffectiveProcessDefinitionProcessor.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/pipelines/processors/EntryPointProcessor.java
effective yaml now contains correct entry point
> runtime-v2: fix entryPoint in effective yaml

- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/vm/ExpressionCommand.java
if the user needs a log segment then he can add `name` attribute to the expression step.
logs look clearer without this segment :)
> runtime-v2: do not create log segment for expression by default

- agent/src/main/java/com/walmartlabs/concord/agent/executors/runner/RunnerCommandBuilder.java
- server/dist/src/main/java/com/walmartlabs/concord/server/dist/Main.java
- server/impl/src/main/java/com/walmartlabs/concord/server/ConcordServer.java
- server/impl/src/main/java/com/walmartlabs/concord/server/Listeners.java
- server/impl/src/main/java/com/walmartlabs/concord/server/agent/AgentCommandWatchdog.java
- server/impl/src/main/java/com/walmartlabs/concord/server/audit/AuditLogCleaner.java
- server/impl/src/main/java/com/walmartlabs/concord/server/boot/BackgroundTasks.java
- server/impl/src/main/java/com/walmartlabs/concord/server/org/triggers/TriggerScheduler.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/ProcessCleaner.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/locks/ProcessLocksWatchdog.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/queue/ProcessQueueWatchdog.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/waits/ProcessWaitWatchdog.java
- server/impl/src/main/java/com/walmartlabs/concord/server/security/apikey/ApiKeyCleaner.java
- server/impl/src/main/java/com/walmartlabs/concord/server/security/apikey/ApiKeyExpirationNotifier.java
- server/impl/src/main/java/com/walmartlabs/concord/server/security/ldap/UserLdapGroupSynchronizer.java
- server/impl/src/main/java/com/walmartlabs/concord/server/task/SchedulerDao.java
- server/impl/src/main/java/com/walmartlabs/concord/server/task/TaskScheduler.java
- server/impl/src/main/java/com/walmartlabs/concord/server/user/UserManager.java
- server/impl/src/test/java/com/walmartlabs/concord/server/ListenersTest.java
- server/plugins/ansible/impl/src/main/java/com/walmartlabs/concord/server/plugins/ansible/EventFetcher.java
- server/plugins/noderoster/impl/src/main/java/com/walmartlabs/concord/server/plugins/noderoster/processor/AnsibleEventsProcessor.java
- server/sdk/src/main/java/com/walmartlabs/concord/server/sdk/ScheduledTask.java
I'm gradually replacing the usage of `@Named` autowiring with explicit bindings using `Module`.
The idea is that the top-level modules (e.g. `ConcordServer`) and server plugins are autowired by Sisu while all internal modules are wired explicitly using Guice `Module`s. This should provide better re-usability of pieces of concord-server -- e.g., for testing and creating Concord-based tools.
> concord-server: @Inject refactoring (part 1)

- server/db/src/main/resources/com/walmartlabs/concord/server/db/v1.98.1.xml
- server/dist/src/main/resources/concord-server.conf
when the value in quotes, it is used as is.
> server-db: secret salt default value as decoded base64 value

- it/runtime-v2/src/test/java/com/walmartlabs/concord/it/runtime/v2/FormIT.java
- it/runtime-v2/src/test/resources/com/walmartlabs/concord/it/runtime/v2/customFormValues/concord.yml
- runtime/v2/model/src/main/java/com/walmartlabs/concord/runtime/v2/model/FormCallOptions.java
- runtime/v2/model/src/main/java/com/walmartlabs/concord/runtime/v2/parser/FormsGrammar.java
- runtime/v2/model/src/main/java/com/walmartlabs/concord/runtime/v2/parser/YamlValueType.java
- runtime/v2/model/src/main/java/com/walmartlabs/concord/runtime/v2/serializer/FormCallStepSerializer.java
- runtime/v2/model/src/test/java/com/walmartlabs/concord/project/runtime/v2/parser/YamlErrorParserTest.java
- runtime/v2/model/src/test/java/com/walmartlabs/concord/project/runtime/v2/parser/YamlOkParserTest.java
- runtime/v2/model/src/test/resources/006.yml
- runtime/v2/model/src/test/resources/errors/formCall/005.yml
- runtime/v2/model/src/test/resources/errors/formCall/006.yml
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/vm/FormCallCommand.java
Enables support for expressions in `- form:` calls for `values` and `runAs` options.
```yaml
- set:
extraValues:
hello: world
customRunAs: { }
- set:
customRunAs.username:
- 'admin'
- form: myForm
fields: # ...
values: "${extraValues}"
runAs: "${customRunAs}"
```
> runtime-v2: allow expression for form call values and runAs

- it/runtime-v2/src/test/java/com/walmartlabs/concord/it/runtime/v2/ProcessIT.java
- it/runtime-v2/src/test/resources/com/walmartlabs/concord/it/runtime/v2/forkAfterForm/concord.yml
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/Main.java
state of the parent process overwrites the fork variables (e.g. fork after form).
now fork arguments overrides parent process variables (state).
> runtime-v2: fix fork args

- agent/src/main/java/com/walmartlabs/concord/agent/cfg/ServerConfiguration.java
- agent/src/main/java/com/walmartlabs/concord/agent/remote/QueueClientProvider.java
- agent/src/main/resources/concord-agent.conf
- server/queue-client/src/main/java/com/walmartlabs/concord/server/queueclient/QueueClient.java
- server/queue-client/src/main/java/com/walmartlabs/concord/server/queueclient/QueueClientConfiguration.java
Configurable delays for successful and unsuccessful (connection errors) polling attempts.
> concord-agent: make more delays configurable

- cli/pom.xml
- cli/src/main/java/com/walmartlabs/concord/cli/Run.java
- cli/src/main/java/com/walmartlabs/concord/cli/runner/CliServicesModule.java
- cli/src/main/java/com/walmartlabs/concord/cli/runner/EventLoggerExecutionListener.java
```
Starting...
>>> 'Task: log' at concord.yml:30
15:48:03.504 [main] All variables: {myVar=world, newVar= Hello earth, url=https://rubygems.org, txId=f29ebf5c-ed3d-4ba1-98d1-1a49b14f4a23, workDir=/Users/brig/prj/github/concord/examples/runtime-v2/demo-flow/target}
>>> 'Check: ${hasVariable('projectInfo.orgName')}' at concord.yml:32
>>> 'Task: log' at concord.yml:36
15:48:03.507 [main] Nope, we do not have 'orgName' variable
>>> 'Flow call: externalFlow' at concord.yml:38
>>> 'Task: log' at concord/test.concord.yml:6
...
```
> cli: log step info with --verbose

- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/script/VariablesSanitizer.java
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/vm/LoopItemSanitizer.java
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/vm/LoopWrapper.java
- runtime/v2/runner/src/test/java/com/walmartlabs/concord/runtime/v2/runner/MainTest.java
- runtime/v2/runner/src/test/resources/com/walmartlabs/concord/runtime/v2/runner/loopSerializationError/concord.yml
class cast exception before this PR:
```
flows:
default:
- set:
items:
- name: one
- name: two
filteredItems: ${items.stream().filter(i -> i.name.equals('one')).toList()}
- call: test
loop:
items: ${filteredItems}
test:
- log: ${item}
```
> runtime-v2: better loop items serialization

- server/impl/src/main/java/com/walmartlabs/concord/server/security/ldap/ConcordDnsSrvLdapContextFactory.java
- server/impl/src/main/java/com/walmartlabs/concord/server/security/ldap/LdapContextFactoryProvider.java
Fixes a problem of starting concord-server without LDAP configuration.
Avoids side-effects in constructors.
> concord-server: fix ConcordDnsSrvLdapContextFactory initialization 

- it/server/src/test/java/com/walmartlabs/concord/it/server/ExternalImportsIT.java
- it/server/src/test/resources/com/walmartlabs/concord/it/server/externalImportSymlink/concord.txt
- server/impl/src/main/java/com/walmartlabs/concord/server/repository/RepositoryRefresher.java
- server/impl/src/main/java/com/walmartlabs/concord/server/repository/listeners/ProcessDefinitionRefreshListener.java
- server/impl/src/main/java/com/walmartlabs/concord/server/repository/listeners/RepositoryRefreshListener.java
- server/impl/src/main/java/com/walmartlabs/concord/server/repository/listeners/TriggerRefreshListener.java
When a `RepositoryRefreshListener` processes the repo directory, it typically will process `imports` which adds files to the directory. If any of the files are symlinks, then multiple listeners re-processing the same directory will try to recreate existing symlinks causing an exception.
This change gives each listener a fresh copy of the base exported repo directory so the listener can do whatever it wants without assumptions.
Alternatively, we could refactor one of two things:
1.  Change [`IOUtils.copy(...)`](https://github.com/walmartlabs/concord/blob/53db9edaa44b0a028af57046dc7f57cfd87d801c/common/src/main/java/com/walmartlabs/concord/common/IOUtils.java#L253-L268) to delete and re-create any existing symlinks it encounters. That _may_ have some side effects.
2. Refactor the repository …
> server: use clean directory for each refresh listener

- console2/src/components/organisms/ProcessAttachmentsActivity/index.tsx
- it/runtime-v2/src/test/java/com/walmartlabs/concord/it/runtime/v2/ConcordConfiguration.java
- it/runtime-v2/src/test/java/com/walmartlabs/concord/it/runtime/v2/SessionStateFilesIT.java
- it/runtime-v2/src/test/resources/com/walmartlabs/concord/it/runtime/v2/sessionFileAccess/concord.yml
- runtime/common/src/main/java/com/walmartlabs/concord/runtime/common/StateManager.java
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/DefaultPersistenceService.java
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/PersistenceService.java
- sdk/src/main/java/com/walmartlabs/concord/sdk/Constants.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/ProcessResource.java
we can save files in the process state that are only accessible with a session token.
The resource can be accessed only by using the process' session key. for example for https://github.com/walmartlabs/concord/pull/719
> runtime-v2: session state files

- console2/src/components/molecules/LogSegment/index.tsx
When a runtime-v2 process is interrupted (cancelled, timed_out, etc), the last event may not get a final status. Currently, that results in the spinner continuing to spin forever and the time running to continue accumulating. This change adds an extra check when the current segment appears active, and if the process status is something final, then it shows a yellow question mark.
*Before*
*After*
> concord-console: fix v2 log segment spinner after interrupted process

- console2/src/components/molecules/DropdownWithAddition/index.tsx
- console2/src/components/molecules/ProcessForm/index.tsx
- it/console/src/test/java/com/walmartlabs/concord/it/console/FormsIT.java
- it/console/src/test/resources/com/walmartlabs/concord/it/console/stringValues/concord.yml
Currently, if a form field is defined with a list of values, they are not displayed. However, they _are_ submitted which is pretty confusing. e.g. a form defined as
```yaml
- form: myForm
fields:
- aField: { label: "the-label", type: "string+", value: [ "first", "second" ] }
```
will not show `first` and `second` when loaded. If the user adds another option and submits the form, the submitted value is actually `[ "first", "second", "third" ]`
> concord-console: fix rendering of multiple string values in process form

- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/el/LazyExpressionEvaluator.java
- runtime/v2/runner/src/test/java/com/walmartlabs/concord/runtime/v2/runner/el/ExpressionEvaluatorTest.java
before:
```
Can't find the specified variable in 'BOOM ${abc}'. Check if it is defined in the current scope. Details: ELResolver cannot handle a null base Object with identifier 'abc'
```
after:
```
Can't find variable 'abc' in 'BOOM ${abc}'. Check if it is defined in the current scope. Details: ELResolver cannot handle a null base Object with identifier 'abc'
```
> runtime-v2: hide stacktrace for peropertyNotFound exception, better error message

- cli/src/main/java/com/walmartlabs/concord/cli/Run.java
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/Main.java
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/vm/SaveLastErrorCommand.java
- runtime/v2/runner/src/test/java/com/walmartlabs/concord/runtime/v2/runner/MainTest.java
- runtime/v2/vm/src/main/java/com/walmartlabs/concord/svm/MultiException.java
stacktraces for UserDefinedException is useless:)
> runtime-v2, cli: hide stack trace for user defined exception from parallel block

- cli/src/main/java/com/walmartlabs/concord/cli/Run.java
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/Main.java
```
concord run --no-default-cfg
```
Skips the defaultCfg.yml (i.e. the default `dependencies`).
> concord-cli: add no-default-cfg option

- CHANGELOG.md
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/StackTraceCollector.java
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/guice/DefaultRunnerModule.java
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/vm/FlowCallCommand.java
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/vm/StepCommand.java
- runtime/v2/runner/src/test/java/com/walmartlabs/concord/runtime/v2/runner/MainTest.java
- runtime/v2/runner/src/test/java/com/walmartlabs/concord/runtime/v2/runner/el/SingleFrameContext.java
- runtime/v2/runner/src/test/resources/com/walmartlabs/concord/runtime/v2/runner/stackTrace/concord.yml
- runtime/v2/runner/src/test/resources/com/walmartlabs/concord/runtime/v2/runner/stackTrace2/concord.yml
- runtime/v2/runner/src/test/resources/com/walmartlabs/concord/runtime/v2/runner/stackTrace3/concord.yml
- runtime/v2/runner/src/test/resources/com/walmartlabs/concord/runtime/v2/runner/stackTrace4/concord.yml
- runtime/v2/runner/src/test/resources/com/walmartlabs/concord/runtime/v2/runner/stackTrace5/concord.yml
- runtime/v2/runner/src/test/resources/com/walmartlabs/concord/runtime/v2/runner/stackTrace6/concord.yml
- runtime/v2/runner/src/test/resources/com/walmartlabs/concord/runtime/v2/runner/stackTrace7/concord.yml
- runtime/v2/vm/src/main/java/com/walmartlabs/concord/svm/Frame.java
- runtime/v2/vm/src/main/java/com/walmartlabs/concord/svm/FrameId.java
- runtime/v2/vm/src/main/java/com/walmartlabs/concord/svm/InMemoryState.java
- runtime/v2/vm/src/main/java/com/walmartlabs/concord/svm/StackTraceItem.java
- runtime/v2/vm/src/main/java/com/walmartlabs/concord/svm/State.java
example logs:
```
14:38:08 [ERROR] (concord.yml): Error @ line: 20, col: 7. boom
14:38:08 [ERROR] Call stack:
(concord.yml) @ line: 15, col: 7, thread: 0, flow: flowB
(concord.yml) @ line: 6, col: 7, thread: 0, flow: flowA
```
I think we can remove column number from error messages, it's a bit useless. wdyt?
> runtime-v2: log call stack on error

- docker-images/ansible/oss/debian/Dockerfile
- docker-images/base/oss/debian/Dockerfile
Fix for
```
#6 158.4 error: externally-managed-environment
#6 158.4 
#6 158.4 × This environment is externally managed
#6 158.4 ╰─> To install Python packages system-wide, try apt install
#6 158.4     python3-xyz, where xyz is the package you are trying to
#6 158.4     install.
#6 158.4     
#6 158.4     If you wish to install a non-Debian-packaged Python package,
#6 158.4     create a virtual environment using python3 -m venv path/to/venv.
#6 158.4     Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
#6 158.4     sure you have python3-full installed.
#6 158.4     
#6 158.4     If you wish to install a non-Debian packaged Python application,
#6 158.4     it may be easiest to use pipx install xyz, which will manage a
#6 158.4     virtual environment for you. Make sure you …
```
> docker-images: fix build for debian 12 based images

- console2/src/components/organisms/ProcessActivity/Toolbar.tsx
> console2: displaying the running process duration on the process toolbar

- pom.xml
Javadoc JARs are rarely needed for local development, skipping maven-javadoc-plugin in regular builds speeds things up a bit.
> project: attach javadoc jars only on release

- .github/settings.xml
- .github/workflows/build.yml
- it/server/pom.xml
- it/server/src/test/java/com/walmartlabs/concord/it/server/AbstractServerIT.java
- it/server/src/test/java/com/walmartlabs/concord/it/server/DockerAnsibleIT.java
- it/server/src/test/java/com/walmartlabs/concord/it/server/DockerIT.java
Only two test classes require our custom Docker setup (i.e. the 2375 port).
> project: allow usage of Github-hosted runners

- it/testing-server/src/main/java/com/walmartlabs/concord/it/testingserver/TestingConcordServer.java
- pom.xml
- attach source JARs only when running with `-Pconcord-release`. This shaves off some seconds from regular builds;
- expose a getter to retrive the server instance in TestingConcordServer. Useful for getting service references in tests.
> Minor changes

- it/testing-server/src/main/java/com/walmartlabs/concord/it/testingserver/TestingConcordServer.java
- pom.xml
- server/dist/src/main/java/com/walmartlabs/concord/server/dist/Main.java
- server/impl/src/main/java/com/walmartlabs/concord/server/ConcordServer.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/ProcessHeartbeatResource.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/ProcessKvResource.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/ProcessLogResourceV2.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/ProcessModule.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/ProcessResource.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/ProcessResourceV2.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/checkpoint/ProcessCheckpointResource.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/checkpoint/ProcessCheckpointV2Resource.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/event/ProcessEventResource.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/form/FormResource.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/locks/ProcessLocksResource.java
Gives the option of excluding sisu from the classpath if auto-wiring is not required.
+ more @Named removed
> concord-server: auto-wire modules in dist instead of impl

- .gitignore
- server/impl/src/main/java/com/walmartlabs/concord/server/repository/RepositoryManager.java
*I think* the new fetch-with-version is fully compatible with the old one that accepted branch or commitId separately.
> concord-server: expose fetch with version

- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/context/ResumeEventImpl.java
- runtime/v2/runner/src/test/java/com/walmartlabs/concord/runtime/v2/runner/context/ResumeEventImplTest.java
just to avoid event send error:
```
[WARN ] send [{threadId=0, phase=pre, processDefinitionId=test, fileName=concord.yaml, in={0=ResumeEventImpl{eventName='... state={baseUrl=null, apiKey=null, jobs=[...], collectOutVars=false, ignoreFailures=false}}}, line=3, column=7, description=Task: Test, correlationId=...}] -> error while sending an event to the server: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class com.walmartlabs.concord.runtime.v2.runner.context.ResumeEventImpl and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: com.walmartlabs.concord.client2.ProcessEventRequest["data"]->java.util.HashMap["in"]->java.util.HashMap["0"])
```
> runtime-v2: resume event to json serialization fix

- client2/pom.xml
- it/server/src/test/java/com/walmartlabs/concord/it/server/LdapIT.java
- server/db/src/main/resources/com/walmartlabs/concord/server/db/liquibase.xml
- server/db/src/main/resources/com/walmartlabs/concord/server/db/v2.8.0.xml
- server/db/src/main/resources/com/walmartlabs/concord/server/db/v2.9.0.xml
- server/impl/src/main/java/com/walmartlabs/concord/server/security/ldap/UserLdapGroupSynchronizer.java
- server/impl/src/main/java/com/walmartlabs/concord/server/user/UserDao.java
- server/impl/src/main/java/com/walmartlabs/concord/server/user/UserEntry.java
- server/impl/src/main/java/com/walmartlabs/concord/server/user/UserManager.java
- server/impl/src/main/java/com/walmartlabs/concord/server/user/UserResource.java
- server/impl/src/test/java/com/walmartlabs/concord/server/org/secret/PasswordCheckerTest.java
- server/plugins/pfed-sso/src/main/java/com/walmartlabs/concord/server/plugins/pfedsso/SsoRealm.java
For the times when a user is up to no good. Currently, `UserLdapGroupSynchronizer` or a UI login will automatically re-enable an LDAP user. This change sets and option that indicates a user should not be automatically re-enabled.
> concord-server: option to permanently disable a user

- server/impl/src/main/java/com/walmartlabs/concord/server/org/project/ProjectRepositoryManager.java
Currently, a repo cannot be disabled if there's something wrong with the config (auth, branch/tag, path etc).
> server: skip repository refresh when repo is disabled

- agent/src/main/java/com/walmartlabs/concord/agent/Utils.java
- agent/src/main/java/com/walmartlabs/concord/agent/cfg/AbstractRunnerConfiguration.java
- agent/src/main/java/com/walmartlabs/concord/agent/executors/JobExecutorFactory.java
- agent/src/main/java/com/walmartlabs/concord/agent/executors/runner/RunnerJobExecutor.java
- agent/src/main/resources/concord-agent.conf
Funky child processes from the runner may persist even after the runner is killed due to cancel command or `processTimeout`. This change kills each child recursively if they are still alive after the runner is killed.
> agent: kill runner child PIDs

- server/impl/src/main/java/com/walmartlabs/concord/server/boot/filters/ConcordAuthenticatingFilter.java
- server/impl/src/main/java/com/walmartlabs/concord/server/security/rememberme/ConcordRememberMeManager.java
Before:
```
> curl -i http://localhost:8001/api/v1/org
HTTP/1.1 401 Unauthorized
Server: Jetty(12.0.7)
Date: Sun, 21 Apr 2024 11:11:50 GMT
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: *
Access-Control-Allow-Headers: Authorization, Content-Type, Range, Cookie, Origin
Access-Control-Expose-Headers: cache-control,content-language,expires,last-modified,content-range,content-length,accept-ranges
Cache-Control: no-cache, no-store, must-revalidate
Pragma: no-cache
Expires: 0
Set-Cookie: rememberMe=deleteMe; Path=/; Max-Age=0; Expires=Sat, 20-Apr-2024 11:11:53 GMT; SameSite=lax
WWW-Authenticate: Basic
WWW-Authenticate: ConcordApiToken
Content-Length: 0
```
After:
```
> curl -i http://localhost:8001/api/v1/org
HTTP/1.1 401 Unauthorized
Server: Jetty(12.0.7)
Date: Sun, 21 Apr 2024 …
```
> Minor improvements to the remember me cookie logic

- server/impl/src/main/java/com/walmartlabs/concord/server/websocket/WebSocketListener.java
The actual stacktraces are not particularly useful, it is always just Jetty stuff. Let us log such errors as WARN plus the user agent.
> concord-server: tone down websocket errors

- server/impl/src/main/java/com/walmartlabs/concord/server/boot/HttpServer.java
- server/impl/src/main/java/com/walmartlabs/concord/server/boot/resteasy/ApiDescriptor.java
- server/impl/src/main/java/com/walmartlabs/concord/server/boot/resteasy/ConcordApiDescriptor.java
- server/impl/src/main/java/com/walmartlabs/concord/server/boot/resteasy/ResteasyModule.java
Allow server plugins to supply their own top-level JAX-RS endpoints in addition to the default `/api/*` and `/events/*`.
> concord-server: allow custom top-level API endpoints

- server/impl/src/main/java/com/walmartlabs/concord/server/boot/filters/ConcordAuthenticatingFilter.java
This effectively reverts #859. The change broke redirect after login when the authentication times out (e.g. OIDC login). Unfortunaly, pax4j stores the "from" parameter in the session so we need it alive when we redirect the user between the app and the auth provider.
We might want to use a separate cookie or have a way to differentiate between onLoginFailure reasons when we make a decision to invalidate the session. Get rid of pax4j too.
> concord-server: do not invalidate sessions in onFailedLogin

- server/impl/src/main/java/com/walmartlabs/concord/server/metrics/JettySessionMetricsModule.java
- server/plugins/noderoster/impl/pom.xml
- targetplatform/pom.xml
Upgrade Dropwizard Metrics and fix Jetty session metrics exporter for Jetty 12 compatibility.
> concord-server: fix Jetty metrics

- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/vm/ErrorWrapper.java
Reverts the field rename from #905 for compatibility with state serialized by previous versions.
> runtime-v2: revert renaming of a ErrorWrapper field

- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/vm/ErrorWrapper.java
- server/dist/src/main/resources/concord-server.conf
- server/impl/src/main/java/com/walmartlabs/concord/server/cfg/ProcessWaitWatchdogConfiguration.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/waits/ProcessCompletionCondition.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/waits/ProcessWaitHandler.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/waits/ProcessWaitWatchdog.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/waits/WaitProcessFinishHandler.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/waits/WaitProcessLockHandler.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/waits/WaitProcessSleepHandler.java
- server/impl/src/test/java/com/walmartlabs/concord/server/process/waits/WaitProcessFinishHandlerTest.java
the idea here is this: instead of processing each wait condition individually, we will process them in batches. As a result, instead of requesting the status for each process separately, we will request the statuses for a batch of processes at once
> server: process wait conditions in batch mode

- server/impl/src/main/java/com/walmartlabs/concord/server/process/pipelines/processors/InvalidProcessStateExceptionMapper.java
simply to avoid logging the stack trace of this exception and return a proper status code
> server: exception mapper for InvalidProcessStateException

- server/db/src/main/java/com/walmartlabs/concord/db/DataSourceUtils.java
- server/db/src/main/java/com/walmartlabs/concord/db/LiquibaseLogService.java
- server/db/src/main/java/com/walmartlabs/concord/db/LiquibaseLogger.java
- server/db/src/main/resources/META-INF/services/liquibase.logging.LogService
- server/db/src/main/resources/com/walmartlabs/concord/server/db/v0.0.1.xml
- server/db/src/main/resources/com/walmartlabs/concord/server/db/v0.18.0.xml
- server/db/src/main/resources/com/walmartlabs/concord/server/db/v0.20.0.xml
- server/db/src/main/resources/com/walmartlabs/concord/server/db/v0.21.0.xml
- server/db/src/main/resources/com/walmartlabs/concord/server/db/v0.22.0.xml
- server/db/src/main/resources/com/walmartlabs/concord/server/db/v0.64.0.xml
- server/db/src/main/resources/com/walmartlabs/concord/server/db/v0.67.0.xml
- server/db/src/main/resources/com/walmartlabs/concord/server/db/v0.84.0.xml
- server/db/src/main/resources/com/walmartlabs/concord/server/db/v0.86.0.xml
- server/db/src/main/resources/com/walmartlabs/concord/server/db/v1.49.0.xml
- server/db/src/main/resources/com/walmartlabs/concord/server/db/v1.56.0.xml
- server/db/src/main/resources/com/walmartlabs/concord/server/db/v1.83.0.xml
- server/db/src/main/resources/com/walmartlabs/concord/server/db/v1.98.1.xml
- server/db/src/main/resources/com/walmartlabs/concord/server/db/v2.8.0.xml
- server/impl/src/main/resources/logback.xml
- targetplatform/pom.xml
Latest Liquibase -- requires changes in existing change sets. At some point Liquibase started mapping `blob` to `oid` instead of `bytea`. Now we need to use `longblob` if we want the old behavior.  We also need to specify `autoIncremen=true` explicitly for any `*serial` columns we have.
> project: update Liquibase to 4.8.0

- dependency-manager/src/main/java/com/walmartlabs/concord/dependencymanager/DependencyManager.java
- dependency-manager/src/test/java/com/walmartlabs/concord/dependencymanager/DependencyManagerTest.java
- targetplatform/pom.xml
Example:
`mvn://com.walmartlabs.concord:concord-sdk:LATEST`
> dependency-manager: allow `LATEST` to pull latest version from remote repositories

- agent/src/main/java/com/walmartlabs/concord/agent/logging/LogSegmentStats.java
- agent/src/main/java/com/walmartlabs/concord/agent/logging/RemoteLogAppender.java
- agent/src/main/java/com/walmartlabs/concord/agent/logging/SegmentHeaderParser.java
- agent/src/main/java/com/walmartlabs/concord/agent/logging/SegmentedLogsConsumer.java
- agent/src/test/java/com/walmartlabs/concord/agent/executors/runner/SegmentHeaderParserTest.java
- agent/src/test/java/com/walmartlabs/concord/agent/executors/runner/SegmentedLogsConsumerTest.java
- console2/src/api/process/log/index.ts
- console2/src/components/molecules/LogSegment/index.tsx
- runtime/common/src/main/java/com/walmartlabs/concord/runtime/common/logger/LogSegmentDeserializer.java
- runtime/common/src/main/java/com/walmartlabs/concord/runtime/common/logger/LogSegmentHeader.java
- runtime/common/src/main/java/com/walmartlabs/concord/runtime/common/logger/LogSegmentSerializer.java
- runtime/common/src/main/java/com/walmartlabs/concord/runtime/common/logger/LogSegmentStatus.java
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/logging/ConcordLogEncoder.java
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/logging/LogLevelFilter.java
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/logging/SegmentStatusMarker.java
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/logging/SegmentedLogger.java
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/logging/SimpleLogger.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/LogSegment.java
before this, the segment had two statuses: RUNNING and OK.
now the segment will have the correct status in case of an error.
the SUSPENDED status is not used yet, I just reserved id=2 for it))
> runtime-v2: use log segment statuses

- .github/settings.xml
- .github/workflows/build.yml
- it/compat/src/test/java/com/walmartlabs/concord/it/compat/OldAgentIT.java
- it/runtime-v2/pom.xml
- it/server/pom.xml
- it/server/src/test/java/com/walmartlabs/concord/it/server/AbstractServerIT.java
- targetplatform/pom.xml
`runs-on: [ linux, ARM64 ]` is currently handled by a RPi5 in my basement. :-)
Next step will be moving the release process to GHA flows.
> project: build both x86 and aarch64 versions

- cli/src/main/java/com/walmartlabs/concord/cli/Run.java
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/Main.java
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/vm/JoinCommand.java
- runtime/v2/runner/src/test/java/com/walmartlabs/concord/runtime/v2/runner/MainTest.java
- runtime/v2/runner/src/test/resources/com/walmartlabs/concord/runtime/v2/runner/parallelWithError/concord.yml
- runtime/v2/vm/src/main/java/com/walmartlabs/concord/svm/MultiException.java
- runtime/v2/vm/src/main/java/com/walmartlabs/concord/svm/ParallelExecutionException.java
Cut off the bottom of the trace, it's not particularly useful anyway.
Should make parallel execution errors sligtly more readable.
Before:
```
2024-06-18T14:18:16.989+0000 [INFO ] will fail with error
2024-06-18T14:18:16.989+0000 [INFO ] will fail with error
2024-06-18T14:18:16.995+0000 [ERROR] (concord.yml): Error @ line: 3, col: 7. Error during execution of 'faultyTask' task: boom!
2024-06-18T14:18:16.995+0000 [ERROR] (concord.yml): Error @ line: 3, col: 7. Error during execution of 'faultyTask' task: boom!
2024-06-18T14:18:17.965+0000 [ERROR] (concord.yml): Error @ line: 3, col: 7. Errors: 
java.lang.RuntimeException: Error during execution of 'faultyTask' task: boom!
at com.walmartlabs.concord.runtime.v2.runner.vm.StepCommand.lambda$executeWithContext$1(StepCommand.java:100)
at …
```
> runtime-v2: limit depth of MultiException stack trace

- server/impl/src/main/java/com/walmartlabs/concord/server/websocket/WebSocketChannel.java
- server/impl/src/main/java/com/walmartlabs/concord/server/websocket/WebSocketChannelManager.java
Allow server plugins to access currently connected websockets.
> concord-server: expose websocket channels

- it/runtime-v1/src/test/java/com/walmartlabs/concord/it/runtime/v1/ProcessIT.java
- it/runtime-v1/src/test/resources/com/walmartlabs/concord/it/runtime/v1/processWithChildSuspend/concord.yml
- it/runtime-v1/src/test/resources/com/walmartlabs/concord/it/runtime/v1/processWithChildSuspend/myPayload/concord.yml
- it/runtime-v1/src/test/resources/com/walmartlabs/concord/it/runtime/v1/processWithChildSuspendWithoutOut/concord.yml
- it/runtime-v1/src/test/resources/com/walmartlabs/concord/it/runtime/v1/processWithChildSuspendWithoutOut/myPayload/concord.yml
- it/runtime-v1/src/test/resources/com/walmartlabs/concord/it/runtime/v1/processWithChildrenSuspend/concord.yml
- targetplatform/pom.xml
re: https://github.com/concord-workflow/bpm/pull/19
> runtime-v1: update bpm library to fix saving variables before suspend

- it/runtime-v2/src/test/java/com/walmartlabs/concord/it/runtime/v2/ProcessIT.java
- it/runtime-v2/src/test/resources/com/walmartlabs/concord/it/runtime/v2/processMetadataSend/concord.yml
- it/runtime-v2/src/test/resources/com/walmartlabs/concord/it/runtime/v2/processMetadataSend/debug_logback.xml
- runtime/v1/impl/src/main/java/com/walmartlabs/concord/runner/engine/EngineFactory.java
- runtime/v2/model/src/main/java/com/walmartlabs/concord/runtime/v2/model/EventConfiguration.java
- runtime/v2/model/src/main/java/com/walmartlabs/concord/runtime/v2/parser/ConfigurationGrammar.java
- runtime/v2/model/src/test/java/com/walmartlabs/concord/project/runtime/v2/parser/YamlErrorParserTest.java
- runtime/v2/model/src/test/resources/serializer/processDefinition.yml
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/MetadataProcessor.java
Similar to https://github.com/walmartlabs/concord/pull/938 but for runtime-v2.
> runtime-v2: option to update meta only on termination or suspend

- cli/src/main/java/com/walmartlabs/concord/cli/Lint.java
- console2/src/api/process/index.ts
- console2/src/components/organisms/ProcessActivity/index.tsx
- policy-engine/src/test/java/com/walmartlabs/concord/policyengine/DependencyRewritePolicyTest.java
- runtime/loader/src/main/java/com/walmartlabs/concord/process/loader/ProjectLoader.java
- runtime/loader/src/main/java/com/walmartlabs/concord/process/loader/UnsupportedRuntimeTypeException.java
- server/dist/src/main/resources/concord-server.conf
- server/impl/src/main/java/com/walmartlabs/concord/server/cfg/ProcessConfiguration.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/ProjectLoaderConfigurationProvider.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/pipelines/processors/ProcessDefinitionProcessor.java
Add `process.extraRuntimes` configuration parameter to concord-server.conf. Only the default v1, v2 and `extraRuntimes` will be allowed as `configuration.runtime` values.
> what's the result if someone misspells the runtime? e.g. runtime: runtime-v@
The process will transition NEW -> FAILED with the exception printed in the "system" log segment.
> concord-server: allow non-standard runtimes

- server/impl/src/main/java/com/walmartlabs/concord/server/process/ProcessModule.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/ProjectLoaderConfigurationProvider.java
- server/plugins/oidc/src/main/java/com/walmartlabs/concord/server/plugins/oidc/OidcLogoutFilter.java
plus a small fix for a missing binding for ProjectLoaderConfigurationProvider when using concord-server modules without autowiring
> oidc: support "from" when logging out

- cli/src/main/java/com/walmartlabs/concord/cli/runner/FlowStepLogger.java
before:
```
Starting...
>>> 'Task: log' @ concord.yml:3     # <---- unexpected log line
>>> 'Task: log' @ concord.yml:3
in: {msg=Hello!}
14:58:13.112 [main] Hello!
...
```
after:
```
Starting...
>>> 'Task: log' @ concord.yml:3
in: {msg=Hello!}
14:58:13.112 [main] Hello!
...
```
concord.yaml:
```
flows:
default:
- log: "Hello!"
```
> cli: fix duplicate step logs

- docker-images/ansible/galaxy_requirements.yml
Newer versions of `requests` python module are [not compatible](https://github.com/ansible-collections/community.docker/issues/868) with the pinned older version of `community.docker`.
> docker-images: update ansible galaxy community.docker version

- docker-images/base/oss/debian/Dockerfile
Git 2.35+ introduced `safe.directory` feature, i.e. fail if .git belongs to a user different that the current.
It is an issue for our integration tests where we share .git between the host and the containers.
This change effectively disables the `safe.directory` feature by configuring `safe.directory=*` at user-level in the base Docker image.
> docker: configure safe.directory for git 2.35+

- console2/src/components/molecules/ProcessToolbar/index.tsx
- console2/src/components/organisms/ProcessLogActivityV2/index.tsx
> console2: log segments status filter

- console2/src/components/pages/UnauthorizedPage/index.tsx
- server/dist/src/main/resources/concord-server.conf
- server/plugins/oidc/README.md
- server/plugins/oidc/src/main/java/com/walmartlabs/concord/server/plugins/oidc/OidcAuthFilter.java
- server/plugins/oidc/src/main/java/com/walmartlabs/concord/server/plugins/oidc/OidcCallbackFilter.java
- server/plugins/oidc/src/main/java/com/walmartlabs/concord/server/plugins/oidc/PluginConfiguration.java
Handle `error` responses in OIDC callback code. Redirect to the unauthorized page and show the error:
> oidc: improve error handling

- agent-operator/src/main/java/com/walmartlabs/concord/agentoperator/processqueue/ProcessQueueClient.java
Save cookies received from concord-server, including the session cookie. Reduces the number of authorization hits when operators poll for work.
> agent-operator: save cookies received from API

- server/impl/src/main/java/com/walmartlabs/concord/server/process/ProcessResource.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/waits/ProcessWaitWatchdog.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/waits/WaitConditionUpdater.java
[ConcurrentProcessFilter](https://github.com/walmartlabs/concord/blob/brig-patch-1/server/impl/src/main/java/com/walmartlabs/concord/server/process/queue/dispatcher/ConcurrentProcessFilter.java#L43) adds an `exclusive` wait condition to the process, 
transitions the process from `ENQUEUED -> WAITING`, and marks it with `PROCESS_WAIT_CONDITIONS.IS_WAITING=true`.
[ProcessWaitWatchdog](https://github.com/walmartlabs/concord/blob/brig-patch-1/server/impl/src/main/java/com/walmartlabs/concord/server/process/waits/ProcessWaitWatchdog.java#L221) processes the `exclusive` wait condition first, transitions the process from `WAITING -> ENQUEUED`, 
and marks it with `PROCESS_WAIT_CONDITIONS.IS_WAITING=false`.
This is a symmetric action. As a result, the process will return to the state it was in.
If …
> server: fix updateWaitConditions when wait condition without processes

- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/DefaultEventReportingService.java
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/EventReportingService.java
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/guice/DefaultRunnerModule.java
and `EventReportingService` does not implement the `ExecutionListener` interface, as it's not supposed to :)
> runtime-v2: flush events on process error

- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/vm/JoinCommand.java
The current "good enough™" value is not particularly good for short forks. Tighten the loop by reducing the delay from 1 second to 100 milliseconds.
Test flow:
```yaml
flows:
default:
- call: foo
loop:
items: ["A", "B", "C"]
parallelism: 2
mode: parallel
foo:
- log: "Hi, ${item}!"
- "${sleep.ms(1000)}"
- log: "Bye, ${item}!"
```
Before:
After:
> runtime-v2: use shorter delay while polling status of threads

- it/server/src/test/java/com/walmartlabs/concord/it/server/StandardAuthenticationHandlersIT.java
- it/server/src/test/resources/com/walmartlabs/concord/it/server/sessionTokenAsUsername/concord.yml
- server/impl/src/main/java/com/walmartlabs/concord/server/security/BasicAuthenticationHandler.java
- server/impl/src/main/java/com/walmartlabs/concord/server/security/SessionTokenAuthenticationHandler.java
Bring back the handling of the "session tokens as usernames" special case.
> concord-server: fix session token handling

- it/runtime-v2/src/test/java/com/walmartlabs/concord/it/runtime/v2/ConcordConfiguration.java
- it/runtime-v2/src/test/java/com/walmartlabs/concord/it/runtime/v2/CryptoIT.java
- it/runtime-v2/src/test/java/com/walmartlabs/concord/it/runtime/v2/FormIT.java
- it/runtime-v2/src/test/java/com/walmartlabs/concord/it/runtime/v2/ImportsIT.java
- it/runtime-v2/src/test/java/com/walmartlabs/concord/it/runtime/v2/JsonStoreIT.java
- it/runtime-v2/src/test/java/com/walmartlabs/concord/it/runtime/v2/KvTaskIT.java
- it/runtime-v2/src/test/java/com/walmartlabs/concord/it/runtime/v2/NodeRosterIT.java
- it/runtime-v2/src/test/java/com/walmartlabs/concord/it/runtime/v2/SmtpIT.java
- it/server/src/test/resources/agent.conf
Use shorter polling intervals on the agent during ITs.
Last few runs, "Build and test with Maven" time:
| Platform      | Before | After |
|--------------|---------|-------|
| jdk17        | 1h 9m 14s<br>1h 11m 23s<br>1h 10m 22s | 1h 3m 59s<br>1h 4m 46s<br>1h 4m 57s |
| jdk17-aarch64| 1h 36m 24s<br>1h 30m 7s<br>1h 28m 25s | 1h 22m 6s<br>1h 22m 6s<br>1h 22m 15s |
> it: tighten up polling intervals

- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/DefaultEventReportingService.java
- runtime/v2/runner/src/test/java/com/walmartlabs/concord/runtime/v2/runner/EventReportingServiceTest.java
- server/impl/src/main/java/com/walmartlabs/concord/server/ConcordObjectMapper.java
and save invalid process events as process attachments
> server: cleanup control chars from jsonb

- server/impl/src/main/java/com/walmartlabs/concord/server/user/UserResourceV2.java
restricts UserResourceV2 to only allow a user to look up their own information or requires admin permissions.
> server: add authorization check to User lookup endpoint in API

- plugins/tasks/ansible/pom.xml
- plugins/tasks/asserts/pom.xml
- plugins/tasks/concord/pom.xml
- plugins/tasks/crypto/pom.xml
- plugins/tasks/docker/pom.xml
- plugins/tasks/dynamic-tasks/pom.xml
- plugins/tasks/example/pom.xml
- plugins/tasks/files/pom.xml
- plugins/tasks/http/pom.xml
- plugins/tasks/kv/pom.xml
- plugins/tasks/locale/pom.xml
- plugins/tasks/lock/pom.xml
- plugins/tasks/log/pom.xml
- plugins/tasks/misc/pom.xml
- plugins/tasks/mock/pom.xml
- plugins/tasks/noderoster/pom.xml
- plugins/tasks/resource/pom.xml
- plugins/tasks/slack/pom.xml
- plugins/tasks/sleep/pom.xml
- plugins/tasks/smtp/pom.xml
- plugins/tasks/throw/pom.xml
- plugins/tasks/variables/pom.xml
- pom.xml
Some plugins depend on the runner, so we can't verify it because it creates a circular dependency: 
task A -> concord-maven-plugin -> runner -> task A
so we just create an sisu-index for them.
> project: use concord-maven-plugin

- console2/src/components/organisms/Login2/index.tsx
This way adding `from=/destination` will redirect users to `http://localhost:8001/#/destination` (note the use of the hash route) while `redirectTo=/destination` will send users to `http://localhost:8001/destination`. Useful for 3rd-party integrations and non-console2 endpoints.
Also fixes the 'from' behavior -- `from` didn't work for me at all (at least in dev mode).
> concord-console2: add support for redirectTo to the login page

- it/runtime-v2/src/test/java/com/walmartlabs/concord/it/runtime/v2/ProcessIT.java
- it/runtime-v2/src/test/resources/com/walmartlabs/concord/it/runtime/v2/throwWithPayload/concord.yml
- plugins/tasks/throw/src/main/java/com/walmartlabs/concord/plugins/throwex/ThrowExceptionTaskV2.java
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/vm/SaveLastErrorCommand.java
- runtime/v2/sdk/src/main/java/com/walmartlabs/concord/runtime/v2/sdk/UserDefinedException.java
```
- task: "throw"
in:
exception: "message"
payload:
key: "value"
```
Everything seems like it shouldn't break, but it might be useful :)
> runtime-v2: allow throw payload with exception

- agent/src/main/java/com/walmartlabs/concord/agent/cfg/AgentConfiguration.java
- agent/src/main/java/com/walmartlabs/concord/agent/executors/JobExecutorFactory.java
- agent/src/main/java/com/walmartlabs/concord/agent/executors/runner/RunnerJob.java
- agent/src/main/java/com/walmartlabs/concord/agent/executors/runner/RunnerJobExecutor.java
- agent/src/main/resources/concord-agent.conf
- it/runtime-v2/src/test/resources/com/walmartlabs/concord/it/runtime/v2/processMetadataSend/debug_logback.xml
- runtime/common/src/main/java/com/walmartlabs/concord/runtime/common/cfg/LoggingConfiguration.java
- runtime/v2/runner-test/src/main/java/com/walmartlabs/concord/runtime/v2/runner/TestRuntimeV2.java
- runtime/v2/runner-test/src/test/java/com/walmartlabs/concord/runtime/v2/runner/MainTest.java
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/InjectorFactory.java
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/logging/CustomLayout.java
- runtime/v2/runner/src/main/resources/logback.xml
Add workDirMasking option to concord-agent.conf to enable masking of workDir values in logs. The actual path (which is usually some noise like `/tmp/concord-agent/xxxxxyyyyyzzzzz`) is replaced with a `$WORK_DIR` literal.
> runtime-v2: mask workDir value in logs by default

- agent-operator/src/main/java/com/walmartlabs/concord/agentoperator/Operator.java
- agent-operator/src/main/java/com/walmartlabs/concord/agentoperator/scheduler/Scheduler.java
Avoid "resource too old" issue when using "naked" Watchers.
As recommended here https://stackoverflow.com/a/61437982
> concord-agent-operator: use informers API

- .github/workflows/build.yml
Checking github.repository_owner is not enough. IIUC, it always points at the repository in the context of which the current GHA check is running.
Let's try `github.event.pull_request.head.repo.full_name` instead.
> project: do not log into Docker in check runs started in forks (another attempt)

- plugins/tasks/misc/src/main/java/com/walmartlabs/concord/plugins/misc/Base64TaskV2.java
- plugins/tasks/misc/src/main/java/com/walmartlabs/concord/plugins/misc/DateTimeTaskV2.java
runtime-v2 only:
- add `base64.encode` and `decode` methods
- add `datetime.currentISO()` shortcut
> misc-tasks: add base64 task, shortcut for current ISO timestamp

- server/impl/src/main/java/com/walmartlabs/concord/server/console/CustomFormService.java
- server/impl/src/main/java/com/walmartlabs/concord/server/console/CustomFormServiceV1.java
- server/impl/src/main/java/com/walmartlabs/concord/server/console/CustomFormServiceV2.java
- server/impl/src/main/java/com/walmartlabs/concord/server/console/ProcessCardResource.java
- server/impl/src/main/java/com/walmartlabs/concord/server/org/secret/GetDataRequest.java
- server/impl/src/main/java/com/walmartlabs/concord/server/org/secret/SecretResource.java
- server/impl/src/main/java/com/walmartlabs/concord/server/org/secret/SecretResourceV2.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/ProcessResource.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/checkpoint/ProcessCheckpointResource.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/form/FormResource.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/form/FormResourceV1.java
Remove temporary files as soon as possible. Do not rely on finalizers.
> concord-server: close MultipartInput explicitly

- .gitignore
- docker-images/agent/oss/debian/Dockerfile
- docker-images/base/oss/debian/Dockerfile
- docker-images/server/oss/Dockerfile
- pom.xml
- runtime/v1/impl/pom.xml
And other minor changes.
The updated maven-enforcer-plugin complained about runtime-v1 pulling in Guava 25.x while Jackson was pulling in the common version (33.x). Now runtime-v1 will be using the common Guava version as well.
> project: update Maven plugin versions

- plugins/tasks/http/pom.xml
- plugins/tasks/http/src/main/java/com/walmartlabs/concord/plugins/http/HttpTask.java
- plugins/tasks/http/src/test/java/com/walmartlabs/concord/plugins/http/HttpTaskTest.java
- plugins/tasks/http/src/test/java/com/walmartlabs/concord/plugins/http/HttpTaskV2Test.java
- plugins/tasks/http/src/test/java/com/walmartlabs/concord/plugins/http/SimpleHttpClientTest.java
- plugins/tasks/http/src/test/java/com/walmartlabs/concord/plugins/http/WiremockTest.java
- plugins/tasks/http/src/test/resources/logback.xml
- targetplatform/pom.xml
* No main code changes (except for method visibility `private` -> package private)
* Refactor to test only the intended bits (i.e. don't run through task when test is only for client or config)
* Compatibility for [parallel tests](https://github.com/walmartlabs/concord/pull/1117)
> http-tasks: refactor tests, support for parallel tests

- agent-operator/pom.xml
- targetplatform/pom.xml
[bcprov-ext-jdk18on](https://mvnrepository.com/artifact/org.bouncycastle/bcprov-ext-jdk18on) moved to [bcprov-jdk18on](https://mvnrepository.com/artifact/org.bouncycastle/bcprov-jdk18on)
> project: update bouncycastle dependency versions

- it/server/src/test/java/com/walmartlabs/concord/it/server/RequirementsIT.java
- it/server/src/test/resources/com/walmartlabs/concord/it/server/processRequirements/concord.yml
- server/impl/pom.xml
- server/impl/src/main/java/com/walmartlabs/concord/server/process/queue/dispatcher/Dispatcher.java
- server/impl/src/test/java/com/walmartlabs/concord/server/process/queue/dispatcher/DispatcherTest.java
A bad regex in a process request's agent requirements can completely halt the queue dispatcher since one exception causes the entire run to fail.
This change handles an exception per matching attempt so the dispatcher can carry on if any requests are catastrophically invalid. The process(es) with non-processable requirements are `FAILED`.
> server: handle invalid regex in dispatcher requirements

- targetplatform/pom.xml
The 10.x branch has some compatibility issues with Shiro's OIDC.
> project: downgrade nimbus-jose-jwt

- agent-operator/README.md
- agent-operator/deploy/crds/cr.yml
- agent-operator/deploy/crds/example.agentpool.yml
- agent-operator/src/main/java/com/walmartlabs/concord/agentoperator/Operator.java
- agent-operator/src/main/java/com/walmartlabs/concord/agentoperator/scheduler/DefaultAutoScaler.java
- agent-operator/src/main/resources/prestop-hook.sh
- agent/src/main/java/com/walmartlabs/concord/agent/Agent.java
Fix handling of processes with empty `requirements` when using empty `queueSelector` in agent pools.
Replace wget usage in prestop-hook.sh with a Bash-only version.
Explicitly handle SIGTERM in the agent for faster termination in k8s environment.
> concord-agent, concord-agent-operator: better shutdown hook, handle SIGTERM

- targetplatform/pom.xml
Fixes compatibility with Concord 2.25.0+ wrt to the removed `acceptsRawPayload` property.
> project: update testcontainers-concord version

- it/runtime-v2/pom.xml
- runtime/v2/runner-test/pom.xml
- runtime/v2/runner/pom.xml
- runtime/v2/runner/src/test/java/com/walmartlabs/concord/runtime/v2/runner/context/ResumeEventImplTest.java
- runtime/v2/runner/src/test/java/com/walmartlabs/concord/runtime/v2/runner/tasks/TaskCallInterceptorTest.java
Fix test discovery (and test skipping)
```
10:04:02 [INFO ] [INFO] --- maven-surefire-plugin:3.0.0-M5:test (default-test) @ concord-runner-v2 ---
10:04:02 [INFO ] [INFO] 
10:04:02 [INFO ] [INFO] -------------------------------------------------------
10:04:02 [INFO ] [INFO]  T E S T S
10:04:02 [INFO ] [INFO] -------------------------------------------------------
10:04:03 [ERROR] May 02, 2025 3:04:03 PM org.junit.platform.launcher.core.DefaultLauncher handleThrowable
10:04:03 [ERROR] WARNING: TestEngine with ID 'junit-jupiter' failed to discover tests
10:04:03 [ERROR] java.lang.NoClassDefFoundError: org/junit/platform/engine/support/discovery/SelectorResolver
```
> project: fix concord-runner-v2 test discovery

- cli/src/main/java/com/walmartlabs/concord/cli/Lint.java
- runtime/loader/src/main/java/com/walmartlabs/concord/process/loader/ConcordProjectLoader.java
- runtime/loader/src/main/java/com/walmartlabs/concord/process/loader/ProjectLoader.java
- server/impl/src/main/java/com/walmartlabs/concord/server/org/triggers/TriggerResource.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/ConcordProjectLoaderConfigurationProvider.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/ProcessModule.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/pipelines/processors/ProcessDefinitionProcessor.java
- server/impl/src/main/java/com/walmartlabs/concord/server/repository/RepositoryManager.java
Extract ProjectLoader interface out of the current impl + remove `@Named`.
Before this change, RepositoryManager had a hard dependency on a specific implementation of ProjectLoader and was hard coded to treat any repository as a "project" (i.e. containing files for v1, v2 or other supported runtimes).
The change allows simpler testing and re-use in other projects.
> concord-server: use ProjectLoader interface, bind explicitly

- server/impl/src/main/java/com/walmartlabs/concord/server/events/TriggerProcessExecutor.java
- server/impl/src/main/java/com/walmartlabs/concord/server/org/triggers/TriggerScheduler.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/ProcessSecurityContext.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/queue/ProcessQueueWatchdog.java
- server/impl/src/main/java/com/walmartlabs/concord/server/security/SecurityModule.java
- server/impl/src/main/java/com/walmartlabs/concord/server/security/UserSecurityContext.java
Before this change ProcessSecurityContext was responsible for both runAs (generic "run as this user ID" method) and runAsCurrentUser (i.e. "run as the current user of the specified process ID").
This change separates those concerns. The new UserSecurityContext can be used in situations where there is no notion of processes at all (i.e. testing or re-use in other projects).
> concord-server: split ProcessSecurityContext

- cli/pom.xml
- cli/src/main/java/com/walmartlabs/concord/cli/Lint.java
- cli/src/main/java/com/walmartlabs/concord/cli/Main.java
- cli/src/main/java/com/walmartlabs/concord/cli/Run.java
- cli/src/main/java/com/walmartlabs/concord/cli/runner/FlowStepLogger.java
- cli/src/main/java/com/walmartlabs/concord/cli/runner/TaskParamsLogger.java
- cli/src/main/java/com/walmartlabs/concord/cli/runner/VaultProvider.java
- cli/src/main/resources/logback.xml
- cli/src/test/java/com/walmartlabs/concord/cli/AbstractTest.java
- cli/src/test/resources/logback-test.xml
- targetplatform/pom.xml
Colorful output for concord-cli.
Before:
After:
Without verbose mode:
Also changes the `lint` action to use Jansi instead of Picocli's ANSI support for consistency.
> concord-cli: use jansi, add colors to run output

- pom.xml
To get rid of the Maven warning about the annotation processing not being explicitly enabled.
> project: enable full annotation processing

- repository/src/main/java/com/walmartlabs/concord/repository/GitClient.java
- repository/src/main/java/com/walmartlabs/concord/repository/GitClientConfiguration.java
- server/impl/src/main/java/com/walmartlabs/concord/server/cfg/GitConfiguration.java
- server/impl/src/main/java/com/walmartlabs/concord/server/repository/RepositoryManager.java
Adds a field to the git client configuration which serves as a whitelist for allowed hosts to use the default git credentials with (to prevent leaking of said credentials.) WIP Label bc I'm not confident that I've covered all bases and would appreciate more eyes on it :)
> Default Git Credentials Hostname Whitelist

- server/db/pom.xml
- server/db/src/main/resources/META-INF/services/liquibase.lockservice.LockService
- targetplatform/pom.xml
Use `pg_try_advisory_lock` instead of a lock table by adding [liquibase-sessionlock](https://github.com/blagerweij/liquibase-sessionlock).
In environment like K8s it is not uncommon to have the server pod killed before it finishes the database migration (took too long, redeployed too fast, etc) -- which may leave lock records in Liquibase lock tables and cause subsequent restarts to fail.
> concord-server-db: use session locks in Liquibase

- it/server/src/test/resources/agent.conf
- it/server/src/test/resources/server.conf
In my local tests it shaves ~6 minutes off it/server run time. It might not be the case for (weaker) GHA runners.
> concord-server-it: reduce agent and server poll delays to speed up tests

- it/console/src/test/resources/agent.conf
- it/console/src/test/resources/server.conf
- it/runtime-v1/src/test/java/com/walmartlabs/concord/it/runtime/v1/ConcordConfiguration.java
- it/runtime-v2/src/test/java/com/walmartlabs/concord/it/runtime/v2/ConcordConfiguration.java
Continuation of #1159, now applied to it/runtime-v1, it/runtime-v2 and console ITs.
> concord-runtime-v1/v2-it: reduce agent and server poll rates to speed up tests

- cli/pom.xml
- pom.xml
The Central Portal doesn't like .jar files that are not exactly jars -- e.g. prepended with a shell script to make the JAR "really executable".
> concord-cli: produce an executable binary again

- plugins/tasks/http/src/main/java/com/walmartlabs/concord/plugins/http/HttpTaskUtils.java
The HTTP task now includes `Number` values (e.g., integers) when building multipart/form-data requests. Unsupported types are skipped with a warning...
This change might break something if integer variables were previously ignored and are now being sent. But I hope it won't be a big issue :)
> http-task: support sending int values in multipart requests

- server/queue-client/src/main/java/com/walmartlabs/concord/server/queueclient/message/ProcessResponse.java
Sometimes `ProcessResponse` messages are [logged in full](https://github.com/walmartlabs/concord/blob/19119528f197357aa4d4982ec2dac16c6cf8a5ae/server/impl/src/main/java/com/walmartlabs/concord/server/message/MessageChannelManager.java#L85), including the session token.
> concord-server: do not log session token

- server/dist/src/main/resources/concord-server.conf
- server/impl/src/main/java/com/walmartlabs/concord/server/cfg/ConfigurationModule.java
- server/impl/src/main/java/com/walmartlabs/concord/server/cfg/TemplatesConfiguration.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/pipelines/processors/TemplateScriptProcessor.java
- server/impl/src/test/java/com/walmartlabs/concord/server/process/pipelines/processors/TemplateScriptProcessTest.java
Adds a kill switch for any template script execution on the server. Needs some further consideration for sandboxing the scripts when enabled. Newer graalvm SDKs may offer some extra options, but SecurityManager isn't really feasible (and is deprecated).
> concord-server: config option to disable template script processing

- console2/src/components/organisms/TaskCallDetails/index.tsx
> concord-console2: sort variables in task call details

- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/checkpoints/DefaultCheckpointService.java
- runtime/v2/runner/src/test/java/com/walmartlabs/concord/runtime/v2/runner/checkpoints/DefaultCheckpointServiceTest.java
Trying to debug issues like this one https://github.com/walmartlabs/concord/actions/runs/16353509366/job/46206028838?pr=1191#step:6:15022
```
Caused by: java.io.OptionalDataException
at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1756)
[cut]
at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:467)
at com.walmartlabs.concord.runtime.v2.runner.checkpoints.DefaultCheckpointService.clone(DefaultCheckpointService.java:118)
```
> runtime-v2: additional error logging when cloning state fails

- it/runtime-v2/src/test/java/com/walmartlabs/concord/it/runtime/v2/ConcordTaskIT.java
- it/runtime-v2/src/test/resources/com/walmartlabs/concord/it/runtime/v2/concord/createApiKey/concord.yml
- plugins/tasks/concord/src/main/java/com/walmartlabs/concord/client/ConcordTaskCommon.java
- plugins/tasks/concord/src/main/java/com/walmartlabs/concord/client/ConcordTaskParams.java
E.g.
```yaml
- task: concord
in:
action: createApiKey
baseUrl: http://localhost:8001
apiKey: foobar # API key for calling the baseUrl API, not the value of the key
userId: 230c5c9c-d9a7-11e6-bcfd-bb681c07b26c
name: foo
ignoreExisting: true
```
> concord-tasks: add createApiKey action

- pom.xml
Enable trimHeaderLine in license-maven-plugin to avoid trailing white space in the license header.
Most formatters (including Checkstyle) do not like trailing white space and it was a constant source of random superfluous diffs in Git.
Not going to reformat the existing files though but all new files should have their license headers "fixed".
> project: enable trimHeaderLine in license-maven-plugin

- cli/src/main/java/com/walmartlabs/concord/cli/AbortException.java
- cli/src/main/java/com/walmartlabs/concord/cli/runner/secrets/RemoteSecretsProvider.java
Make testing simpler by not using System.exit anywhere except the entrypoints.
> concord-cli: do not call System.exit in RemoteSecretsProvider

- plugins/tasks/resource/pom.xml
- plugins/tasks/resource/src/main/java/com/walmartlabs/concord/plugins/resource/ResourceTaskCommon.java
Using the IOUtils assertInPath to reduce duplicate code.
> resource-task: Use the shared IOUtils assertInPath method for resource lookups

- server/plugins/oidc/pom.xml
- server/plugins/oidc/src/main/java/com/walmartlabs/concord/server/plugins/oidc/OidcAuthFilter.java
- server/plugins/oidc/src/main/java/com/walmartlabs/concord/server/plugins/oidc/OidcAuthenticationHandler.java
- server/plugins/oidc/src/main/java/com/walmartlabs/concord/server/plugins/oidc/OidcCallbackFilter.java
- server/plugins/oidc/src/main/java/com/walmartlabs/concord/server/plugins/oidc/OidcFilterChainConfigurator.java
- server/plugins/oidc/src/main/java/com/walmartlabs/concord/server/plugins/oidc/OidcLogoutFilter.java
- server/plugins/oidc/src/main/java/com/walmartlabs/concord/server/plugins/oidc/OidcPluginModule.java
- server/plugins/oidc/src/main/java/com/walmartlabs/concord/server/plugins/oidc/OidcRealm.java
- server/plugins/oidc/src/main/java/com/walmartlabs/concord/server/plugins/oidc/OidcService.java
- server/plugins/oidc/src/main/java/com/walmartlabs/concord/server/plugins/oidc/OidcToken.java
- server/plugins/oidc/src/main/java/com/walmartlabs/concord/server/plugins/oidc/PluginConfiguration.java
- server/plugins/oidc/src/main/java/com/walmartlabs/concord/server/plugins/oidc/UserProfile.java
- targetplatform/pom.xml
Remove pac4j-oidc and implement the authorization flow manually.
Note, this change can break SUSPENDED processes with OIDC initiators due to the way concord-server serializes security principals.
> oidc: remove pac4j dependency

- server/impl/src/main/java/com/walmartlabs/concord/server/security/UserPrincipal.java
- server/impl/src/main/java/com/walmartlabs/concord/server/security/apikey/ApiKeyRealm.java
UserPrincipal#user should not be null. Instead, we should skip `UserPrincipal` entirely when authenticating via an API key without the user.
> concord-server: do not create UserPrincipal for API keys without userId

- it/runtime-v2/src/test/java/com/walmartlabs/concord/it/runtime/v2/ConcordConfiguration.java
- it/runtime-v2/src/test/java/com/walmartlabs/concord/it/runtime/v2/ProcessIT.java
- it/runtime-v2/src/test/resources/com/walmartlabs/concord/it/runtime/v2/usernameSignature/concord.yml
- server/impl/src/main/java/com/walmartlabs/concord/server/process/pipelines/processors/UserInfoProcessor.java
- server/impl/src/main/java/com/walmartlabs/concord/server/user/UserInfoProvider.java
> server: fix usernameSignature generation
