walmartlabs/concord

- server/impl/src/main/java/com/walmartlabs/concord/server/org/secret/SecretDao.java
- server/impl/src/main/java/com/walmartlabs/concord/server/org/secret/SecretManager.java
- server/impl/src/test/java/com/walmartlabs/concord/server/security/secret/SecretDaoTest.java
Add an option to SecretManager (and it's DAO) to do an upsert instead of an insert
Closes #30
How can I test this? Is there a script to set up a local environment?
> Add an option to SecretManager (and it's DAO) to do an upsert

- cli/src/main/java/com/walmartlabs/concord/cli/runner/CliLockService.java
- cli/src/main/java/com/walmartlabs/concord/cli/runner/CliServicesModule.java
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/DefaultLockService.java
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/context/ContextImpl.java
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/context/DefaultContextFactory.java
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/guice/DefaultRunnerModule.java
- runtime/v2/runner/src/test/java/com/walmartlabs/concord/runtime/v2/runner/MainTest.java
- runtime/v2/runner/src/test/java/com/walmartlabs/concord/runtime/v2/runner/el/DummyContext.java
- runtime/v2/sdk/src/main/java/com/walmartlabs/concord/runtime/v2/sdk/Context.java
- runtime/v2/sdk/src/main/java/com/walmartlabs/concord/runtime/v2/sdk/LockService.java
Runtime v2 implementation of `LockService`.
Pretty much a carbon copy of the v1 version + `Context#lockService()` boilerplate.
cc @brig
> runtime-v2: LockService implementation

- docker-images/ansible/oss/Dockerfile
- docker-images/base/oss/Dockerfile
Pin Pip's version to fix the images.
cc @brig
> docker: pin pip versions

- server/queue-client/src/main/java/com/walmartlabs/concord/server/queueclient/QueueClient.java
> concord-queue-client: tone down errors when stopping

- console2/package-lock.json
- console2/package.json
See also https://github.com/walmartlabs/concord/pull/33
> concord-console: update lodash to address a CVE

- cli/src/main/java/com/walmartlabs/concord/cli/runner/CliServicesModule.java
- runtime/v2/runner/pom.xml
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/DefaultDependencyManager.java
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/guice/DefaultRunnerModule.java
- runtime/v2/runner/src/test/java/com/walmartlabs/concord/runtime/v2/runner/MainTest.java
- runtime/v2/sdk/src/main/java/com/walmartlabs/concord/runtime/v2/sdk/DependencyManager.java
Pretty much a verbatim copy from the v1 SDK.
> runtime-v2: provide a DependencyManager implementation

- console2/src/components/molecules/ProcessLogViewer/index.tsx
- console2/src/components/organisms/ProcessLogActivity/index.tsx
link format:
```
#/process/<instance-id>/log#event-correlation-id
```
> concord-console: a way to get a link to a specific checkpoint in process logs

- docker-images/base/oss/Dockerfile
Use en_US.UTF-8 as the default locale in the base image.
> docker-images: specify the default locale

- runtime/v2/sdk/src/main/java/com/walmartlabs/concord/runtime/v2/sdk/Variables.java
Add missing `assert*` methods to `Variables`.
> runtime-v2: add more utility methods to Variables

- console2/src/components/molecules/LoadingEditor/index.tsx
- console2/src/components/molecules/ProjectConfiguration/index.tsx
- console2/src/components/molecules/ProjectConfiguration/styles.css
- console2/src/components/pages/JsonStorePage/EditStoreQueryForm.tsx
- console2/src/components/pages/JsonStorePage/NewStorageQueryForm.tsx
>  console: fix json store query editor

- console2/src/api/process/index.ts
- console2/src/components/molecules/LoadingEditor/index.tsx
- console2/src/components/molecules/LogSegment/index.tsx
- console2/src/components/molecules/LogSegment/styles.css
- console2/src/components/organisms/ProcessLogActivityV2/LogSegmentActivity.tsx
changed theme to white
added icons and tooltips for additional actions
minor css changes
> console-v2: log segments styling

- it/server/src/test/java/com/walmartlabs/concord/it/server/ProjectIT.java
- it/server/src/test/resources/com/walmartlabs/concord/it/server/project-triggers/concord.yml
- runtime/v1/project-model/src/main/java/com/walmartlabs/concord/project/yaml/YamlTriggersConverter.java
we do not have v1 triggers anymore
> runtime-v1: fix github trigger definition parse

- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/vm/RetryWrapper.java
- runtime/v2/runner/src/test/java/com/walmartlabs/concord/runtime/v2/runner/MainTest.java
- runtime/v2/runner/src/test/resources/com/walmartlabs/concord/runtime/v2/runner/retry/concord.yml
E.g. when the exception doesn't have a message.
> runtime-v2: fix potential NPE in RetryWrapper

- cli/src/main/java/com/walmartlabs/concord/cli/runner/CliSecretServiceV2.java
- client/src/main/java/com/walmartlabs/concord/client/CreateSecretRequest.java
- client/src/main/java/com/walmartlabs/concord/client/SecretClient.java
- client/src/main/java/com/walmartlabs/concord/client/SecretRequest.java
- it/runtime-v2/src/test/java/com/walmartlabs/concord/it/runtime/v2/CryptoIT.java
- it/runtime-v2/src/test/resources/com/walmartlabs/concord/it/runtime/v2/cryptoCreate/concord.yml
- plugins/tasks/crypto/pom.xml
- plugins/tasks/crypto/src/main/java/com/walmartlabs/concord/plugins/crypto/CryptoTaskV2.java
- plugins/tasks/crypto/src/main/java/com/walmartlabs/concord/plugins/crypto/TaskParams.java
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/DefaultSecretService.java
- runtime/v2/sdk/src/main/java/com/walmartlabs/concord/runtime/v2/sdk/SecretService.java
- server/impl/src/main/java/com/walmartlabs/concord/server/org/secret/SecretResource.java
task params:
```
crypto:
in:
action: create
org: <org-name>
project: <project-name>
secretName: <secret-name>
generatePwd: <true|false>
storePassword: <secret-password>
visibility: <PUBLIC|PRIVATE>
keyPair:
public: <path-to-public-key>
private: <path-to-private-key>
usernamePassword:
username: <username>
password: <password>
data: <path-to-data>
```
> crypto: create secrets from crypto task runtime-v2

- common/src/main/java/com/walmartlabs/concord/common/ConfigurationUtils.java
- runtime/v2/model/src/main/java/com/walmartlabs/concord/runtime/v2/ProjectLoaderV2.java
- runtime/v2/model/src/main/java/com/walmartlabs/concord/runtime/v2/model/EventConfiguration.java
- runtime/v2/model/src/main/java/com/walmartlabs/concord/runtime/v2/model/ProcessConfiguration.java
- runtime/v2/model/src/main/java/com/walmartlabs/concord/runtime/v2/model/Profile.java
We need to merge all EventConfiguration instances of all loaded Concord YAML files.
> runtime-v2: merge EventConfiguration when loading multiple resources

- k8s/agent-operator/src/main/java/com/walmartlabs/concord/agentoperator/processqueue/ProcessQueueClient.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/ProcessResourceV2.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/queue/ProcessQueueDao.java
+ exclude scheduled processes for agent operator
> server: list process requirements with startAt

- console2/src/components/molecules/GitHubLink/index.tsx
- console2/src/components/molecules/ProcessElementList/index.tsx
- console2/src/components/organisms/ProcessActivity/index.tsx
- console2/src/components/organisms/ProcessEventsActivity/index.tsx
- console2/src/components/organisms/ProjectOutVariablesModeActivity/index.tsx
> console: link to concord.yml from process events page (runtime-v2 only)

- server/impl/src/main/java/com/walmartlabs/concord/server/org/OrganizationDao.java
- server/impl/src/main/java/com/walmartlabs/concord/server/org/OrganizationManager.java
Allows plugins to use OrgManager's methods within their own transactions.
> concord-server: tx aware OrganizationManager's createOrUpdate/get

- server/impl/src/main/java/com/walmartlabs/concord/server/org/OrganizationDao.java
- server/impl/src/main/java/com/walmartlabs/concord/server/org/OrganizationManager.java
- server/impl/src/main/java/com/walmartlabs/concord/server/org/policy/PolicyCheckResource.java
- server/impl/src/main/java/com/walmartlabs/concord/server/org/project/ProjectDao.java
- server/impl/src/main/java/com/walmartlabs/concord/server/org/project/ProjectManager.java
- server/impl/src/main/java/com/walmartlabs/concord/server/org/project/ProjectOperationResult.java
- server/impl/src/main/java/com/walmartlabs/concord/server/org/project/ProjectResource.java
- server/impl/src/main/java/com/walmartlabs/concord/server/user/UserDao.java
- server/impl/src/main/java/com/walmartlabs/concord/server/user/UserManager.java
> concord-server: tx aware ProjectManager's createOrUpdate/get, other methods

- repository/src/main/java/com/walmartlabs/concord/repository/Snapshot.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/Payload.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/PayloadBuilder.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/PayloadUtils.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/pipelines/processors/PayloadStoreProcessor.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/pipelines/processors/ProcessDefinitionProcessor.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/pipelines/processors/RepositoryProcessor.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/pipelines/processors/StateImportingProcessor.java
- server/sdk/src/main/java/com/walmartlabs/concord/server/sdk/ProcessKey.java
E.g.
```java
PayloadBuilder b = PayloadBuilder.start(...)
.file("concord.yml", "flows\n  default:\n    - log: 'hello'\n");
```
> concord-server: a PayloadBuilder method to add files

- plugins/tasks/ansible/src/main/java/com/walmartlabs/concord/plugins/ansible/AnsibleAuth.java
- plugins/tasks/ansible/src/main/java/com/walmartlabs/concord/plugins/ansible/AnsibleTask.java
- plugins/tasks/ansible/src/main/java/com/walmartlabs/concord/plugins/ansible/KerberosAuth.java
- plugins/tasks/ansible/src/main/java/com/walmartlabs/concord/plugins/ansible/NopAuth.java
- plugins/tasks/ansible/src/main/java/com/walmartlabs/concord/plugins/ansible/PrivateKeyAuth.java
https://github.com/walmartlabs/concord/issues/160
Bug when nested containers are used kerberos auth was broken. Fixed by replacing the parent {{workdir}} in tgtCacheFile to container workspace "/workspace"
> bug-kerberos-nested-container: change to docker container workspace

- server/impl/src/main/java/com/walmartlabs/concord/server/audit/AuditLogResource.java
now users can see trigger github event from UI
> server: allow non admin users to search audit logs by eventId

- examples/http/README.md
- examples/runtime-v2/basic_example/README.md
- examples/runtime-v2/basic_example/concord.yml
- examples/runtime-v2/basic_example/concord/example.concord.yml
- examples/runtime-v2/basic_example/run.sh
- examples/runtime-v2/parallel_execution/concord.yml
- examples/runtime-v2/parallel_execution/run.sh
Test Runs:
https://concord.prod.walmart.com/#/process/d47baa60-f18c-4841-be69-5130ec41ccd8/log
https://concord.prod.walmart.com/#/process/a2ad585e-16b6-49d2-9bb2-4ea51f93d497/log
> examples: runtime v2 sample flows

- runtime/v2/model/src/main/java/com/walmartlabs/concord/runtime/v2/model/EventConfiguration.java
- server/sdk/src/main/java/com/walmartlabs/concord/server/sdk/ConcordApplicationException.java
Plus a serialVersionUID for ConcordApplicationException.
> runtime-v2: more javadocs for EventConfiguration

- server/impl/src/main/java/com/walmartlabs/concord/server/events/github/GithubTriggerV2Processor.java
- server/impl/src/main/java/com/walmartlabs/concord/server/events/github/Payload.java
`files.any` contains list of all files (modified, changed, deleted)
> server: github triggers: added `files.any` condition

- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/vm/ExpressionCommand.java
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/vm/ScriptCallCommand.java
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/vm/StepCommand.java
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/vm/TaskCallCommand.java
> runtime-v2: eval segment name for all steps

- server/impl/src/main/java/com/walmartlabs/concord/server/metrics/FailedTaskError.java
- server/impl/src/main/java/com/walmartlabs/concord/server/metrics/FailedTaskMetrics.java
- server/impl/src/main/java/com/walmartlabs/concord/server/task/SchedulerDao.java
- server/impl/src/main/java/com/walmartlabs/concord/server/task/TaskScheduler.java
- server/impl/src/test/java/com/walmartlabs/concord/server/tasks/SchedulerDaoTest.java
server tasks failures are added to metrics (while monitoring tasks table)
> metrics: add failed task metrics to collector

- server/db/src/main/resources/com/walmartlabs/concord/server/db/v0.17.0.xml
internal vulnerability fix https://brinqa.wal-mart.com/tvm/issues/1320830370345119745
> server: remove WM AD group from db changelog

- console2/src/components/organisms/Login2/index.tsx
> console: link to login with api key form from login page

- console2/src/components/molecules/RepositoryForm/index.tsx
- console2/src/components/organisms/Login2/index.tsx
- repository/src/main/java/com/walmartlabs/concord/repository/GitClient.java
Now users can create `Single Value` secrets with GH access token and use it to auth to GH repository
> git: support for OAuth tokens

- console2/src/api/org/index.ts
- console2/src/components/atoms/TableSearchFilter/index.tsx
- console2/src/components/molecules/ProcessList/index.tsx
> console: support for `boolean` values in process list

- console2/src/components/molecules/ProcessList/index.tsx
- console2/src/components/organisms/ProcessListActivity/index.tsx
- it/runtime-v2/src/test/java/com/walmartlabs/concord/it/runtime/v2/ProcessIT.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/queue/ProcessQueueManager.java
```
{
"ui":{
"processList":[
....
{
"builtin":"entryPoint"
}
]
}
}
```
> console: support for entryPoint column in process list

- runtime/v2/model/src/main/java/com/walmartlabs/concord/runtime/v2/parser/GrammarOptions.java
- runtime/v2/model/src/main/java/com/walmartlabs/concord/runtime/v2/parser/TriggersGrammar.java
- runtime/v2/model/src/main/java/com/walmartlabs/concord/runtime/v2/parser/YamlValueType.java
- runtime/v2/model/src/test/java/com/walmartlabs/concord/project/runtime/v2/parser/YamlErrorParserTest.java
- runtime/v2/model/src/test/resources/009.yml
- runtime/v2/model/src/test/resources/errors/triggers/032.yml
- runtime/v2/model/src/test/resources/errors/triggers/033.yml
- runtime/v2/model/src/test/resources/errors/triggers/034.yml
- runtime/v2/model/src/test/resources/errors/triggers/035.yml
+ grammar: expected options are now sorted
> runtime-v2: github trigger repositoryInfo condition grammar

- console2/src/components/molecules/ProcessLastErrorModal/index.tsx
- console2/src/components/organisms/ProcessLogActivityV2/LogSegmentActivity.tsx
- console2/src/components/organisms/TriggeredByPopup/index.tsx
> console: scrollable modal windows

- it/common/src/main/java/com/walmartlabs/concord/it/common/ServerClient.java
- it/server/src/test/java/com/walmartlabs/concord/it/server/DockerIT.java
- it/server/src/test/resources/com/walmartlabs/concord/it/server/dockerPullRetry/concord.yml
Also improve the log assertion messages a bit.
> it: speed up the Docker test a bit by reducing the retry interval

- it/runtime-v2/src/test/java/com/walmartlabs/concord/it/runtime/v2/JsonStoreIT.java
- it/runtime-v2/src/test/resources/com/walmartlabs/concord/it/runtime/v2/jsonStore/concord.yml
- it/server/src/test/java/com/walmartlabs/concord/it/server/JsonStoreTaskIT.java
- it/server/src/test/resources/com/walmartlabs/concord/it/server/jsonStoreTask/_agent.json
- it/server/src/test/resources/com/walmartlabs/concord/it/server/jsonStoreTask/concord.yml
- it/server/src/test/resources/com/walmartlabs/concord/it/server/jsonStoreTaskStoreTest/concord.yml
- plugins/tasks/concord/src/main/java/com/walmartlabs/concord/client/JsonStoreTask.java
- plugins/tasks/concord/src/main/java/com/walmartlabs/concord/client/JsonStoreTaskCommon.java
- plugins/tasks/concord/src/main/java/com/walmartlabs/concord/client/RequestUtils.java
- plugins/tasks/concord/src/main/java/com/walmartlabs/concord/client/v2/JsonStoreTaskV2.java
- server/impl/src/main/java/com/walmartlabs/concord/server/org/jsonstore/JsonStoreAccessManager.java
New methods to check if the record and/or store exists and to insert a
record with automatic store creation.
> concord-tasks: add more methods to the JSON store task

- console2/src/components/atoms/Scrollable.tsx
- console2/src/components/organisms/TaskCallDetails/index.tsx
> console: runtime-v2: show file name in the segment info popup

- examples/ansible/concord.yml
- examples/ansible_docker/concord.yml
- examples/ansible_dynamic_inventory/concord.yml
- examples/ansible_form/concord.yml
- examples/ansible_form_as_inventory/concord.yml
- examples/ansible_kerberos/concord.yml
- examples/ansible_limit/concord.yml
- examples/ansible_out_vars/concord.yml
- examples/ansible_remote/concord.yml
- examples/ansible_retry/concord.yml
- examples/ansible_roles/concord.yml
- examples/ansible_stats/concord.yml
- examples/ansible_vault/concord.yml
- examples/ansible_windows/concord.yml
- examples/context_injection/concord.yml
- examples/dynamic_tasks/concord.yml
- examples/dynamic_tasks/runtime-v2/concord.yml
- examples/git/concord.yml
- examples/inventory/concord.yml
- examples/inventory_lookup/concord.yml
- examples/jira/concord.yml
- examples/ldap/concord.yml
- examples/mocking/concord.yml
- examples/noderoster/concord.yml
- examples/secret_lookup/concord.yml
- examples/smtp/concord.yml
- examples/smtp_html/concord.yml
Update dependencies in examples to the current version of plugins.
> examples: update dependencies

- repository/src/main/java/com/walmartlabs/concord/repository/GitClient.java
+  projectInfo.repoCommitAuthor fix
> concord-repository: fix commit info command

- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/el/LazyExpressionEvaluator.java
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/el/resolvers/MethodAccessorResolver.java
- runtime/v2/runner/src/test/java/com/walmartlabs/concord/runtime/v2/runner/el/ImmutablesTest.java
Adds support for Immutables-style accessor methods.
> runtime-v2: add EL resolver for plain accessor methods

- repository/src/main/java/com/walmartlabs/concord/repository/GitClient.java
- repository/src/test/java/com/walmartlabs/concord/repository/GitClientTest5.java
- repository/src/test/java/com/walmartlabs/concord/repository/GitUtils.java
- repository/src/test/resources/test5/0_concord.yml
- repository/src/test/resources/test5/1_concord.yml
- repository/src/test/resources/test5/2_concord.yml
ignore `git reset <branch>` when commitId specified
> git-client: fix fetch with commitID + branch

- console2/src/components/organisms/RequestErrorActivity/index.tsx
- server/dist/src/main/resources/concord-server.conf
- server/impl/src/main/java/com/walmartlabs/concord/server/security/internal/LocalUserInfoProvider.java
- server/impl/src/main/java/com/walmartlabs/concord/server/security/ldap/LdapUserInfoProvider.java
- server/impl/src/main/java/com/walmartlabs/concord/server/user/UserInfoProvider.java
- server/impl/src/main/java/com/walmartlabs/concord/server/user/UserManager.java
- server/impl/src/main/java/com/walmartlabs/concord/server/user/UserResource.java
- server/plugins/pfed-sso/src/main/java/com/walmartlabs/concord/server/plugins/pfedsso/SsoAuthFilter.java
- server/plugins/pfed-sso/src/main/java/com/walmartlabs/concord/server/plugins/pfedsso/SsoClient.java
- server/plugins/pfed-sso/src/main/java/com/walmartlabs/concord/server/plugins/pfedsso/SsoConfiguration.java
- server/plugins/pfed-sso/src/main/java/com/walmartlabs/concord/server/plugins/pfedsso/SsoCookies.java
- server/plugins/pfed-sso/src/main/java/com/walmartlabs/concord/server/plugins/pfedsso/SsoHandler.java
- server/plugins/pfed-sso/src/main/java/com/walmartlabs/concord/server/plugins/pfedsso/SsoRealm.java
- server/plugins/pfed-sso/src/main/java/com/walmartlabs/concord/server/plugins/pfedsso/SsoToken.java
* SSO authentication is successful after verification of user with AD/LDAP. Hence PR to remove redundant check with LDAP when user logged in through sso.
* Add user info openid endpoint to get user attributes while creating new users
* Add sso redirect on token/session expiration in console
> concord-server,pfed-sso: sso login independent of ldap

- console2/src/api/process/log/index.ts
- console2/src/components/molecules/LogSegment/index.tsx
- console2/src/components/organisms/ProcessLogActivityV2/LogSegmentActivity.tsx
- console2/src/components/organisms/ProcessLogActivityV2/index.tsx
- console2/src/components/organisms/RequestErrorActivity/index.tsx
- server/db/src/main/resources/com/walmartlabs/concord/server/db/liquibase.xml
- server/db/src/main/resources/com/walmartlabs/concord/server/db/v1.81.0.xml
- server/impl/src/main/java/com/walmartlabs/concord/server/process/LogSegment.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/ProcessLogResourceV2.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/logs/ProcessLogsDao.java
Add duration for closed segments.
> concord-server, concord-console: add log segment duration

- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/script/DefaultScriptEvaluator.java
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/script/ScriptEvaluator.java
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/vm/ScriptCallCommand.java
fix for:
```
...
- script: example.py
```
```
...
00:52:02 [ERROR] java.lang.RuntimeException: Unknown language 'py'. Check process dependencies.
...
```
> runtime-v2: fix external script execution

- server/plugins/pfed-sso/README.md
Add readme to pingfed-sso plugin
> pfed-sso-plugin: add readme

- examples/runtime-v2/demo-flow/README.md
- examples/runtime-v2/demo-flow/concord.yml
- examples/runtime-v2/demo-flow/concord/forms.concord.yml
- examples/runtime-v2/demo-flow/concord/test.concord.yml
- examples/runtime-v2/demo-flow/scripts/test-script.groovy
end to end demo flow that highlights v2 features and migration guidelines for users.
process run: https://concord.prod.walmart.com/#/process/e194bd3d-b932-451a-9feb-7e77fa3a8a3f/log
> examples: runtime v2 demo 

- plugins/tasks/http/src/main/java/com/walmartlabs/concord/plugins/http/Configuration.java
- plugins/tasks/http/src/main/java/com/walmartlabs/concord/plugins/http/HttpTask.java
- plugins/tasks/http/src/main/java/com/walmartlabs/concord/plugins/http/SimpleHttpClient.java
support for client cert/keys.
new params:
```
keystorePath - optional, string, path to pkcs12 keystore;
keystorePassword - optional, string, keystore password.
```
> http task: support for keystore

- server/impl/src/main/java/com/walmartlabs/concord/server/process/queue/ProcessQueueWatchdog.java
```
....
13:28:54 [ERROR] Process exit code: 1
13:28:54 [INFO ] Process status: FAILED
13:28:57 [INFO ] Failure handler started: 92f5fdc6-1f25-4bc6-aea0-b05b4b7d6619
```
> server: log ID of process handler into process log

- console2/src/components/molecules/GitHubLink/index.tsx
- console2/src/components/molecules/ProcessStatusTable/index.tsx
- console2/src/components/molecules/RepositoryList/index.tsx
Add in repository list page
Update in Process Status table
> concord-console: add branchOrCommitd and repoPath links

- console2/src/state/data/processes/logs/processors.ts
- plugins/tasks/concord/src/main/java/com/walmartlabs/concord/client/ConcordTask.java
- plugins/tasks/concord/src/main/java/com/walmartlabs/concord/client/ConcordTaskCommon.java
- plugins/tasks/concord/src/main/java/com/walmartlabs/concord/client/ConcordTaskParams.java
- plugins/tasks/concord/src/main/java/com/walmartlabs/concord/client/v2/ConcordTaskV2.java
- sdk/src/main/java/com/walmartlabs/concord/sdk/LogTags.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/queue/ProcessQueueWatchdog.java
from code:
```
...
log.info("Forked a child process: {}", LogTags.instanceId(resp.getInstanceId()));
...
```
UI:
> ability to log process instanceId as link on UI

- console2/src/components/molecules/ProcessForm/index.tsx
- forms/src/main/java/com/walmartlabs/concord/forms/FormUtils.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/form/FormUtils.java
```
forms:
myForm:
- field1_1: { label: "ONE_AND_ONLY_ONE with single allow value", type: "string", allow: "single-value", search: true }
- field1_2: { label: "ONE_AND_ONLY_ONE with array allow value", type: "string", allow: ["single-array-value"], search: true }
- field1_3: { label: "ONE_AND_ONLY_ONE with multi array allow value", type: "string", allow: ["first", "second"], search: true }
- field1_4: { label: "ONE_AND_ONLY_ONE without allow value", type: "string", search: true }
- field2_1: { label: "AT_LEAST_ONE with single allow value", type: "string+", allow: "single-value", search: true }
- field2_2: { label: "AT_LEAST_ONE with array allow value", type: "string+", allow: ["single-value"], search: true }
- field2_3: { label: "AT_LEAST_ONE with multi array allow value", type: …
```
> console2: fix render of form dropdown field with single allowed value

- console2/src/components/molecules/ProcessForm/index.tsx
- console2/src/state/data/processes/logs/processors.ts
> console2: fix form field dropdown

- server/plugins/pfed-sso/src/main/java/com/walmartlabs/concord/server/plugins/pfedsso/SsoAuthFilter.java
fix for repeated log in screen when user reopens the browser immediately after close
> pfed-sso: do not redirect if refresh token exists

- examples/runtime-v2/demo-flow/run.sh
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/Main.java
- runtime/v2/runner/src/test/java/com/walmartlabs/concord/runtime/v2/runner/MainTest.java
> runtime-v2: rollback state cleanup

- docker-images/compose/docker-compose.yml
Fixes issue https://github.com/walmartlabs/concord/issues/398
> docker-compose: Fix agent and dind communication

- plugins/tasks/http/src/main/java/com/walmartlabs/concord/plugins/http/Configuration.java
- plugins/tasks/http/src/main/java/com/walmartlabs/concord/plugins/http/HttpTask.java
- plugins/tasks/http/src/main/java/com/walmartlabs/concord/plugins/http/SimpleHttpClient.java
* Add `strictSsl` option
* Add support for `custom truststore`
> http-plugin: add support for custom truststore

- agent/src/assembly/start.sh
- cli/pom.xml
- server/dist/src/assembly/start.sh
Fixes https://github.com/walmartlabs/concord/issues/415
> Ability to run Concord on Java 16

- server/impl/src/main/java/com/walmartlabs/concord/server/Listeners.java
Need to forcefully cancel task if exception on listener
> concord-server: task cancel on exception

- server/impl/src/main/java/com/walmartlabs/concord/server/security/ldap/LdapGroupDao.java
- server/impl/src/main/java/com/walmartlabs/concord/server/security/ldap/SyncUserLdapGroupRequest.java
- server/impl/src/main/java/com/walmartlabs/concord/server/security/ldap/UserLdapGroup.java
- server/impl/src/main/java/com/walmartlabs/concord/server/security/ldap/UserLdapGroupSynchronizer.java
API to sync ldap groups for a user
> concord-server: add user ldapgroup sync api

- console2/src/components/organisms/Login2/index.tsx
- server/plugins/pfed-sso/src/main/java/com/walmartlabs/concord/server/plugins/pfedsso/RedirectHelper.java
- server/plugins/pfed-sso/src/main/java/com/walmartlabs/concord/server/plugins/pfedsso/SsoCallbackFilter.java
- server/plugins/pfed-sso/src/main/java/com/walmartlabs/concord/server/plugins/pfedsso/SsoLogoutFilter.java
- Redirect to default login whenever pingfed fails to provide auth token or fails due to some other IO issue
> pfed-sso: redirect to login on failure sso

- runtime/v1/impl/src/main/java/com/walmartlabs/concord/runner/engine/DefaultElementEventProcessor.java
- runtime/v1/impl/src/main/java/com/walmartlabs/concord/runner/engine/ElementEventProcessor.java
- runtime/v1/impl/src/main/java/com/walmartlabs/concord/runner/engine/EngineFactory.java
- runtime/v1/impl/src/main/java/com/walmartlabs/concord/runner/engine/EventConfiguration.java
- runtime/v1/impl/src/main/java/com/walmartlabs/concord/runner/engine/NopElementEventProcessor.java
- runtime/v2/model/src/main/java/com/walmartlabs/concord/runtime/v2/ConcordJsonSchemaGenerator.java
- runtime/v2/model/src/main/java/com/walmartlabs/concord/runtime/v2/model/EventConfiguration.java
- runtime/v2/model/src/main/java/com/walmartlabs/concord/runtime/v2/parser/ConfigurationGrammar.java
- runtime/v2/model/src/test/java/com/walmartlabs/concord/project/runtime/v2/ConcordJsonSchemaGeneratorTest.java
- runtime/v2/model/src/test/java/com/walmartlabs/concord/project/runtime/v2/parser/YamlErrorParserTest.java
- runtime/v2/model/src/test/resources/serializer/processDefinition.yml
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/remote/EventRecordingExecutionListener.java
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/remote/TaskCallEventRecordingListener.java
runtime-v1:
```
configuration:
runner:
events:
recordEvents: false|true
```
runtime-v2:
```
configuration:
events:
recordEvents: false|true
```
or better rename this option to `enable: true|false` ?
> runtime-v1/v2: ability to disable events recording

- console2/src/api/org/project/repository/index.ts
- console2/src/api/service/console/index.ts
- console2/src/components/molecules/LoadingEditor/index.tsx
- console2/src/components/molecules/RepositoryForm/index.tsx
- console2/src/components/organisms/CheckpointView/Container/__tests__/checkpointUtils.test.ts
- console2/src/components/organisms/EditRepositoryActivity/index.tsx
- console2/src/components/organisms/Login2/index.tsx
- console2/src/components/pages/RepositoryPage/RepositorySettingsActivity.tsx
- server/db/src/main/resources/com/walmartlabs/concord/server/db/liquibase.xml
- server/db/src/main/resources/com/walmartlabs/concord/server/db/v0.48.0.xml
- server/db/src/main/resources/com/walmartlabs/concord/server/db/v1.91.0.xml
- server/impl/src/main/java/com/walmartlabs/concord/server/org/project/ProjectDao.java
- server/impl/src/main/java/com/walmartlabs/concord/server/org/project/ProjectRepositoryManager.java
- server/impl/src/main/java/com/walmartlabs/concord/server/org/project/RepositoryDao.java
- server/impl/src/main/java/com/walmartlabs/concord/server/org/project/RepositoryEntry.java
- server/impl/src/main/java/com/walmartlabs/concord/server/org/triggers/TriggerManager.java
- server/impl/src/main/java/com/walmartlabs/concord/server/repository/listeners/TriggerRefreshListener.java
- server/impl/src/test/java/com/walmartlabs/concord/server/security/secret/SecretDaoTest.java
- server/impl/src/test/java/com/walmartlabs/concord/server/template/ProjectDaoTest.java
> server, console: allow users to disable triggers in repository

- plugins/tasks/docker/src/main/java/com/walmartlabs/concord/plugins/docker/DockerTaskV2.java
new input variables:
```
redirectErrorStream - optional, boolean. If `true` docker std error stream redirects to std out; 
logOut - optional, boolean. If `true` Concord logs docker std out to process logs;
logErr - optional, boolean. If `true` Concord logs docker std error to process logs;
saveOut - optional, boolean. If `true` docker task returns std out as task result;
saveErr - optional, boolean. If `true` docker task returns std err as task result;
```
> docker: more input params to handle logging

- it/server/src/test/java/com/walmartlabs/concord/it/server/TimeoutHandlingIT.java
- it/server/src/test/resources/com/walmartlabs/concord/it/server/timeoutHandling/.concord.yml
- sdk/src/main/java/com/walmartlabs/concord/sdk/Constants.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/pipelines/processors/ConfigurationProcessor.java
```
configuration:
...
handlerProcessTimeout: "PT1M"
...
```
> server: allow users to override handlers timeout

- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/context/ContextImpl.java
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/el/LazyExpressionEvaluator.java
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/el/functions/CurrentFlowNameFunction.java
- runtime/v2/runner/src/test/java/com/walmartlabs/concord/runtime/v2/runner/MainTest.java
- runtime/v2/runner/src/test/java/com/walmartlabs/concord/runtime/v2/runner/el/SingleFrameContext.java
- runtime/v2/runner/src/test/resources/com/walmartlabs/concord/runtime/v2/runner/currentFlowName/concord.yml
- runtime/v2/sdk/src/main/java/com/walmartlabs/concord/runtime/v2/sdk/Execution.java
```
flows:
default:
- log: "default: ${currentFlowName()}" # default: default
```
> runtime-v2: allow users to get current flow name

- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/script/DefaultScriptEvaluator.java
- disable graalvm warining:
```
WARNING: The polyglot context is using an implementation that does not support runtime compilation...
```
> runtime-v2: disable warning for graalvm, fix logging

- plugins/tasks/lock/src/main/java/com/walmartlabs/concord/plugins/lock/LockTaskCommon.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/locks/ProcessLocksResource.java
[LockService](https://github.com/walmartlabs/concord/blob/master/runtime/v1/impl/src/main/java/com/walmartlabs/concord/runner/LockServiceImpl.java#L65) will not create wait condition for each iteration :)
> server, lock-task: lock task creates lock wait condition

- console2/src/api/process/index.ts
- console2/src/components/molecules/LogSegment/index.tsx
> console: icon for segment of suspended process

- client/pom.xml
- it/runtime-v2/pom.xml
- it/server/pom.xml
- plugins/tasks/http/pom.xml
- plugins/tasks/http/src/test/resources/logback.xml
- plugins/tasks/smtp/pom.xml
- pom.xml
- runtime/v1/impl/pom.xml
- runtime/v2/model/src/test/java/com/walmartlabs/concord/project/runtime/v2/ConcordJsonSchemaGeneratorTest.java
- runtime/v2/runner/pom.xml
- targetplatform/pom.xml
includes: 
https://github.com/walmartlabs/concord/pull/525
https://github.com/walmartlabs/concord/pull/524
https://github.com/walmartlabs/concord/pull/511
https://github.com/walmartlabs/concord/pull/510
https://github.com/walmartlabs/concord/pull/507
> versions up

- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/checkpoints/DefaultCheckpointService.java
- server/impl/src/main/java/com/walmartlabs/concord/server/MultipartUtils.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/checkpoint/ProcessCheckpointResource.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/state/ProcessCheckpointDao.java
before:
```
22:01:33 [WARN ] call error: '(http://localhost:8001) Server response: ERROR: (ID 8b540a59-64db-455c-a0d9-b919820cf485) org.jooq.exception.DataAccessException: Error while running ConnectionCallable: ERROR: (ID 8b540a59-64db-455c-a0d9-b919820cf485) org.jooq.exception.DataAccessException: Error while running ConnectionCallable'
22:01:33 [INFO ] retry after 5 sec
22:01:38 [WARN ] call error: '(http://localhost:8001) Server response: ERROR: (ID 9bedb003-b56b-4c20-8a21-b36684a6f71c) org.jooq.exception.DataAccessException: Error while running ConnectionCallable: ERROR: (ID 9bedb003-b56b-4c20-8a21-b36684a6f71c) org.jooq.exception.DataAccessException: Error while running ConnectionCallable'
22:01:38 [INFO ] retry after 5 sec
22:01:43 [WARN ] call error: '(http://localhost:8001) …
```
> server: better checkpoint info validation

- agent/src/main/java/com/walmartlabs/concord/agent/remote/ApiClientFactory.java
> agent: single tmp dir for api-client

- it/runtime-v2/src/test/java/com/walmartlabs/concord/it/runtime/v2/ProcessIT.java
- it/runtime-v2/src/test/resources/com/walmartlabs/concord/it/runtime/v2/scriptJs/concord.yml
- runtime/v1/impl/pom.xml
- runtime/v2/runner/pom.xml
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/script/DefaultScriptEvaluator.java
- targetplatform/pom.xml
depends on https://github.com/concord-workflow/bpm/pull/13
> graalvm: use nashorn compat mode

- it/server/src/test/java/com/walmartlabs/concord/it/server/CronIT.java
- it/server/src/test/resources/com/walmartlabs/concord/it/server/cronRunAs/concord.yml
- runtime/v2/model/src/main/java/com/walmartlabs/concord/runtime/v2/parser/TriggersGrammar.java
- runtime/v2/model/src/main/java/com/walmartlabs/concord/runtime/v2/parser/YamlValueType.java
- runtime/v2/model/src/main/java/com/walmartlabs/concord/runtime/v2/schema/TriggerMixIn.java
- runtime/v2/model/src/test/java/com/walmartlabs/concord/project/runtime/v2/parser/YamlErrorParserTest.java
- runtime/v2/model/src/test/java/com/walmartlabs/concord/project/runtime/v2/parser/YamlOkParserTest.java
- runtime/v2/model/src/test/resources/009.yml
- runtime/v2/model/src/test/resources/errors/triggers/031_1.yml
- server/impl/src/main/java/com/walmartlabs/concord/server/org/secret/SecretManager.java
- server/impl/src/main/java/com/walmartlabs/concord/server/org/triggers/TriggerRunAs.java
- server/impl/src/main/java/com/walmartlabs/concord/server/org/triggers/TriggerScheduler.java
- server/impl/src/main/java/com/walmartlabs/concord/server/org/triggers/TriggerSchedulerEntry.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/ProcessSecurityContext.java
```
triggers:
- cron:
spec: "* * * * *"
entryPoint: onCron
runAs:
withSecret: "test-run-as"    # secret must be linked to the project and contain the API token of the initiator
```
> runtime-v2: cron: support for runAs

- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/script/DefaultScriptEvaluator.java
```
flows:
default:
- script: python
body: |
print "321"
```
> runtime-v2: script logs to logger

- examples/hello_world/test.properties
- plugins/tasks/resource/pom.xml
- plugins/tasks/resource/src/main/java/com/walmartlabs/concord/plugins/resource/ResourceTaskCommon.java
- plugins/tasks/resource/src/main/java/com/walmartlabs/concord/plugins/resource/v2/ResourceTaskV2.java
- plugins/tasks/resource/src/test/java/com/walmartlabs/concord/plugins/resource/ResourceTaskCommonTest.java
- plugins/tasks/resource/src/test/resources/com/walmartlabs/concord/plugins/resource/test.properties
new methods:
```
Map<String, Object> asProperties(path);
Map<String, Object> asProperties(path, eval);
```
> resources-v2: support for properties files

- client/src/main/java/com/walmartlabs/concord/client/ClientUtils.java
- client/src/main/java/com/walmartlabs/concord/client/SecretClient.java
- client/src/main/java/com/walmartlabs/concord/client/UpdateSecretRequest.java
- it/server/pom.xml
- it/server/src/test/java/com/walmartlabs/concord/it/server/SecretIT.java
- server/impl/src/main/java/com/walmartlabs/concord/server/org/secret/SecretDao.java
- server/impl/src/main/java/com/walmartlabs/concord/server/org/secret/SecretManager.java
- server/impl/src/main/java/com/walmartlabs/concord/server/org/secret/SecretResource.java
- server/impl/src/main/java/com/walmartlabs/concord/server/org/secret/SecretResourceV2.java
- server/impl/src/main/java/com/walmartlabs/concord/server/org/secret/SecretUpdateParams.java
- server/impl/src/test/java/com/walmartlabs/concord/server/security/secret/SecretDaoTest.java
URI /api/v2/org/${orgName}/secret
Method POST
Headers Authorization, Content-Type: multipart/form-data
Multipart request
```
orgId - new organization identifier;
org - new organization name;
projectId - new project identifier;
project - new project name;
removeProjectLink - unlink secret from project;
ownerId - new owner identifier;
storePassword - current store passsword;
newStorePassword - new store password;
public - new public key file of the key pair;
private - new private key file of the key pair;
username - new string value;
password - new string value;
data - new string or binary value;
name - new secret name;
visibility - new secret visibility;
```
> server: api for updating a secret

- it/runtime-v2/src/test/resources/com/walmartlabs/concord/it/runtime/v2/scriptGroovy/concord.yml
- it/server/src/test/resources/com/walmartlabs/concord/it/server/dynamicFormWithGroovy/concord.yml
- it/server/src/test/resources/com/walmartlabs/concord/it/server/dynamicTask/concord.yml
- it/server/src/test/resources/com/walmartlabs/concord/it/server/externalImportWithDeps/concord.yml
- it/server/src/test/resources/com/walmartlabs/concord/it/server/filePerm/concord.yml
- it/server/src/test/resources/com/walmartlabs/concord/it/server/groovy/concord.yml
- it/server/src/test/resources/com/walmartlabs/concord/it/server/kvScript/concord.yml
- it/server/src/test/resources/com/walmartlabs/concord/it/server/mvnDeps/concord.yml
- it/server/src/test/resources/com/walmartlabs/concord/it/server/onFailureDependencies/concord.yml
- it/server/src/test/resources/com/walmartlabs/concord/it/server/projectfile/scriptWithErrorBlock/.concord.yml
- it/server/src/test/resources/com/walmartlabs/concord/it/server/serialization/.concord.yml
- targetplatform/pom.xml
Or, more precisely, downgrade from 3.x to 2.5.x to avoid breaking images without JDK.
> project: update to Groovy 2.5.17 to support JDK 17

- console2/src/api/__tests__/common.queryParams.test.ts
- console2/src/api/process/ansible/index.ts
- console2/src/components/atoms/ColumnSort/index.tsx
- console2/src/components/molecules/ansible/AnsibleHostList/index.tsx
- examples/custom_task/pom.xml
- server/plugins/ansible/impl/src/main/java/com/walmartlabs/concord/server/plugins/ansible/ProcessAnsibleResource.java
> ansible:  sort options on ansible host stats

- agent/src/main/java/com/walmartlabs/concord/agent/cfg/AgentConfiguration.java
- agent/src/main/java/com/walmartlabs/concord/agent/guice/AgentDependencyManagerConfigurationProvider.java
- agent/src/main/resources/concord-agent.conf
- dependency-manager/src/main/java/com/walmartlabs/concord/dependencymanager/DependencyManager.java
- dependency-manager/src/main/java/com/walmartlabs/concord/dependencymanager/DependencyManagerConfiguration.java
```  
dependencies:
- "mvn://org.codehaus.groovy:groovy-all:pom:3.0.2?exclude=com.sun:tools"
```
> dependency-manager: allow exclusion artifacts from transitive dependencies

- console2/src/components/molecules/LogSegment/styles.css
> compact view of log segments

- console2/src/components/molecules/LogSegment/styles.css
> console2: single vertical scroll for process log page

- console2/src/components/molecules/LogSegment/index.tsx
- console2/src/components/organisms/ProcessLogActivityV2/LogSegmentActivity.tsx
- console2/src/components/organisms/ProcessLogActivityV2/index.tsx
> console2: allow expand all log segments

- server/impl/src/main/java/com/walmartlabs/concord/server/org/triggers/TriggerScheduleDao.java
fix immutables NPE on null values
> cron: clean null values from trigger conditions, arguments, cfg

- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/el/LazyExpressionEvaluator.java
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/el/functions/ThrowFunction.java
- runtime/v2/runner/src/test/java/com/walmartlabs/concord/runtime/v2/runner/MainTest.java
- runtime/v2/runner/src/test/resources/com/walmartlabs/concord/runtime/v2/runner/throwExpression/concord.yml
sometimes it's useful to throw exception from EL:
```
- log: ${throw('boom')}
```
> runtime-v2: function for throw exception

- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/el/LazyEvalMap.java
- runtime/v2/runner/src/test/java/com/walmartlabs/concord/runtime/v2/runner/MainTest.java
- runtime/v2/runner/src/test/java/com/walmartlabs/concord/runtime/v2/runner/el/ExpressionEvaluatorTest.java
- runtime/v2/runner/src/test/resources/com/walmartlabs/concord/runtime/v2/runner/incVariable/concord.yaml
```
- set:
counter: 0
...
- set:
counter: ${counter + 1}
```
> runtime-v2: allow increment variable in expression

- server/impl/src/main/java/com/walmartlabs/concord/server/console/CustomFormServiceV1.java
- server/impl/src/main/java/com/walmartlabs/concord/server/console/CustomFormServiceV2.java
Fix for broken redirection from `custom form` to next `default form`.
> forms: fix default wizard url

- cli/src/main/java/com/walmartlabs/concord/cli/Run.java
- cli/src/main/java/com/walmartlabs/concord/cli/Verbosity.java
- cli/src/main/java/com/walmartlabs/concord/cli/runner/CliServicesModule.java
- cli/src/main/java/com/walmartlabs/concord/cli/runner/FlowStepLogger.java
- cli/src/main/java/com/walmartlabs/concord/cli/runner/TaskParamsLogger.java
**cli run** 
```
Starting...
19:13:30.732 [main] Hello, Concord!
...done!
```
**cli run -v** 
```
Starting...
>>> 'Task: log' @ concord.yml:3
19:14:11.572 [main] Hello, Concord!
...done!
```
**cli run -vv** 
```
Starting...
>>> 'Task: log' @ concord.yml:3
in: {msg=Hello, Concord!}
19:16:00.441 [main] Hello, Concord!
out: {ok=true}
duration: 2ms
...done!
```
**cli run -vvv** 
```
Copying files into the target directory...
Default configuration already exists: /Users/brig/.concord/defaultCfg.yml
Resolving process dependencies...
Dependency resolution took 1ms
No external dependencies.
Process arguments:
name: "Concord"
txId: "bd6a56dd-a1f3-4dc8-97b2-518cd902704a"
workDir: "/Users/brig/prj/github/concord/examples/hello_world/target"
Starting...
>>> 'Task: log' @ concord.yml:3
in: {msg=Hello, …
```
> cli: better verbose mode

- console2/cfg.d.ts
- console2/src/components/pages/ProcessListPage/index.tsx
just to see flow name/entrypoint in process list:)
cfg.js:
```
processListColumns: [
{
builtin: "status"
},
{
builtin: "instanceId"
},
{
caption: "Flow",
source: "meta.flow",
searchType: "equals",
searchValueType: "string"
},
{
caption: 'Project',
source: 'projectName',
render: 'project-link'
},
{
builtin: "initiator"
},
{
builtin: "createdAt"
},
{
builtin: "lastRunAt"
}
]
```
> console-2: allow customizing columns in the main process table

- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/el/LazyExpressionEvaluator.java
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/el/resolvers/MapELResolver.java
- runtime/v2/runner/src/test/java/com/walmartlabs/concord/runtime/v2/runner/MainTest.java
- runtime/v2/runner/src/test/resources/com/walmartlabs/concord/runtime/v2/runner/sensitiveData/concord.yaml
when task implements a map interface...
> runtime-v2: hide sensitive data in MapELResolver

- cli/src/main/java/com/walmartlabs/concord/cli/Run.java
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/Main.java
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/vm/SaveLastErrorCommand.java
- runtime/v2/sdk/src/main/java/com/walmartlabs/concord/runtime/v2/sdk/UserDefinedException.java
- runtime/v2/vm/src/main/java/com/walmartlabs/concord/svm/MultiException.java
I hope it will not be visible anymore.
Finally, I like how it looks now:)
> runtime-v2: hide stacktrace for UserDefinedException

- server/impl/src/main/java/com/walmartlabs/concord/server/process/ProcessCleaner.java
cleanup process_queue at the end of the cleanup process:)
> server: fix DB cleanup job

- console2/src/api/org/jsonstore/index.ts
- console2/src/components/pages/JsonStorePage/StoreOrganizationChangeActivity.tsx
- console2/src/components/pages/JsonStorePage/StoreSettings.tsx
- server/impl/src/main/java/com/walmartlabs/concord/server/org/jsonstore/JsonStoreDao.java
- server/impl/src/main/java/com/walmartlabs/concord/server/org/jsonstore/JsonStoreManager.java
- server/impl/src/main/java/com/walmartlabs/concord/server/org/jsonstore/JsonStoreRequest.java
> console2: allow changing JSON store org

- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/StackTraceCollector.java
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/vm/FlowCallCommand.java
- runtime/v2/runner/src/test/java/com/walmartlabs/concord/runtime/v2/runner/MainTest.java
- runtime/v2/runner/src/test/resources/com/walmartlabs/concord/runtime/v2/runner/doNotTouchFlowNameVariable/concord.yaml
> 1.103.x to master

- it/testing-server/src/main/java/com/walmartlabs/concord/it/testingserver/TestingConcordServer.java
- server/impl/src/main/java/com/walmartlabs/concord/server/ConcordServer.java
- server/impl/src/main/java/com/walmartlabs/concord/server/cfg/ConfigurationModule.java
- server/plugins/oidc/src/main/java/com/walmartlabs/concord/server/plugins/oidc/OidcCallbackFilter.java
- server/plugins/oidc/src/main/java/com/walmartlabs/concord/server/plugins/oidc/OidcPluginModule.java
- rename PluginModule to OidcPluginModule, makes easier to reference the module among the others
- bind Config in ConfigurationModule so it can be injected in "external" beans
- pass the config to all extra modules in testing-concord-server
> project: minor updates

- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/vm/IfCommand.java
- runtime/v2/runner/src/test/java/com/walmartlabs/concord/runtime/v2/runner/MainTest.java
- runtime/v2/runner/src/test/resources/com/walmartlabs/concord/runtime/v2/runner/ifExpressionAsString/concord.yml
useful when flow called with cli...
> runtime-v2: allow "true|false" string in if expression

- plugins/tasks/lock/src/main/java/com/walmartlabs/concord/plugins/lock/LockTaskCommon.java
properties for ProcessLockCondition: 
```
"instanceId", "reason", "name", "orgId", "projectId", "scope"
```
> lock-task: cleanup lock condition

- console2/src/api/process/event/index.ts
- console2/src/components/organisms/TaskCallDetails/index.tsx
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/el/resolvers/TaskMethodResolver.java
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/remote/EventRecordingExecutionListener.java
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/remote/TaskCallEventRecordingListener.java
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/tasks/TaskCallEvent.java
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/tasks/TaskCallInterceptor.java
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/vm/TaskCallCommand.java
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/vm/TaskResumeCommand.java
> runtime-v2: threadId to task details

- plugins/pom.xml
- plugins/tasks/asserts/pom.xml
- plugins/tasks/asserts/src/main/java/com/walmartlabs/concord/plugins/asserts/AssertsTask.java
`asserts.hasVariable` - asserts that a variable exist, not null, not empty. If it isn't it throws an exception.
`asserts.hasFile` - asserts that a file exists. If it isn't it throws an exception.
`aserts.assertEquals` - asserts that two objects are equal. If they are not an exception is thrown.
`aserts.assertTrue` - asserts that a condition is true. If it isn't it throws an exception.
> asserts task

- cli/src/main/java/com/walmartlabs/concord/cli/runner/CliDockerService.java
- cli/src/main/java/com/walmartlabs/concord/cli/runner/CliSecretService.java
- examples/README.md
- examples/ansible/concord.yml
- examples/ansible_docker/concord.yml
- examples/ansible_dynamic_inventory/concord.yml
- examples/ansible_form/concord.yml
- examples/ansible_form_as_inventory/concord.yml
- examples/ansible_kerberos/concord.yml
- examples/ansible_limit/concord.yml
- examples/ansible_out_vars/concord.yml
- examples/ansible_remote/concord.yml
- examples/ansible_retry/concord.yml
- examples/ansible_roles/concord.yml
- examples/ansible_stats/concord.yml
- examples/ansible_vault/concord.yml
- examples/ansible_windows/concord.yml
- examples/inventory/concord.yml
- examples/inventory_lookup/concord.yml
- examples/secret_lookup/concord.yml
- plugins/tasks/ansible/src/main/java/com/walmartlabs/concord/plugins/ansible/AnsibleTask.java
- plugins/tasks/ansible/src/main/java/com/walmartlabs/concord/plugins/ansible/PlaybookScriptBuilder.java
- plugins/tasks/ansible/src/main/java/com/walmartlabs/concord/plugins/ansible/TaskParams.java
Plus some minor updates to `examples/`.
> ansible-tasks: be more helpful when commands are missing

- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/el/resolvers/MapELResolver.java
- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/el/resolvers/SensitiveDataProcessor.java
check any `T get(Object key)` method as @sensitiveData method
> runtime-v2: sensitive data in maps

- server/impl/src/main/java/com/walmartlabs/concord/server/events/github/Payload.java
`status`
`workflow_job`
`workflow_run`
> concord-server: add some missing GHA event types

- agent/pom.xml
- plugins/tasks/http/pom.xml
- runtime/v1/impl/pom.xml
- server/impl/pom.xml
- server/plugins/ansible/impl/pom.xml
- server/plugins/noderoster/impl/pom.xml
- server/plugins/oneops/pom.xml
- server/queue-client/pom.xml
- server/sdk/pom.xml
- targetplatform/pom.xml
> project: upgrade dependencies

- console2/src/api/process/index.ts
- console2/src/components/molecules/ProcessList/index.tsx
- console2/src/components/organisms/ProcessActivity/Toolbar.tsx
- server/db/src/main/resources/com/walmartlabs/concord/server/db/liquibase.xml
- server/db/src/main/resources/com/walmartlabs/concord/server/db/v2.14.0.xml
- server/impl/src/main/java/com/walmartlabs/concord/server/process/ProcessEntry.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/ProcessModule.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/TotalRuntimeCalculator.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/queue/ProcessQueueDao.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/queue/ProcessQueueManager.java
- server/impl/src/main/java/com/walmartlabs/concord/server/process/queue/ProcessStatusListener.java
> concord-server: calculate total process run time

- plugins/tasks/resource/src/main/java/com/walmartlabs/concord/plugins/resource/ResourceTaskCommon.java
- plugins/tasks/resource/src/main/java/com/walmartlabs/concord/plugins/resource/v2/ResourceTaskV2.java
- plugins/tasks/resource/src/test/java/com/walmartlabs/concord/plugins/resource/ResourceTaskCommonTest.java
> resource-tasks: add versions of writeAs* methods that accept destination

- pom.xml
Align versions in the parent POM with the targetplatform versions.
> project: update dependency versions in parent pom

- it/runtime-v1/src/test/java/com/walmartlabs/concord/it/runtime/v1/ProcessIT.java
- it/runtime-v1/src/test/resources/com/walmartlabs/concord/it/runtime/v1/processWithChildSuspend/concord.yml
- it/runtime-v1/src/test/resources/com/walmartlabs/concord/it/runtime/v1/processWithChildSuspend/myPayload/concord.yml
- it/runtime-v1/src/test/resources/com/walmartlabs/concord/it/runtime/v1/processWithChildSuspendWithoutOut/concord.yml
- it/runtime-v1/src/test/resources/com/walmartlabs/concord/it/runtime/v1/processWithChildSuspendWithoutOut/myPayload/concord.yml
- it/runtime-v1/src/test/resources/com/walmartlabs/concord/it/runtime/v1/processWithChildrenSuspend/concord.yml
- targetplatform/pom.xml
> backport #955 to 2.14.x branch

- server/db/src/main/resources/com/walmartlabs/concord/server/db/v1.58.0.xml
For situations when superuserAvailable=false.
> concord-server: fix DB change set

- .github/workflows/build.yml
docker-login@v2 stopped working for some reason.
> project: update docker-login action in build flow

- targetplatform/pom.xml
Mostly what dependabot suggests, only newer.
> project: update dependencies

- agent-operator/pom.xml
- agent-operator/src/main/java/com/walmartlabs/concord/agentoperator/PodUtils.java
- agent-operator/src/main/java/com/walmartlabs/concord/agentoperator/crd/AgentPoolList.java
- agent-operator/src/main/java/com/walmartlabs/concord/agentoperator/planner/DeleteConfigMapChange.java
- targetplatform/pom.xml
Changes:
- update Jackson to latest 2.x
- migrate to kubernetes-client 7.x
- remove some dead code from agent-operator
- update SnakeYAML and slf4j versions as required by kubernetes-client
> targetplatform: update dependencies

- runtime/v2/runner/src/main/java/com/walmartlabs/concord/runtime/v2/runner/remote/TaskCallEventRecordingListener.java
- runtime/v2/runner/src/test/java/com/walmartlabs/concord/runtime/v2/runner/remote/TaskCallEventRecordingListenerTest.java
Use `SensitiveDataHolder` for task parameter masking in addition to @SensitiveData annotation processing and in/out/meta blacklists.
> runtime-v2: use SensitiveDataHolder for task parameter masking

- server/queue-client/src/main/java/com/walmartlabs/concord/server/queueclient/QueueClient.java
It will also reduce the number of logs:
```
14:34:27.776 [qtp2117269355-3186] [WARN ] [] c.w.c.s.websocket.WebSocketListener - onWebSocketError ['7e0e7f9f-35d2-4dae-ace2-92504fa21de7', 'agent-00000 @ 1.2.3.4'] -> error: null
```
> server: proper close queue client

- server/impl/src/main/java/com/walmartlabs/concord/server/security/rememberme/ConcordRememberMeManager.java
from java doc:
request.getCookies():
```
* @return		an array of all the <code>Cookies</code>
*			included with this request, or <code>null</code>
*			if the request has no cookies
```
> concord-server: handle request without cookies

- plugins/tasks/misc/src/main/java/com/walmartlabs/concord/plugins/misc/CollectionsTaskV2.java
- plugins/tasks/misc/src/main/java/com/walmartlabs/concord/plugins/misc/EnvTaskV2.java
- server/impl/src/main/java/com/walmartlabs/concord/server/ApiServerModule.java
- server/impl/src/main/java/com/walmartlabs/concord/server/GenericRequestErrorHandler.java
- server/impl/src/main/java/com/walmartlabs/concord/server/console/ResponseTemplates.java
- server/impl/src/main/resources/com/walmartlabs/concord/server/console/genericError.html
Don't let stack traces through for unexpected errors.
> server: default message for unexpected errors

- it/testing-server/src/main/java/com/walmartlabs/concord/it/testingserver/TestingConcordServer.java
- server/impl/src/main/java/com/walmartlabs/concord/server/ConcordServer.java
- server/impl/src/main/java/com/walmartlabs/concord/server/boot/BackgroundTasks.java
- server/impl/src/main/java/com/walmartlabs/concord/server/boot/HttpServer.java
> concord-server: log listening address, starting tasks

- examples/README.md
Add missing links, fix existing ones.
We should convert all examples to runtime-v2 at some point, maybe AI can help with it. ;-)
> examples: update description

- SECURITY.md
> project: fix typo
